### ISSUE TITLE
Found on Jan at 0826 on 11/3/16

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1014]
active branch=None

active analyses=bc-02-J-80

```
Traceback (most recent call last):
  File "/Users/jan/Programming/git/pychron/pychron/core/helpers/exception_helper.py", line 275, in run_with_except_hook
    run_old(*args, **kw)
  File "/Users/jan/anaconda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/jan/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 472, in _execute
    self._execute_queue(i, exp)
  File "/Users/jan/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 593, in _execute_queue
    self._join_run(spec, run)
  File "/Users/jan/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 688, in _join_run
    self._do_run(run)
  File "/Users/jan/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 756, in _do_run
    run.save()
  File "/Users/jan/Programming/git/pychron/pychron/experiment/automated_run/automated_run.py", line 1037, in save
    self._persister_save_action('post_measurement_save')
  File "/Users/jan/Programming/git/pychron/pychron/experiment/automated_run/automated_run.py", line 1496, in _persister_save_action
    getattr(self.dvc_persister, func)(*args, **kw)
  File "/Users/jan/Programming/git/pychron/pychron/dvc/dvc_persister.py", line 194, in post_measurement_save
    self._save_analysis(timestamp)
  File "/Users/jan/Programming/git/pychron/pychron/dvc/dvc_persister.py", line 365, in _save_analysis
    'value': float(nominal_value(iso.uvalue)),
  File "/Users/jan/Programming/git/pychron/pychron/processing/isotope.py", line 367, in uvalue
    v = ufloat(self.value, self.error, tag=self.name)
  File "/Users/jan/Programming/git/pychron/pychron/processing/isotope.py", line 295, in error
    v = self.regressor.predict_error(0)
  File "/Users/jan/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 174, in predict_error
    e = self.predict_error_matrix(x, error_calc)
  File "/Users/jan/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 211, in predict_error_matrix
    sef = self.calculate_standard_error_fit()
  File "/Users/jan/Programming/git/pychron/pychron/core/regression/base_regressor.py", line 155, in calculate_standard_error_fit
    res = self.calculate_residuals()
  File "/Users/jan/Programming/git/pychron/pychron/core/regression/base_regressor.py", line 167, in calculate_residuals
    return self.clean_ys - self.predict(self.clean_xs)
ValueError: operands could not be broadcast together with shapes (600,) (573,) 

```

**Comment by wcmcintosh** [comment]
is this issue still current?
