### ISSUE TITLE
error when adding pause to experiment editor

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1031]
active branch=None

active analyses=

```
Traceback (most recent call last):
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traits/trait_notifiers.py", line 615, in dispatch
    handler( *args )
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 824, in _evaluate_when
    self._do_evaluate_when(at_init=False)
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 838, in _do_evaluate_when
    self._evaluate_condition(self._visible, 'visible', at_init)
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 883, in _evaluate_condition
    context = self._get_context( self.context )
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 804, in _get_context
    context2 = value.trait_get()
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traits/has_traits.py", line 1485, in trait_get
    value = getattr( self, name, Missing )
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traits/has_traits.py", line 896, in decorator
    self.__dict__[ name ] = result = function( self )
  File "/Users/obama/Programming/git/pychron/pychron/experiment/automated_run/factory.py", line 1098, in _get_flux
    return self._get_flux_from_datastore()
  File "/Users/obama/Programming/git/pychron/pychron/experiment/automated_run/factory.py", line 1115, in _get_flux_from_datastore
    j = self.dvc.get_flux(self.selected_irradiation, self.selected_level, int(self.irrad_hole)) or 0
  File "/Users/obama/Programming/git/pychron/pychron/dvc/dvc.py", line 261, in get_flux
    j, lambda_k = self.meta_repo.get_flux(irrad, level, pos)
  File "/Users/obama/Programming/git/pychron/pychron/dvc/meta_repo.py", line 596, in get_flux
    positions = self._get_level_positions(irradiation, level)
  File "/Users/obama/Programming/git/pychron/pychron/dvc/meta_repo.py", line 660, in _get_level_positions
    positions = obj['positions']
KeyError: 'positions'

```

**Comment by jirhiker** [comment]
likely resolved in latest release
