### ISSUE TITLE
error on baselin refit

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1042]
active branch=None

active analyses=c-02-F-570

```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 58, in _model_changed
    self.refresh(clear=True)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 43, in refresh
    comp.add(p.make_graph())
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 42, in dec
    return func(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/panels/figure_panel.py", line 120, in make_graph
    fig.plot(plots, legend)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/iso_evo.py", line 39, in plot
    self._plot(i, p)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/iso_evo.py", line 62, in _plot
    xma, xmi, yma, ymi, scatter, ins = self._plot_baseline(i, iso, p, xma, xmi, yma, ymi)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/iso_evo.py", line 138, in _plot_baseline
    color='black')
ValueError: too many values to unpack

```

**Comment by wcmcintosh** [comment]
All well now.  Close issue?
