### ISSUE TITLE
error on recall of fixed peak hop analysis

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1047]
When I try to recall ic-01-f-11
I get the following error

```
nspection                              : 2016-12-12 14:02:54,514 DEBUG     (MainThread) pull called by sync_repo. parent call=<pychron.dvc.dvc.DVC object at 0x124bde7d0> repo.pull(use_progress=use_progress)
laboratory<GitRepo>                     : 2016-12-12 14:02:54,514 DEBUG     (MainThread) pulling master from origin
laboratory<GitRepo>                     : 2016-12-12 14:02:54,516 DEBUG     (MainThread) pulling from url: https://github.com/NMGRLData/laboratory.git
root                                    : 2016-12-12 14:02:56,182 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2016-12-12 14:02:56,183 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2016-12-12 14:02:56,183 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
root                                    : 2016-12-12 14:02:56,183 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
root                                    : 2016-12-12 14:02:56,183 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/browser_task.py", line 368, in _handle_dclicked
    self._recall_item(new.item)
root                                    : 2016-12-12 14:02:56,183 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/browser_task.py", line 311, in _recall_item
    self.recall(item, open_copy=open_copy)
root                                    : 2016-12-12 14:02:56,183 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/browser_task.py", line 142, in recall
    ans = self.dvc.make_analyses(records)
root                                    : 2016-12-12 14:02:56,184 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 545, in make_analyses
    ret = progress_loader(records, func, threshold=1, step=25)
root                                    : 2016-12-12 14:02:56,184 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 100, in progress_loader
    items = list(gen())
root                                    : 2016-12-12 14:02:56,184 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 82, in gen
    r = func(x, prog, i, n)
root                                    : 2016-12-12 14:02:56,184 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 541, in func
    r = make_record(calculate_f_only=calculate_f_only, *args)
root                                    : 2016-12-12 14:02:56,184 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 965, in _make_record
    a = DVCAnalysis(rid, expid)
root                                    : 2016-12-12 14:02:56,184 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc_analysis.py", line 141, in __init__
    self.load_paths()
root                                    : 2016-12-12 14:02:56,184 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc_analysis.py", line 153, in load_paths
    func(jd)
root                                    : 2016-12-12 14:02:56,185 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc_analysis.py", line 364, in _load_peakcenter
    self.peak_center_data = unpack(pd['data'], jd['fmt'], decode=True)
root                                    : 2016-12-12 14:02:56,185 CRITICAL  (MainThread) KeyError: 'data'
root                                    : 2016-12-12 14:02:56,185 CRITICAL  (MainThread) ============ End Exception ==========



```

**Comment by wcmcintosh** [comment]
pychron quits after error

**Comment by wcmcintosh** [comment]
Tested, seems OK now.
