### ISSUE TITLE
error on view fusions diode - maybe not a necessary feature

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1087]
active branch=None

active analyses=

```
Traceback (most recent call last):
  File "/Users/obama/anaconda/lib/python2.7/site-packages/pyface/ui/qt4/action/action_item.py", line 163, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/obama/anaconda/lib/python2.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/obama/Programming/git/pychron_dev/pychron/envisage/tasks/base_task.py", line 111, in perform
    application.open_task(self.task_id)
  File "/Users/obama/Programming/git/pychron_dev/pychron/envisage/tasks/base_tasks_application.py", line 119, in open_task
    return self.get_task(tid, True, **kw)
  File "/Users/obama/Programming/git/pychron_dev/pychron/envisage/tasks/base_tasks_application.py", line 109, in get_task
    win = self.create_window(w)
  File "/Users/obama/anaconda/lib/python2.7/site-packages/envisage/ui/tasks/tasks_application.py", line 205, in create_window
    window.add_task(task)
  File "/Users/obama/anaconda/lib/python2.7/site-packages/pyface/tasks/task_window.py", line 182, in add_task
    state.central_pane.create(self.control)
  File "/Users/obama/anaconda/lib/python2.7/site-packages/pyface/tasks/traits_task_pane.py", line 40, in create
    self.ui = self.edit_traits(kind='subpanel', parent=parent)
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traits/has_traits.py", line 1859, in edit_traits
    handler, id, scrollable, args )
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traitsui/qt4/toolkit.py", line 140, in ui_subpanel
    ui_panel.ui_subpanel( ui, parent )
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 79, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 92, in _ui_panel_for
    ui.prepare_ui()
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 456, in prepare_ui
    self._do_evaluate_when(at_init=True)
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 838, in _do_evaluate_when
    self._evaluate_condition(self._visible, 'visible', at_init)
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 883, in _evaluate_condition
    context = self._get_context( self.context )
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 804, in _get_context
    context2 = value.trait_get()
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traits/has_traits.py", line 1485, in trait_get
    value = getattr( self, name, Missing )
  File "/Users/obama/Programming/git/pychron_dev/pychron/lasers/laser_managers/base_lase_manager.py", line 379, in _pattern_executor_default
    from pychron.lasers.pattern.pattern_executor import PatternExecutor
  File "/Users/obama/Programming/git/pychron_dev/pychron/lasers/pattern/pattern_executor.py", line 32, in <module>
    from pychron.lasers.pattern.dragonfly_pattern import dragonfly
  File "/Users/obama/Programming/git/pychron_dev/pychron/lasers/pattern/dragonfly_pattern.py", line 25, in <module>
    from pychron.lasers.pattern.seek_pattern import SeekPattern
  File "/Users/obama/Programming/git/pychron_dev/pychron/lasers/pattern/seek_pattern.py", line 27, in <module>
    from pychron.mv.lumen_detector import LumenDetector
  File "/Users/obama/Programming/git/pychron_dev/pychron/mv/lumen_detector.py", line 24, in <module>
    from skimage.draw._draw import line, _coords_inside_image
ImportError: cannot import name _coords_inside_image

```

**Comment by jirhiker** [comment]
skimage dependency version mismatch
