### ISSUE TITLE
error on diff view

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1090]
active branch=None

active analyses=65495-02D

tried diff view for 65495-02D

```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/ui/qt4/action/action_item.py", line 343, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/argonlab2/.pychron/updates/pychron/pipeline/tasks/task.py", line 172, in diff_analysis
    editor.set_diff(left)
  File "/Users/argonlab2/.pychron/updates/pychron/pipeline/editors/diff_editor.py", line 241, in set_diff
    self._set_values(left, right, isotopes)
  File "/Users/argonlab2/.pychron/updates/pychron/pipeline/editors/diff_editor.py", line 296, in _set_values
    rvalue=nominal_value(right.r3739)))
  File "/Users/argonlab2/.pychron/updates/pychron/processing/isotope_group.py", line 357, in __getattr__
    raise AttributeError(attr)
AttributeError: r3739

```

**Comment by wcmcintosh** [comment]
OK
