### ISSUE TITLE
save interpreted age - not using same criteria as figure?  not recognizing 2 step plateau that is correctly recognized on figure 

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1105]
```
Pipeline Data Processing                : 2017-05-22 16:24:28,135 DEBUG     (MainThread) true run pipeline run_pipeline
no icon for ".png"
Inspection                              : 2017-05-22 16:24:28,148 DEBUG     (MainThread) make_graph called by refresh. parent call=<pychron.pipeline.plot.figure_container.FigureContainer object at 0x12ad65050> comp.add(p.make_graph())
seting ylimits 0
has ymin max set 20.0 35.0
seting ylimits 1
has calculated 60.7478519399 98.3174341404
Pipeline Data Processing                : 2017-05-22 16:24:28,272 DEBUG     (MainThread) run pipeline finished
root                                    : 2017-05-22 16:25:24,645 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2017-05-22 16:25:24,645 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2017-05-22 16:25:24,646 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
root                                    : 2017-05-22 16:25:24,646 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
root                                    : 2017-05-22 16:25:24,646 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traits/has_traits.py", line 1196, in wrapper0
    return function(arg)
root                                    : 2017-05-22 16:25:24,646 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traits/has_traits.py", line 3535, in notify
    self.trait_property_changed( name, None )
root                                    : 2017-05-22 16:25:24,646 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 434, in _get_preferred_mswd
    return self.plateau_mswd
root                                    : 2017-05-22 16:25:24,646 CRITICAL  (MainThread) AttributeError: 'InterpretedAgeGroup' object has no attribute 'plateau_mswd'
root                                    : 2017-05-22 16:25:24,647 CRITICAL  (MainThread) ============ End Exception ==========
2017-05-22 16:25:31.842 python[12096:1854079] modalSession has been exited prematurely - check for a reentrant call to endModalSession:

```

**Comment by wcmcintosh** [comment]
OK now I think.
