### ISSUE TITLE
hoverr error in interpreted age ideogram

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1108]
active branch=None

active analyses=65495-13A,65495-13B,65495-13C,65495-13D,65495-13E

```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/enable/qt4/base_window.py", line 198, in paintEvent
    self.handler.paintEvent(event)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/enable/qt4/base_window.py", line 50, in paintEvent
    self._enable_window._paint(event)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/enable/abstract_window.py", line 467, in _paint
    self.component.draw(gc, view_bounds=(0, 0, size[0], size[1]))
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/enable/component.py", line 421, in draw
    self._draw(gc, view_bounds, mode)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/enable/component.py", line 770, in _draw
    self._dispatch_draw("overlay", gc, view_bounds, mode)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/enable/container.py", line 327, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/enable/container.py", line 327, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/enable/container.py", line 327, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/enable/component.py", line 793, in _dispatch_draw
    handler(gc, view_bounds, mode)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/enable/component.py", line 871, in _draw_overlay
    overlay.overlay(self, gc, view_bounds, mode)
  File "/Users/mcintosh/Programming/git/pychron/pychron/graph/tools/info_inspector.py", line 124, in overlay
    lines = self.tool.assemble_lines()
  File "/Users/mcintosh/Programming/git/pychron/pychron/graph/tools/analysis_inspector.py", line 156, in assemble_lines
    ad = self.additional_info(ind, xs[ind], ys[ind], analysis)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/ideogram.py", line 337, in <lambda>
    f = lambda i, x, y, ai: u'{}= {}'.format(name, ai.value_string(ia))
AttributeError: 'DVCInterpretedAge' object has no attribute 'value_string'

```

**Comment by wcmcintosh** [comment]
Hovering fine now
