### ISSUE TITLE
frequent error when changing pipelines

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1114]
'''
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 836, in _selected_changed
    if new.editors:
AttributeError: 'SpectrumNode' object has no attribute 'editors'

'''

**Comment by wcmcintosh** [comment]
not show stopper
