### ISSUE TITLE
error while setting two omit tags to OK

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1122]
active branch=None

active analyses=65496-05A,65496-05B,65496-05C,65496-05D,65496-05E

```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/ui/qt4/action/action_item.py", line 343, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 250, in set_tag
    if not isinstance(InterpretedAge):
TypeError: isinstance expected 2 arguments, got 1

```

**Comment by wcmcintosh** [comment]
tagging working well now
