### ISSUE TITLE
Error in IA Table pipeline - all IAs found correctly though

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1126]
active branch=None

active analyses=

```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 583, in _handle_run_needed
    self.run()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 317, in run
    self._run_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 512, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 491, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 598, in run_pipeline
    if not node.pre_run(state):
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/base.py", line 87, in pre_run
    if self.configure(refresh=False, pre_run=True):
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/data.py", line 95, in configure
    interpreted_ages = self.dvc.make_interpreted_ages(records)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 531, in make_interpreted_ages
    return progress_loader(ias, func, step=25)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 100, in progress_loader
    items = list(gen())
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 91, in gen
    r = func(x, None, 0, 0)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 525, in func
    ia.load_tag(dvc_load(ta))
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/__init__.py", line 46, in dvc_load
    if os.path.isfile(path):
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

```

**Comment by wcmcintosh** [comment]
A-OK now
