### ISSUE TITLE
sample entry issue

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1139]
active branch=None

active analyses=bc-02-J-617

Everytime I add this particular sample, I am no longer able to save or edit the experiment 

```
Traceback (most recent call last):
  File "/Users/jan/anaconda/envs/pychron_env/lib/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/jan/anaconda/envs/pychron_env/lib/python2.7/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/Users/jan/Programming/git/pychron_dev/pychron/experiment/experimentor.py", line 318, in _selected_changed
    self.stats.calculate_at(a, at_times=self.executor.is_alive())
  File "/Users/jan/Programming/git/pychron_dev/pychron/experiment/stats.py", line 267, in calculate_at
    ei.executed_runs + ei.cleaned_automated_runs[:si]) + ei.delay_between_analyses
  File "/Users/jan/Programming/git/pychron_dev/pychron/experiment/stats.py", line 65, in calculate_duration
    dur = self._calculate_duration(runs)
  File "/Users/jan/Programming/git/pychron_dev/pychron/experiment/stats.py", line 186, in _calculate_duration
    run_dur += a.get_estimated_duration(script_ctx, warned, True)
  File "/Users/jan/Programming/git/pychron_dev/pychron/experiment/automated_run/spec.py", line 286, in get_estimated_duration
    s = self.test_scripts(script_context, warned)
  File "/Users/jan/Programming/git/pychron_dev/pychron/experiment/automated_run/spec.py", line 223, in test_scripts
    arun.refresh_scripts()
  File "/Users/jan/Programming/git/pychron_dev/pychron/experiment/automated_run/automated_run.py", line 1441, in refresh_scripts
    self._refresh_scripts()
  File "/Users/jan/Programming/git/pychron_dev/pychron/experiment/automated_run/automated_run.py", line 1683, in _refresh_scripts
    setattr(self, '{}_script'.format(name), self._load_script(name))
  File "/Users/jan/Programming/git/pychron_dev/pychron/experiment/automated_run/automated_run.py", line 2465, in _load_script
    script = self._bootstrap_script(sname, name)
  File "/Users/jan/Programming/git/pychron_dev/pychron/experiment/automated_run/automated_run.py", line 2482, in _bootstrap_script
    s = func()
  File "/Users/jan/Programming/git/pychron_dev/pychron/experiment/automated_run/automated_run.py", line 2514, in _extraction_script_factory
    ext.automated_run = self
AttributeError: 'NoneType' object has no attribute 'automated_run'

```

**Comment by jirhiker** [comment]
see #1138
