### ISSUE TITLE
repository access problem

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1360]
request for data in repositories not already on my laptop is giving the following error

pychronmeta                             : 2018-04-12 13:58:24,155 DEBUG     (MainThread) SELECT DISTINCT "IrradiationPositionTbl".id, "IrradiationPositionTbl".identifier, "IrradiationPositionTbl"."sampleID", "IrradiationPositionTbl"."levelID", "IrradiationPositionTbl".position, "IrradiationPositionTbl".note, "IrradiationPositionTbl".weight, "IrradiationPositionTbl".j, "IrradiationPositionTbl".j_err 
FROM "IrradiationPositionTbl" JOIN "AnalysisTbl" ON "IrradiationPositionTbl".id = "AnalysisTbl"."irradiation_positionID" JOIN "LevelTbl" ON "LevelTbl".id = "IrradiationPositionTbl"."levelID" JOIN "IrradiationTbl" ON "IrradiationTbl".id = "LevelTbl"."irradiationID" 
WHERE "IrradiationTbl".name = 'NM-274' AND "LevelTbl".name = 'E' GROUP BY "IrradiationPositionTbl".id 
HAVING count("AnalysisTbl".id) > 0
SampleBrowserModel                      : 2018-04-12 13:58:24,162 DEBUG     (MainThread) _retrieve_labnumbers n=16
SampleBrowserModel                      : 2018-04-12 13:58:36,722 DEBUG     (MainThread) retrieving identifiers=24230
pychronmeta                             : 2018-04-12 13:58:37,141 DEBUG     (MainThread) SELECT "AnalysisTbl".id, "AnalysisTbl".timestamp, "AnalysisTbl".uuid, "AnalysisTbl".analysis_type, "AnalysisTbl".aliquot, "AnalysisTbl".increment, "AnalysisTbl"."irradiation_positionID", "AnalysisTbl"."measurementName", "AnalysisTbl"."extractionName", "AnalysisTbl"."postEqName", "AnalysisTbl"."postMeasName", "AnalysisTbl".mass_spectrometer, "AnalysisTbl".extract_device, "AnalysisTbl".extract_value, "AnalysisTbl".extract_units, "AnalysisTbl".cleanup, "AnalysisTbl".duration, "AnalysisTbl".weight, "AnalysisTbl".comment 
FROM "AnalysisTbl" JOIN "IrradiationPositionTbl" ON "IrradiationPositionTbl".id = "AnalysisTbl"."irradiation_positionID" JOIN "AnalysisChangeTbl" ON "AnalysisTbl".id = "AnalysisChangeTbl"."analysisID" 
WHERE lower("IrradiationPositionTbl".identifier) IN ('24230') AND "AnalysisChangeTbl".tag != 'invalid' ORDER BY "AnalysisTbl".timestamp ASC
SampleBrowserModel                      : 2018-04-12 13:58:37,505 DEBUG     (MainThread) retrieved analyses n=3
SampleBrowserModel                      : 2018-04-12 13:58:37,505 DEBUG     (MainThread) make records 3
SampleBrowserModel                      : 2018-04-12 13:58:37,526 DEBUG     (MainThread) make records 0.020200014114379883
SampleBrowserModel                      : 2018-04-12 13:58:37,526 DEBUG     (MainThread) selected samples changed. loading analyses. low=None, high=None, limit=0 n=3
SampleBrowserModel                      : 2018-04-12 13:58:37,530 DEBUG     (MainThread) dump browser
SampleBrowserModel                      : 2018-04-12 13:58:37,568 DEBUG     (MainThread) $$$$$$$$$$$$$$$$$$$$$ Dumping browser selection
2018-04-12 13:58:42.407 python[12676:22796737] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
SampleBrowserModel                      : 2018-04-12 13:58:42,408 DEBUG     (MainThread) dump browser
SampleBrowserModel                      : 2018-04-12 13:58:42,446 DEBUG     (MainThread) $$$$$$$$$$$$$$$$$$$$$ Dumping browser selection
DVC                                     : 2018-04-12 13:58:42,484 DEBUG     (MainThread) sync repository Irradiation-NM-274. exists=False
DVC                                     : 2018-04-12 13:58:42,484 DEBUG     (MainThread) getting repository from remote
DVC                                     : 2018-04-12 13:58:42,484 DEBUG     (MainThread) load repositories from NMGRLData
root                                    : 2018-04-12 13:58:42,485 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2018-04-12 13:58:42,485 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2018-04-12 13:58:42,485 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
root                                    : 2018-04-12 13:58:42,485 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
root                                    : 2018-04-12 13:58:42,486 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
root                                    : 2018-04-12 13:58:42,486 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 308, in run
    self._run_pipeline()
root                                    : 2018-04-12 13:58:42,486 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 486, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
root                                    : 2018-04-12 13:58:42,486 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 465, in _run
    if not getattr(self.engine, func)():
root                                    : 2018-04-12 13:58:42,486 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 704, in run_pipeline
    if not node.pre_run(state):
root                                    : 2018-04-12 13:58:42,486 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/base.py", line 93, in pre_run
    if self.configure(refresh=False, pre_run=True):
root                                    : 2018-04-12 13:58:42,486 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/data.py", line 134, in configure
    return self.set_browser_analyses()
root                                    : 2018-04-12 13:58:42,486 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/data.py", line 72, in set_browser_analyses
    is_append, analyses = self.get_browser_analyses()
root                                    : 2018-04-12 13:58:42,486 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/data.py", line 68, in get_browser_analyses
    records = self.dvc.make_analyses(records)
root                                    : 2018-04-12 13:58:42,486 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 739, in make_analyses
    branches = {ei: get_repository_branch(os.path.join(paths.repository_dataset_dir, ei)) for ei in exps}
root                                    : 2018-04-12 13:58:42,487 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 739, in <dictcomp>
    branches = {ei: get_repository_branch(os.path.join(paths.repository_dataset_dir, ei)) for ei in exps}
root                                    : 2018-04-12 13:58:42,487 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/git_archive/repo_manager.py", line 44, in get_repository_branch
    r = Repo(path)
root                                    : 2018-04-12 13:58:42,487 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/git/repo/base.py", line 126, in __init__
    raise NoSuchPathError(epath)
root                                    : 2018-04-12 13:58:42,487 CRITICAL  (MainThread) git.exc.NoSuchPathError: /Users/mcintosh/Pychron_dev/data/.dvc/repositories/Irradiation-NM-274
root                                    : 2018-04-12 13:58:42,487 CRITICAL  (MainThread) ============ End Exception ==========
ignore exception
Pipeline Data Processing                : 2018-04-12 13:58:55,088 DEBUG     (MainThread) recall 24230-01 <pychron.database.records.isotope_record.DVCIsotopeRecordView object at 0x1c492bfb00>
DVC                                     : 2018-04-12 13:58:55,088 DEBUG     (MainThread) sync repository Irradiation-NM-274. exists=False
DVC                                     : 2018-04-12 13:58:55,089 DEBUG     (MainThread) getting repository from remote
DVC                                     : 2018-04-12 13:58:55,089 DEBUG     (MainThread) load repositories from NMGRLData
Traceback (most recent call last):
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/browser_task.py", line 327, in _handle_dclicked
    self._recall_item(new.item)
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/browser_task.py", line 273, in _recall_item
    self.recall(item, open_copy=open_copy)
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/browser_task.py", line 132, in recall
    ans = self.dvc.make_analyses(records)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 739, in make_analyses
    branches = {ei: get_repository_branch(os.path.join(paths.repository_dataset_dir, ei)) for ei in exps}
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 739, in <dictcomp>
    branches = {ei: get_repository_branch(os.path.join(paths.repository_dataset_dir, ei)) for ei in exps}
  File "/Users/mcintosh/Programming/git/pychron/pychron/git_archive/repo_manager.py", line 44, in get_repository_branch
    r = Repo(path)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/git/repo/base.py", line 126, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /Users/mcintosh/Pychron_dev/data/.dvc/repositories/Irradiation-NM-274
Pipeline Data Processing                : 2018-04-12 13:58:55,090 CRITICAL  (MainThread) analysis_table:dclicked error /Users/mcintosh/Pychron_dev/data/.dvc/repositories/Irradiation-NM-274

**Comment by wcmcintosh** [comment]
All seems well after change of password top token. Ready to close
