### ISSUE TITLE
test return

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1384]
active branch=None

active analyses=24238-01,24238-02,24238-03,24239-01,24239-02,24239-03,24240-01,24240-02,24240-03,24241-01,24241-02,24241-03,24242-01,24242-02,24242-03,24242-04,24243-01,24243-02,24243-03,24244-01,24244-02,24244-03,24245-01,24245-02,24245-03,24245-04

```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 308, in run
    self._run_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 489, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 468, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 722, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/fit.py", line 441, in run
    super(FitFluxNode, self).run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/figure.py", line 95, in run
    editor.component.invalidate_and_redraw()
AttributeError: 'FluxResultsEditor' object has no attribute 'component'

```

**Comment by wcmcintosh** [comment]
Can't reproduce No title provided so far
