### ISSUE TITLE
flux viewing update

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1388]
If I refit a tray with monte carlo errors, the correct errors are added to the database, but the changes do not appears in the lab number entry window until pychron is restarted

**Comment by wcmcintosh** [comment]
Refit with Monte Carlo updates the labnumber entry window just fine

However, refitting with weighted error checked now triggers the following error

I realize that the current output of the weighted error is not useful, just reporting the error

Also, should check boxes of  weighted error vs monte carlo be mutually exclusive? currently the user can check both

```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 308, in run
    self._run_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 489, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 468, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 722, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/fit.py", line 462, in run
    editor.predict_values()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/editors/flux_results_editor.py", line 341, in predict_values
    self._graph_hole_vs_j(x, y, r, reg, refresh)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/editors/flux_results_editor.py", line 420, in _graph_hole_vs_j
    l, u = reg.calculate_error_envelope(fxs, rmodel=fys)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/base_regressor.py", line 230, in calculate_error_envelope
    return func(rx, rmodel)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/base_regressor.py", line 233, in calculate_sd_error_envelope
    es = self.predict_error(rx, error_calc='SD')
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 169, in predict_error
    e = self.predict_error_matrix(x, error_calc)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 235, in predict_error_matrix
    return [func(xi) for xi in x]
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 235, in <listcomp>
    return [func(xi) for xi in x]
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 229, in func
    varY_hat = calc_hat(xi)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 209, in calc_hat
    Xk = self._get_X(xi).T
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 373, in _get_X
    r, c = xs.shape
ValueError: not enough values to unpack (expected 2, got 0)


```

**Comment by wcmcintosh** [comment]
refitting with weighted error now does not trigger error
weighted error and monte carlo error still can both be checked at the same time, not mutually exclusive

**Comment by jirhiker** [comment]
"weighted error and monte carlo error still can both be checked at the same time, not mutually exclusive" 

its not weighted error its weighted fit so theres nothing wrong with doing a monte carlo with a weighted fit
