### ISSUE TITLE
Pychron error. Looks like it was starting to peak center after air

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1394]
active branch=release/v17.7

active analyses=bu-FD-F-822

```
Traceback (most recent call last):
  File "/Users/obama/.pychron.1/updates/pychron/core/helpers/exception_helper.py", line 283, in run_with_except_hook
    run_old(*args, **kw)
  File "/anaconda2/envs/pychron/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/obama/.pychron.1/updates/pychron/experiment/experiment_executor.py", line 504, in _execute
    self._execute_queue(i, exp)
  File "/Users/obama/.pychron.1/updates/pychron/experiment/experiment_executor.py", line 647, in _execute_queue
    self._join_run(spec, run)
  File "/Users/obama/.pychron.1/updates/pychron/experiment/experiment_executor.py", line 744, in _join_run
    self._do_run(run)
  File "/Users/obama/.pychron.1/updates/pychron/experiment/experiment_executor.py", line 809, in _do_run
    if not f(run):
  File "/Users/obama/.pychron.1/updates/pychron/experiment/experiment_executor.py", line 1169, in _measurement
    if not ai.do_measurement():
  File "/Users/obama/.pychron.1/updates/pychron/experiment/automated_run/automated_run.py", line 1349, in do_measurement
    if script.execute():
  File "/Users/obama/.pychron.1/updates/pychron/pyscripts/pyscript.py", line 286, in execute
    return _ex_()
  File "/Users/obama/.pychron.1/updates/pychron/pyscripts/pyscript.py", line 271, in _ex_
    self._execute(trace=trace, argv=argv)
  File "/Users/obama/.pychron.1/updates/pychron/pyscripts/pyscript.py", line 723, in _execute
    error = self.execute_snippet(**kw)
  File "/Users/obama/.pychron.1/updates/pychron/pyscripts/pyscript.py", line 361, in execute_snippet
    func(*argv)
  File "<string>", line 83, in main
  File "/Users/obama/.pychron.1/updates/pychron/pyscripts/pyscript.py", line 88, in decorator
    return func(obj, *args, **kw)
  File "/Users/obama/.pychron.1/updates/pychron/pyscripts/measurement_pyscript.py", line 371, in peak_center
    save=save, config_name=config_name)
  File "/Users/obama/.pychron.1/updates/pychron/pyscripts/measurement_pyscript.py", line 906, in _automated_run_call
    return func(*args, **kw)
  File "/Users/obama/.pychron.1/updates/pychron/experiment/automated_run/automated_run.py", line 634, in py_peak_center
    ion.do_peak_center(new_thread=False, save=save, message='automated run peakcenter', timeout=300)
  File "/Users/obama/.pychron.1/updates/pychron/spectrometer/ion_optics/ion_optics_manager.py", line 170, in do_peak_center
    self._peak_center(*args)
  File "/Users/obama/.pychron.1/updates/pychron/spectrometer/ion_optics/ion_optics_manager.py", line 368, in _peak_center
    dac_d = pc.get_peak_center()
  File "/Users/obama/.pychron.1/updates/pychron/spectrometer/jobs/peak_center.py", line 113, in get_peak_center
    center, smart_shift, success = self.iteration(start, end, width)
  File "/Users/obama/.pychron.1/updates/pychron/spectrometer/jobs/peak_center.py", line 205, in iteration
    ok = self._do_sweep(start, end, width, directions=self.directions, map_mass=False)
  File "/Users/obama/.pychron.1/updates/pychron/spectrometer/jobs/magnet_sweep.py", line 95, in _do_sweep
    return super(MagnetSweep, self)._do_sweep(sm, em, stm, directions)
  File "/Users/obama/.pychron.1/updates/pychron/spectrometer/jobs/sweep.py", line 131, in _do_sweep
    if not self._sweep(values):
  File "/Users/obama/.pychron.1/updates/pychron/spectrometer/jobs/sweep.py", line 147, in _sweep
    intensity = self._step_intensity()
  File "/Users/obama/.pychron.1/updates/pychron/spectrometer/jobs/sweep.py", line 165, in _step_intensity
    intensity = spec.get_intensity(ds)
  File "/Users/obama/.pychron.1/updates/pychron/spectrometer/thermo/spectrometer/base.py", line 365, in get_intensity
    data = self.get_intensities()
  File "/Users/obama/.pychron.1/updates/pychron/spectrometer/base_spectrometer.py", line 403, in get_intensities
    self._check_intensity_no_change(signals)
  File "/Users/obama/.pychron.1/updates/pychron/spectrometer/base_spectrometer.py", line 422, in _check_intensity_no_change
    raise NoIntensityChange()
NoIntensityChange

```

**Comment by wcmcintosh** [comment]
Ready to close.  Hardware issue?
