### ISSUE TITLE
subn-grouping error

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1404]
active branch=None

active analyses=63457-01A,63457-01B,63457-01C,63457-01D,63457-01E,63457-01F,63457-02A,63457-02B,63457-02C,63457-02D,63457-02E,63457-02F,63457-02G,63457-03A,63457-03B,63457-03C,63457-03D,63457-04A,63457-04B,63457-04C,63457-04D,63457-05A,63457-05B,63457-05C,63457-05D

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 311, in resume
    self._resume_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 486, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 468, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 633, in resume_pipeline
    return self.run_pipeline(state=self.state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 722, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/persist.py", line 302, in run
    writer.build(groups, options=options)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 113, in build
    self._make_summary_sheet(unknowns)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 418, in _make_summary_sheet
    txt = self._get_txt(ug, ci)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 840, in _get_txt
    return func(item, attr)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/util.py", line 77, in value
    x = getattr(x, k)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/has_traits.py", line 896, in decorator
    self.__dict__[ name ] = result = function( self )
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 173, in _get_isochron_age
    return self.calculate_isochron_age()
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 343, in calculate_isochron_age
    args = self.get_isochron_data()
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 338, in get_isochron_data
    return calculate_isochron(ans, self.isochron_age_error_kind, exclude=exclude)
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/argon_calculations.py", line 69, in calculate_isochron
    ref = analyses[0]
IndexError: list index out of range

```

**Comment by jirhiker** [comment]
see #1403
