### ISSUE TITLE
error fitting IC factors ot Felix data 65773

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1416]
active branch=None

active analyses=a-01-F-2345,a-01-F-2346,a-01-F-2347,a-01-F-2348,a-01-F-2349,a-01-F-2350,a-01-F-2351

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 308, in run
    self._run_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 489, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 468, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 726, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/fit.py", line 79, in run
    if self.check_refit(unks):
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/fit.py", line 59, in check_refit
    if self._check_refit(ui):
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/fit.py", line 184, in _check_refit
    if not i.ic_factor_reviewed:
AttributeError: 'NoneType' object has no attribute 'ic_factor_reviewed'

```

**Comment by wcmcintosh** [comment]
Other related Jan samples worked fine
