### ISSUE TITLE
fusion table selected - still getting same error

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1420]
active branch=release/py3/v18.2

active analyses=66124-01A,66124-01B,66124-01C,66124-02A,66124-02B,66124-02C,66124-02D,66124-03A,66124-03B,66124-03C,66124-03D,66124-03E,66124-04A,66124-04B,66124-04C,66124-04D,66124-04E,66124-05B,66124-05C,66124-05D,66124-05E,66124-06B,66124-06C,66124-07A,66124-07C,66124-07D,66124-07E,66124-08A,66124-08B,66124-08C,66124-08D,66124-08E

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 445, in _make_irradiations
    txt = self._get_txt(ug.analyses[0], ci)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 849, in _get_txt
    return func(item, attr)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/util.py", line 50, in f
    if k in x.interference_corrections:
AttributeError: 'IntermediateAnalysis' object has no attribute 'interference_corrections'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 311, in resume
    self._resume_pipeline()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 486, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 468, in _run
    if not getattr(self.engine, func)():
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 637, in resume_pipeline
    return self.run_pipeline(state=self.state)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 726, in run_pipeline
    node.run(state)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/nodes/persist.py", line 302, in run
    writer.build(groups, options=options)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 109, in build
    self._make_irradiations(unknowns)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 447, in _make_irradiations
    txt = self._get_txt(ug, ci)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 849, in _get_txt
    return func(item, attr)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/util.py", line 50, in f
    if k in x.interference_corrections:
AttributeError: 'InterpretedAgeGroup' object has no attribute 'interference_corrections'

```

**Comment by jirhiker** [comment]
removed irradiation sheet
