### ISSUE TITLE
Showstopper error after review node in table pipeline

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1433]
```
PipelineEngine                          : 2018-05-06 18:13:32,880 DEBUG     (MainThread) load predefined templates
PipelineEngine                          : 2018-05-06 18:13:32,881 DEBUG     (MainThread) loaded 1 user templates
Pipeline Data Processing                : 2018-05-06 18:13:33,051 DEBUG     (MainThread) activating pipeline
DVC                                     : 2018-05-06 18:13:33,276 DEBUG     (MainThread) Initialize DVC
DVC                                     : 2018-05-06 18:13:33,276 DEBUG     (MainThread) open meta repo /Users/mcintosh/Pychron_dev/data/.dvc/MetaData
DVC                                     : 2018-05-06 18:13:33,276 DEBUG     (MainThread) Opening Meta Repo
MetaRepo                                : 2018-05-06 18:13:33,529 DEBUG     (MainThread) ahead behind
git.cmd                                 : 2018-05-06 18:13:33,530 DEBUG     (MainThread) Popen(['git', 'fetch', 'origin'], cwd=/Users/mcintosh/Pychron_dev/data/.dvc/MetaData, universal_newlines=False, shell=None)
git.cmd                                 : 2018-05-06 18:13:33,947 DEBUG     (MainThread) Popen(['git', 'status', '-sb'], cwd=/Users/mcintosh/Pychron_dev/data/.dvc/MetaData, universal_newlines=False, shell=None)
MetaRepo                                : 2018-05-06 18:13:33,985 DEBUG     (MainThread) Smart pull ahead: 0 behind: 0
MetaRepo                                : 2018-05-06 18:13:33,986 DEBUG     (MainThread) Up-to-date with origin
PipelineEngine                          : 2018-05-06 18:13:38,858 DEBUG     (MainThread) Pipeline template <pychron.pipeline.template.PipelineTemplate object at 0x1c317296d0> selected
no icon for ".png"
Unknowns<UnknownNode> True [] 0
Pipeline Data Processing                : 2018-05-06 18:13:41,101 DEBUG     (MainThread) run pipeline started
pychronmeta                             : 2018-05-06 18:13:41,102 DEBUG     (MainThread) force create new session 4717944592
PipelineEngine                          : 2018-05-06 18:13:41,102 DEBUG     (MainThread) pipeline run started
SampleBrowserModel                      : 2018-05-06 18:13:41,111 DEBUG     (MainThread) reattach
SampleBrowserModel                      : 2018-05-06 18:13:41,121 DEBUG     (MainThread) /Users/mcintosh/Pychron_dev/.appdata/browser_options
SampleBrowserModel                      : 2018-05-06 18:13:41,121 DEBUG     (MainThread) loading /Users/mcintosh/Pychron_dev/.appdata/browser_options
pychronmeta                             : 2018-05-06 18:13:41,123 DEBUG     (MainThread) SELECT "ProjectTbl".name, "ProjectTbl".id, "ProjectTbl"."principal_investigatorID", "ProjectTbl".checkin_date, "ProjectTbl".comment, "ProjectTbl".lab_contact, "ProjectTbl".institution 
FROM "ProjectTbl"
SampleBrowserModel                      : 2018-05-06 18:13:41,416 DEBUG     (MainThread) load principal investigators
pychronmeta                             : 2018-05-06 18:13:41,417 DEBUG     (MainThread) SELECT "PrincipalInvestigatorTbl".id, "PrincipalInvestigatorTbl".affiliation, "PrincipalInvestigatorTbl".email, "PrincipalInvestigatorTbl".last_name, "PrincipalInvestigatorTbl".first_initial 
FROM "PrincipalInvestigatorTbl" ORDER BY "PrincipalInvestigatorTbl".last_name ASC
SampleBrowserModel                      : 2018-05-06 18:13:41,425 DEBUG     (MainThread) n pis=110
pychronmeta                             : 2018-05-06 18:13:41,429 DEBUG     (MainThread) SELECT "ProjectTbl".name, "ProjectTbl".id, "ProjectTbl"."principal_investigatorID", "ProjectTbl".checkin_date, "ProjectTbl".comment, "ProjectTbl".lab_contact, "ProjectTbl".institution 
FROM "ProjectTbl" ORDER BY "ProjectTbl".name ASC
Inspection                              : 2018-05-06 18:13:42,272 DEBUG     (MainThread) _load_projects_and_irradiations called by activate_browser. parent call=<pychron.envisage.browser.sample_browser_model.SampleBrowserModel object at 0x12c9c6d58> self._load_projects_and_irradiations()
SampleBrowserModel                      : 2018-05-06 18:13:42,272 DEBUG     (MainThread) load_projects_and_irradiations
pychronmeta                             : 2018-05-06 18:13:42,273 DEBUG     (MainThread) SELECT "ProjectTbl".name, "ProjectTbl".id, "ProjectTbl"."principal_investigatorID", "ProjectTbl".checkin_date, "ProjectTbl".comment, "ProjectTbl".lab_contact, "ProjectTbl".institution 
FROM "ProjectTbl"
SampleBrowserModel                      : 2018-05-06 18:13:42,574 DEBUG     (MainThread) $$$$$$$$$$$$$$$$$$$$$ Loading browser selection
SampleBrowserModel                      : 2018-05-06 18:13:42,574 DEBUG     (MainThread) bbmodel selected projects=['IR998']
SampleBrowserModel                      : 2018-05-06 18:13:42,583 DEBUG     (MainThread) set posts lp=2017-08-12 12:31:32 hp=2017-09-04 17:05:35
Inspection                              : 2018-05-06 18:13:42,587 DEBUG     (MainThread) _load_associated_labnumbers called by _selected_projects_changed. parent call=<pychron.envisage.browser.sample_browser_model.SampleBrowserModel object at 0x12c9c6d58> self._load_associated_labnumbers()
Inspection                              : 2018-05-06 18:13:42,589 DEBUG     (MainThread) _make_labnumbers called by _load_associated_labnumbers. parent call=<pychron.envisage.browser.sample_browser_model.SampleBrowserModel object at 0x12c9c6d58> sams = self._make_labnumbers()
SampleBrowserModel                      : 2018-05-06 18:13:42,590 DEBUG     (MainThread) GET HPOST=None
SampleBrowserModel                      : 2018-05-06 18:13:42,590 DEBUG     (MainThread) GET LPOST=None
pychronmeta                             : 2018-05-06 18:13:42,590 DEBUG     (MainThread) ------- Get Labnumbers 4717944592-------
pychronmeta                             : 2018-05-06 18:13:42,590 DEBUG     (MainThread) ------- samples: None
pychronmeta                             : 2018-05-06 18:13:42,590 DEBUG     (MainThread) ------- principal_investigators: None
pychronmeta                             : 2018-05-06 18:13:42,590 DEBUG     (MainThread) ------- projects: ['IR998']
pychronmeta                             : 2018-05-06 18:13:42,590 DEBUG     (MainThread) ------- experiments: None
pychronmeta                             : 2018-05-06 18:13:42,591 DEBUG     (MainThread) ------- mass_spectrometers: []
pychronmeta                             : 2018-05-06 18:13:42,591 DEBUG     (MainThread) ------- irradiation: 
pychronmeta                             : 2018-05-06 18:13:42,591 DEBUG     (MainThread) ------- level: 
pychronmeta                             : 2018-05-06 18:13:42,591 DEBUG     (MainThread) ------- analysis_types: []
pychronmeta                             : 2018-05-06 18:13:42,591 DEBUG     (MainThread) ------- high_post: None
pychronmeta                             : 2018-05-06 18:13:42,591 DEBUG     (MainThread) ------- low_post: None
pychronmeta                             : 2018-05-06 18:13:42,591 DEBUG     (MainThread) ------- loads: []
pychronmeta                             : 2018-05-06 18:13:42,591 DEBUG     (MainThread) ------------------------------
pychronmeta                             : 2018-05-06 18:13:42,596 DEBUG     (MainThread) SELECT DISTINCT "IrradiationPositionTbl".id, "IrradiationPositionTbl".identifier, "IrradiationPositionTbl"."sampleID", "IrradiationPositionTbl"."levelID", "IrradiationPositionTbl".position, "IrradiationPositionTbl".note, "IrradiationPositionTbl".weight, "IrradiationPositionTbl".j, "IrradiationPositionTbl".j_err 
FROM "IrradiationPositionTbl" JOIN "SampleTbl" ON "SampleTbl".id = "IrradiationPositionTbl"."sampleID" JOIN "ProjectTbl" ON "ProjectTbl".id = "SampleTbl"."projectID" JOIN "AnalysisTbl" ON "IrradiationPositionTbl".id = "AnalysisTbl"."irradiation_positionID" 
WHERE "ProjectTbl".name IN ('IR998') GROUP BY "IrradiationPositionTbl".id 
HAVING count("AnalysisTbl".id) > 0
SampleBrowserModel                      : 2018-05-06 18:13:42,605 DEBUG     (MainThread) _retrieve_labnumbers n=5
SampleBrowserModel                      : 2018-05-06 18:13:42,673 DEBUG     (MainThread) load associated analysis groups for ['IR998 (Streck, M)']
SampleBrowserModel                      : 2018-05-06 18:13:43,016 DEBUG     (MainThread) $$$$$$$$$$$$$$$$$$$$$ Dumping browser selection
SampleBrowserModel                      : 2018-05-06 18:13:43,017 DEBUG     (MainThread) retrieving identifiers=65761
pychronmeta                             : 2018-05-06 18:13:43,462 DEBUG     (MainThread) SELECT "AnalysisTbl".id, "AnalysisTbl".timestamp, "AnalysisTbl".uuid, "AnalysisTbl".analysis_type, "AnalysisTbl".aliquot, "AnalysisTbl".increment, "AnalysisTbl"."irradiation_positionID", "AnalysisTbl"."measurementName", "AnalysisTbl"."extractionName", "AnalysisTbl"."postEqName", "AnalysisTbl"."postMeasName", "AnalysisTbl".mass_spectrometer, "AnalysisTbl".extract_device, "AnalysisTbl".extract_value, "AnalysisTbl".extract_units, "AnalysisTbl".cleanup, "AnalysisTbl".duration, "AnalysisTbl".weight, "AnalysisTbl".comment 
FROM "AnalysisTbl" JOIN "IrradiationPositionTbl" ON "IrradiationPositionTbl".id = "AnalysisTbl"."irradiation_positionID" JOIN "AnalysisChangeTbl" ON "AnalysisTbl".id = "AnalysisChangeTbl"."analysisID" 
WHERE lower("IrradiationPositionTbl".identifier) IN ('65761') AND "AnalysisChangeTbl".tag != 'invalid' ORDER BY "AnalysisTbl".timestamp ASC
SampleBrowserModel                      : 2018-05-06 18:13:43,846 DEBUG     (MainThread) retrieved analyses n=23
SampleBrowserModel                      : 2018-05-06 18:13:43,846 DEBUG     (MainThread) make records 23
SampleBrowserModel                      : 2018-05-06 18:13:43,960 DEBUG     (MainThread) make records 0.1131589412689209
SampleBrowserModel                      : 2018-05-06 18:13:43,960 DEBUG     (MainThread) selected samples changed. loading analyses. low=None, high=None, limit=0 n=23
SampleBrowserModel                      : 2018-05-06 18:13:43,961 DEBUG     (MainThread) dump browser
SampleBrowserModel                      : 2018-05-06 18:13:44,012 DEBUG     (MainThread) $$$$$$$$$$$$$$$$$$$$$ Dumping browser selection
libpng warning: iCCP: known incorrect sRGB profile
2018-05-06 18:13:47.873 python[15912:2354143] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
SampleBrowserModel                      : 2018-05-06 18:13:47,874 DEBUG     (MainThread) dump browser
SampleBrowserModel                      : 2018-05-06 18:13:47,927 DEBUG     (MainThread) $$$$$$$$$$$$$$$$$$$$$ Dumping browser selection
DVC                                     : 2018-05-06 18:13:47,971 DEBUG     (MainThread) sync repository IR998. exists=True
DVC                                     : 2018-05-06 18:13:47,971 DEBUG     (MainThread) make new repomanager for /Users/mcintosh/Pychron_dev/data/.dvc/repositories/IR998
Inspection                              : 2018-05-06 18:13:47,974 DEBUG     (MainThread) pull called by sync_repo. parent call=<pychron.dvc.dvc.DVC object at 0x119361e08> repo.pull(use_progress=use_progress)
GitRepoManager                          : 2018-05-06 18:13:47,974 DEBUG     (MainThread) pulling master from origin
GitRepoManager                          : 2018-05-06 18:13:47,976 DEBUG     (MainThread) pulling from url: https://github.com/NMGRLData/IR998.git
git.cmd                                 : 2018-05-06 18:13:47,976 DEBUG     (MainThread) Popen(['git', 'fetch', 'origin'], cwd=/Users/mcintosh/Pychron_dev/data/.dvc/repositories/IR998, universal_newlines=False, shell=None)
GitRepoManager                          : 2018-05-06 18:13:48,386 DEBUG     (MainThread) fetch complete
git.cmd                                 : 2018-05-06 18:13:48,386 DEBUG     (MainThread) Popen(['git', 'merge', 'FETCH_HEAD'], cwd=/Users/mcintosh/Pychron_dev/data/.dvc/repositories/IR998, universal_newlines=False, shell=None)
GitRepoManager                          : 2018-05-06 18:13:48,431 DEBUG     (MainThread) pull complete
DVC                                     : 2018-05-06 18:13:50,026 DEBUG     (MainThread) Make analysis time, total: 2.0558149814605713, n: 23, average: 0.0893832600635031
PipelineEngine                          : 2018-05-06 18:13:50,038 DEBUG     (MainThread) 00: Unknowns<UnknownNode> Runtime: 0.0001
2018-05-06 18:13:55.362 python[15912:2354143] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
PipelineEngine                          : 2018-05-06 18:13:55,375 DEBUG     (MainThread) 01: Grouping<GroupingNode> Runtime: 0.0119
2018-05-06 18:14:00.245 python[15912:2354143] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
not auto configure
PipelineEngine                          : 2018-05-06 18:14:00,257 DEBUG     (MainThread) 02: SubGroup<SubGroupingNode> Runtime: 0.0113
not auto configure
PipelineEngine                          : 2018-05-06 18:14:00,263 DEBUG     (MainThread) 03: Analysis Table<XLSXAnalysisTableNode> Runtime: 0.0059
PipelineEngine                          : 2018-05-06 18:14:00,267 DEBUG     (MainThread) 04: Review<ReviewNode> Runtime: 0.0033
PipelineEngine                          : 2018-05-06 18:14:00,267 DEBUG     (MainThread) pipeline vetoed by Review<ReviewNode>
Pipeline Data Processing                : 2018-05-06 18:14:00,271 DEBUG     (MainThread) false run pipeline run_pipeline
Pipeline Data Processing                : 2018-05-06 18:14:00,359 DEBUG     (MainThread) run pipeline finished
Pipeline Data Processing                : 2018-05-06 18:14:18,114 DEBUG     (MainThread) resume pipeline started
pychronmeta                             : 2018-05-06 18:14:18,114 DEBUG     (MainThread) force create new session 4717944592
PipelineEngine                          : 2018-05-06 18:14:18,115 DEBUG     (MainThread) pipeline run started
PipelineEngine                          : 2018-05-06 18:14:18,115 DEBUG     (MainThread) starting at node Review<ReviewNode> None
root                                    : 2018-05-06 18:14:18,414 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2018-05-06 18:14:18,414 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2018-05-06 18:14:18,414 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
root                                    : 2018-05-06 18:14:18,414 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
root                                    : 2018-05-06 18:14:18,415 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
root                                    : 2018-05-06 18:14:18,415 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 311, in resume
    self._resume_pipeline()
root                                    : 2018-05-06 18:14:18,415 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 486, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
root                                    : 2018-05-06 18:14:18,415 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 468, in _run
    if not getattr(self.engine, func)():
root                                    : 2018-05-06 18:14:18,415 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 642, in resume_pipeline
    return self.run_pipeline(state=self.state)
root                                    : 2018-05-06 18:14:18,415 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 725, in run_pipeline
    if not node.pre_run(state):
root                                    : 2018-05-06 18:14:18,415 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/base.py", line 97, in pre_run
    if self.configure(refresh=False, pre_run=True):
root                                    : 2018-05-06 18:14:18,415 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/base.py", line 117, in configure
    return self._configure(**kw)
root                                    : 2018-05-06 18:14:18,415 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/base.py", line 128, in _configure
    info = obj.edit_traits(kind='livemodal')
root                                    : 2018-05-06 18:14:18,416 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/has_traits.py", line 1871, in edit_traits
    handler, id, scrollable, args )
root                                    : 2018-05-06 18:14:18,416 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
root                                    : 2018-05-06 18:14:18,416 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/ui.py", line 222, in ui
    self.rebuild( self, parent )
root                                    : 2018-05-06 18:14:18,416 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/toolkit.py", line 148, in ui_livemodal
    ui_live.ui_livemodal( ui, parent )
root                                    : 2018-05-06 18:14:18,416 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_live.py", line 44, in ui_livemodal
    _ui_dialog(ui, parent, BaseDialog.MODAL)
root                                    : 2018-05-06 18:14:18,416 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_live.py", line 59, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
root                                    : 2018-05-06 18:14:18,416 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_base.py", line 482, in display_ui
    ui.owner.init(ui, parent, style)
root                                    : 2018-05-06 18:14:18,417 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_live.py", line 177, in init
    self.add_contents(panel(ui), bbox)
root                                    : 2018-05-06 18:14:18,417 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 255, in panel
    panel = _GroupPanel(content[0], ui).control
root                                    : 2018-05-06 18:14:18,417 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 561, in __init__
    _fill_panel(sub, content, self.ui, self._add_page_item)
root                                    : 2018-05-06 18:14:18,417 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 291, in _fill_panel
    gp = _GroupPanel(item, ui, suppress_label=True)
root                                    : 2018-05-06 18:14:18,417 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 590, in __init__
    layout = self._add_groups(content, inner)
root                                    : 2018-05-06 18:14:18,417 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 669, in _add_groups
    panel = _GroupPanel(subgroup, self.ui).control
root                                    : 2018-05-06 18:14:18,417 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 592, in __init__
    layout = self._add_items(content, inner)
root                                    : 2018-05-06 18:14:18,417 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 852, in _add_items
    ui, object, name, item.tooltip, None
root                                    : 2018-05-06 18:14:18,417 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/editor_factory.py", line 145, in simple_editor
    description = description )
root                                    : 2018-05-06 18:14:18,418 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/editor.py", line 133, in __init__
    self.old_value = getattr( self.object, self.name )
root                                    : 2018-05-06 18:14:18,418 CRITICAL  (MainThread) AttributeError: 'XLSXTableWriterOptions' object has no attribute 'summary_sig_figs'
root                                    : 2018-05-06 18:14:18,418 CRITICAL  (MainThread) ============ End Exception ==========
ignore exception



```

**Comment by wcmcintosh** [comment]
Error stopped table making before table options window appeared
