### ISSUE TITLE
Error when testing plateau else weighted mean

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1436]
active branch=None

active analyses=65761-01A,65761-01B,65761-01C,65761-01D,65761-01E,65761-02A,65761-02B,65761-02C,65761-02D,65761-02E,65761-03,65761-04,65761-05,65761-06,65761-07,65761-08,65761-09,65761-10,65761-11,65761-12,65761-13,65761-14,65761-15

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 311, in resume
    self._resume_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 486, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 468, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 642, in resume_pipeline
    return self.run_pipeline(state=self.state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 731, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/persist.py", line 302, in run
    writer.build(groups, options=options)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 89, in build
    self._make_human_unknowns(unknowns)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 375, in _make_human_unknowns
    self._make_sheet(unks, 'Unknowns')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 484, in _make_sheet
    ia = self._make_intermediate_summary(worksheet, cols, items, kind)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 673, in _make_intermediate_summary
    sh.write_rich_string(row, 1, label, fmt2)
UnboundLocalError: local variable 'label' referenced before assignment

```

**Comment by wcmcintosh** [comment]
different error when using subgroup plateau, weighted mean working OK
```
XLSXTableWriter                         : 2018-05-07 08:56:38,582 DEBUG     (MainThread) saving table to /Users/mcintosh/Pychron_dev/data/tables/Untitled-068.xlsx
root                                    : 2018-05-07 08:56:38,652 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2018-05-07 08:56:38,653 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2018-05-07 08:56:38,653 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
root                                    : 2018-05-07 08:56:38,653 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
root                                    : 2018-05-07 08:56:38,653 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
root                                    : 2018-05-07 08:56:38,653 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 311, in resume
    self._resume_pipeline()
root                                    : 2018-05-07 08:56:38,653 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 486, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
root                                    : 2018-05-07 08:56:38,653 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 468, in _run
    if not getattr(self.engine, func)():
root                                    : 2018-05-07 08:56:38,653 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 642, in resume_pipeline
    return self.run_pipeline(state=self.state)
root                                    : 2018-05-07 08:56:38,653 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 731, in run_pipeline
    node.run(state)
root                                    : 2018-05-07 08:56:38,653 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/persist.py", line 302, in run
    writer.build(groups, options=options)
root                                    : 2018-05-07 08:56:38,654 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 89, in build
    self._make_human_unknowns(unknowns)
root                                    : 2018-05-07 08:56:38,654 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 375, in _make_human_unknowns
    self._make_sheet(unks, 'Unknowns')
root                                    : 2018-05-07 08:56:38,654 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 484, in _make_sheet
    ia = self._make_intermediate_summary(worksheet, cols, items, kind)
root                                    : 2018-05-07 08:56:38,654 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 682, in _make_intermediate_summary
    sh.write_number(row, age_idx, 'No plateau')
root                                    : 2018-05-07 08:56:38,654 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/xlsxwriter/worksheet.py", line 65, in cell_wrapper
    return method(self, *args, **kwargs)
root                                    : 2018-05-07 08:56:38,654 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/xlsxwriter/worksheet.py", line 500, in write_number
    if self._isnan(number) or self._isinf(number):
root                                    : 2018-05-07 08:56:38,654 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/xlsxwriter/worksheet.py", line 4675, in _isinf
    return (x - x) != 0
root                                    : 2018-05-07 08:56:38,654 CRITICAL  (MainThread) TypeError: unsupported operand type(s) for -: 'str' and 'str'
root                                    : 2018-05-07 08:56:38,654 CRITICAL  (MainThread) ============ End Exception ==========
```
