### ISSUE TITLE
error triggered trying to add branch for IR998

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1449]
```
Experiment Repositories                 : 2018-05-09 17:17:15,867 INFO      (MainThread) add branch
root                                    : 2018-05-09 17:17:15,869 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2018-05-09 17:17:15,869 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2018-05-09 17:17:15,869 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
root                                    : 2018-05-09 17:17:15,869 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
root                                    : 2018-05-09 17:17:15,869 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
root                                    : 2018-05-09 17:17:15,870 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/tasks/repo_task.py", line 178, in add_branch
    if self._repo.create_branch(commit=commit.hexsha if commit else 'HEAD'):
root                                    : 2018-05-09 17:17:15,870 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/git_archive/repo_manager.py", line 518, in create_branch
    print(repo.branches, type(repo.branches))
root                                    : 2018-05-09 17:17:15,870 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/git/repo/base.py", line 242, in heads
    return Head.list_items(self)
root                                    : 2018-05-09 17:17:15,870 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/git/util.py", line 932, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
root                                    : 2018-05-09 17:17:15,870 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/git/refs/symbolic.py", line 592, in _iter_items
    for sha, rela_path in cls._iter_packed_refs(repo):  # @UnusedVariable
ignore exception
root                                    : 2018-05-09 17:17:15,870 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/git/refs/symbolic.py", line 92, in _iter_packed_refs
    raise TypeError("PackingType of packed-Refs not understood: %r" % line)
root                                    : 2018-05-09 17:17:15,870 CRITICAL  (MainThread) TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'
root                                    : 2018-05-09 17:17:15,871 CRITICAL  (MainThread) ============ End Exception ==========
```

**Comment by wcmcintosh** [comment]
Branching OK. Ready to close.
