### ISSUE TITLE
Error on cloning from experiment repository window

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1465]
active branch=None

active analyses=

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/tasks/repo_task.py", line 174, in clone
    service = self.application.get_service(IGitHost)
AttributeError: 'NoneType' object has no attribute 'get_service'

```

**Comment by wcmcintosh** [comment]
Superceded by #1468, I think.
