### ISSUE TITLE
F*%!!! Tags

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1471]
active branch=None

active analyses=65762-01A,65762-01B,65762-01C,65762-01D,65762-01E,65762-02A,65762-02B,65762-02C,65762-02D,65762-02E,65762-03A,65762-03B,65762-04A,65762-04B,65762-05A,65762-05B,65762-06A,65762-06B,65762-07A,65762-07B,65762-08A,65762-08B,65762-09A,65762-09B,65762-10A,65762-10B,65762-11A,65762-11B,65762-12A,65762-12B,65762-13A,65762-13B,65762-14A,65762-14B,65762-15A,65762-15B

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 262, in set_tag
    fans = [ai for ai in e.analyses if ai.tag != 'invalid']
AttributeError: 'ArArTableEditor' object has no attribute 'analyses'

```

**Comment by wcmcintosh** [comment]
Issue overtaken by subsequent changes in program architecture.  Ready to close.
