### ISSUE TITLE
Error when i tried meanify groups in ideogram grouping node

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1474]
active branch=None

active analyses=65761-01A,65761-01B,65761-01C,65761-01D,65761-01E,65761-02A,65761-02B,65761-02C,65761-02D,65761-02E,65761-03,65761-04,65761-05,65761-06,65761-07,65761-08,65761-09,65761-10,65761-11,65761-12,65761-13,65761-14,65761-15

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 64, in _model_changed
    self.model_changed(True)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 61, in model_changed
    self.refresh(clear=clear)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 45, in dec
    return func(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 46, in refresh
    comp.add(p.make_graph())
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 45, in dec
    return func(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/panels/figure_panel.py", line 92, in make_graph
    center, mi, ma = self._get_init_xlimits()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/panels/ideogram_panel.py", line 77, in _get_init_xlimits
    for i in self.figures]))
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/panels/ideogram_panel.py", line 77, in <listcomp>
    for i in self.figures]))
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/ideogram.py", line 197, in max_x
    for ai in self._unpack_attr(attr, exclude_omit=exclude_omit) if ai is not None])
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/ideogram.py", line 196, in <listcomp>
    return max([nominal_value(ai) + std_dev(ai) * 2
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/arar_figure.py", line 280, in gen
    ans = self.sorted_analyses
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/has_traits.py", line 896, in decorator
    self.__dict__[ name ] = result = function( self )
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/arar_figure.py", line 707, in _get_sorted_analyses
    reverse=self._reverse_sorted_analyses)
TypeError: unorderable types: NoneType() < Variable()

```

**Comment by wcmcintosh** [comment]
Issue overtaken by subsequent changes in program architecture.  Ready to close.
