### ISSUE TITLE
Error trying to connect to DVC database from Lemitar

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1480]
active branch=None

active analyses=

description="Same error when starting Pychron of testing database connection
"

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/mcintosh/Programming/git/pychron/pychron/database/tasks/connection_preferences.py", line 98, in _test_connection_button_fired
    kw = self._get_connection_dict()
  File "/Users/mcintosh/Programming/git/pychron/pychron/database/tasks/connection_preferences.py", line 197, in _get_connection_dict
    return dict(username=obj.username,
AttributeError: 'NoneType' object has no attribute 'username'

```

**Comment by jirhiker** [comment]
you don't have a connection selected

**Comment by wcmcintosh** [comment]
Question:  Was lack of username the problem here?  Did I have something not set up?

**Comment by jirhiker** [comment]
you did not have a connection selected when you hit the test connection button. Armor against this was added
