### ISSUE TITLE
error setting tags from analysis pane

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1484]
active branch=None

active analyses=65773-01A,65773-01B,65773-01C,65773-01D,65773-01E,65773-01F,65773-01G,65773-01H,65773-01I,65773-01J,65773-01K,65773-01L,65773-01M

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 258, in set_tag
    self.dvc.tag_items(tag, items, note)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 1250, in tag_items
    if self.update_tag(it):
TypeError: 'NoneType' object is not callable

```

**Comment by wcmcintosh** [comment]
A-OK, ready to close
