### ISSUE TITLE
Error running subgroup ideogram pipeline

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1485]
All running perfectly until ideogram node, then this error and no output

```
ImportError: No module named 'PySide'
2018-05-21 15:10:16.444 python[53697:7674150] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
apptools.sweet_pickle.versioned_unpickler: 2018-05-21 15:10:16,453 DEBUG     (MainThread) VersionedUnpickler [<apptools.sweet_pickle.versioned_unpickler.VersionedUnpickler object at 0x1c3cac4308>] using Updater [<apptools.sweet_pickle.updater.Updater object at 0x1c3ceb4d58>]
apptools.sweet_pickle.versioned_unpickler: 2018-05-21 15:10:16,453 DEBUG     (MainThread) VersionedUnpickler [<apptools.sweet_pickle.versioned_unpickler.VersionedUnpickler object at 0x1c3cac4308>] using Updater [<apptools.sweet_pickle.updater.Updater object at 0x1c3ceb4d58>]
2018-05-21 15:10:21.228 python[53697:7674150] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Inspection                              : 2018-05-21 15:10:21,241 DEBUG     (MainThread) refresh_panels called by model_changed. parent call=<pychron.pipeline.plot.figure_container.FigureContainer object at 0x1c3afea620> self.model.refresh_panels()
Inspection                              : 2018-05-21 15:10:21,245 DEBUG     (MainThread) refresh called by model_changed. parent call=<pychron.pipeline.plot.figure_container.FigureContainer object at 0x1c3afea620> self.refresh(clear=clear)
Inspection                              : 2018-05-21 15:10:21,247 DEBUG     (MainThread) make_graph called by refresh. parent call=<pychron.pipeline.plot.figure_container.FigureContainer object at 0x1c3afea620> comp.add(p.make_graph())
root                                    : 2018-05-21 15:10:21,254 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2018-05-21 15:10:21,255 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2018-05-21 15:10:21,255 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
root                                    : 2018-05-21 15:10:21,255 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 64, in _model_changed
    self.model_changed(True)
root                                    : 2018-05-21 15:10:21,255 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 61, in model_changed
    self.refresh(clear=clear)
root                                    : 2018-05-21 15:10:21,255 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 45, in dec
    return func(*args, **kw)
root                                    : 2018-05-21 15:10:21,255 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 46, in refresh
    comp.add(p.make_graph())
root                                    : 2018-05-21 15:10:21,255 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 45, in dec
    return func(*args, **kw)
root                                    : 2018-05-21 15:10:21,255 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/panels/figure_panel.py", line 93, in make_graph
    center, mi, ma = self._get_init_xlimits()
root                                    : 2018-05-21 15:10:21,256 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/panels/ideogram_panel.py", line 99, in _get_init_xlimits
    cs = [i.mean_x(attr) for i in self.figures]
root                                    : 2018-05-21 15:10:21,256 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/panels/ideogram_panel.py", line 99, in <listcomp>
    cs = [i.mean_x(attr) for i in self.figures]
root                                    : 2018-05-21 15:10:21,256 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/ideogram.py", line 193, in mean_x
    return nominal_value(self.analysis_group.weighted_age)
root                                    : 2018-05-21 15:10:21,256 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_handlers.py", line 110, in _undefined_get
    name, class_of( object ) ))
root                                    : 2018-05-21 15:10:21,256 CRITICAL  (MainThread) traits.trait_errors.TraitError: The 'analysis_group' trait of an Ideogram instance is a property that has no 'get' or 'set' method


```

**Comment by wcmcintosh** [comment]
Ideogram working ok.
