### ISSUE TITLE
error running spectrum pipeline 

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1487]
error running spectrum pipeline (65773)

```
Inspection                              : 2018-05-21 15:16:36,139 DEBUG     (MainThread) refresh_panels called by model_changed. parent call=<pychron.pipeline.plot.figure_container.FigureContainer object at 0x1c3a91f150> self.model.refresh_panels()
Inspection                              : 2018-05-21 15:16:36,143 DEBUG     (MainThread) refresh called by model_changed. parent call=<pychron.pipeline.plot.figure_container.FigureContainer object at 0x1c3a91f150> self.refresh(clear=clear)
Inspection                              : 2018-05-21 15:16:36,145 DEBUG     (MainThread) make_graph called by refresh. parent call=<pychron.pipeline.plot.figure_container.FigureContainer object at 0x1c3a91f150> comp.add(p.make_graph())
ignore exception
root                                    : 2018-05-21 15:16:36,187 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2018-05-21 15:16:36,187 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2018-05-21 15:16:36,187 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
root                                    : 2018-05-21 15:16:36,187 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 64, in _model_changed
    self.model_changed(True)
root                                    : 2018-05-21 15:16:36,187 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 61, in model_changed
    self.refresh(clear=clear)
root                                    : 2018-05-21 15:16:36,188 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 45, in dec
    return func(*args, **kw)
root                                    : 2018-05-21 15:16:36,188 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 46, in refresh
    comp.add(p.make_graph())
root                                    : 2018-05-21 15:16:36,188 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 45, in dec
    return func(*args, **kw)
root                                    : 2018-05-21 15:16:36,188 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/panels/figure_panel.py", line 123, in make_graph
    fig.plot(plots, legend)
root                                    : 2018-05-21 15:16:36,188 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/spectrum.py", line 51, in plot
    ag = self.analysis_group
root                                    : 2018-05-21 15:16:36,188 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_handlers.py", line 110, in _undefined_get
    name, class_of( object ) ))
root                                    : 2018-05-21 15:16:36,188 CRITICAL  (MainThread) traits.trait_errors.TraitError: The 'analysis_group' trait of a Spectrum instance is a property that has no 'get' or 'set' method
root                                    : 2018-05-21 15:16:36,188 CRITICAL  (MainThread) ============ End Exception ==========

```

**Comment by wcmcintosh** [comment]
[1.pdf](https://github.com/NMGRL/pychron/files/2024351/1.pdf)

**Comment by wcmcintosh** [comment]
Still getting no steps showing on spectrum  for 65761-01A to E.  Am now getting valid integrated age.  No errors.  Do I have some setting wrong?

Spectrum question.  Can standard spectrum plot do "plateau else mean" like the table subgrouping does?



[2.pdf](https://github.com/NMGRL/pychron/files/2024384/2.pdf)
