### ISSUE TITLE
Error on selecting Entry : Sensitivity

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1488]
active branch=None

active analyses=66194-01

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 163, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/Programming/git/pychron/pychron/entry/tasks/actions.py", line 55, in perform
    app.get_task(pid)
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/tasks/base_tasks_application.py", line 114, in get_task
    win = self.create_window(w)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/envisage/ui/tasks/tasks_application.py", line 228, in create_window
    window.set_window_layout(layout)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/task_window.py", line 333, in set_window_layout
    self.activate_task(state.task)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/task_window.py", line 156, in activate_task
    task.activated()
  File "/Users/mcintosh/Programming/git/pychron/pychron/entry/tasks/sensitivity/task.py", line 42, in activated
    self.manager.activate()
  File "/Users/mcintosh/Programming/git/pychron/pychron/entry/entry_views/sensitivity_entry.py", line 138, in activate
    self._load_records()
  File "/Users/mcintosh/Programming/git/pychron/pychron/entry/entry_views/sensitivity_entry.py", line 144, in _load_records
    self.records = [SensitivityRecord.from_dict(sens) for spec in specs.values() for sens in spec]
  File "/Users/mcintosh/Programming/git/pychron/pychron/entry/entry_views/sensitivity_entry.py", line 144, in <listcomp>
    self.records = [SensitivityRecord.from_dict(sens) for spec in specs.values() for sens in spec]
  File "/Users/mcintosh/Programming/git/pychron/pychron/entry/entry_views/sensitivity_entry.py", line 57, in from_dict
    record.create_date = datetime.strptime(d.get(attr), DATE_FORMAT)
TypeError: strptime() argument 1 must be str, not datetime.datetime

```

**Comment by wcmcintosh** [comment]
Also, correct sensitivity now displayed on recall.
