### ISSUE TITLE
Error in final node of SubGroup ideogram pipeline

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1491]
active branch=None

active analyses=65761-01A,65761-01B,65761-01C,65761-01D,65761-01E,65761-02A,65761-02B,65761-02C,65761-02D,65761-02E,65761-03,65761-04,65761-05,65761-06,65761-07,65761-08,65761-09,65761-10,65761-11,65761-12,65761-13,65761-14,65761-15

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 64, in _model_changed
    self.model_changed(True)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 61, in model_changed
    self.refresh(clear=clear)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 45, in dec
    return func(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 46, in refresh
    comp.add(p.make_graph())
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 45, in dec
    return func(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/panels/figure_panel.py", line 123, in make_graph
    fig.plot(plots, legend)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/ideogram.py", line 163, in plot
    args = getattr(self, '_plot_{}'.format(po.plot_name))(po, plotobj, pid)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/ideogram.py", line 369, in _plot_relative_probability
    graph.set_series_label('Current-{}'.format(gid), series=sgid, plotid=pid)
  File "/Users/mcintosh/Programming/git/pychron/pychron/graph/graph.py", line 602, in set_series_label
    plots = self.plots[plotid].plots[series]
KeyError: 'plot0'

```

**Comment by wcmcintosh** [comment]
Teste4d.  Sub-grouping running without error, but plotting all analyses of subgroup rather than mean.  We discussed this yesterday and I expect that it is in the queue.

**Comment by wcmcintosh** [comment]
Subgroup ideogram working well, no errors plotting correctly.

**Comment by wcmcintosh** [comment]
Whoops.  Spoke too quickly. Ideogram for 65761 attached. Data from first two step-heats (01 and 02) plotted fine as means, but following fusion analyses also plotted as mean rather than individual analyses.  Subgrouping in table pipeline handles data correctly. Attached pdfs show ideogram and datasets.
[8.pdf](https://github.com/NMGRL/pychron/files/2036019/8.pdf)
[Uploading 7.pdf…]()

**Comment by wcmcintosh** [comment]
Subgrouping demon returned.  Were yesterday's 5:00 PM changes not fully committed?
[12.pdf](https://github.com/NMGRL/pychron/files/2040152/12.pdf)

**Comment by wcmcintosh** [comment]
ID>1,A=1  all grouped together
[14.pdf](https://github.com/NMGRL/pychron/files/2040174/14.pdf)

**Comment by wcmcintosh** [comment]
Sorting now A-OK.

**Comment by wcmcintosh** [comment]
Subgroup ideogram working well now. Subgroup points labelled with correct number, but missing "pl"for plateau.  Were the changes from yesterday committed?
