### ISSUE TITLE
Request for J position uncertainty (sometime in the future)

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1493]
As we discussed previously, it would be great to look sometime at expected J uncertainty related to irradiation geometry.
This would require modeling the 3-D J field, and examining expected variation across sample holes

One could argue that the effort would yield the same result as our much-talked-about fixed-geometry irradiation experiment, although the fixed-geometry experiment would provide ground truth to the model

**Comment by wcmcintosh** [comment]
received the following error in fit flux node, testing position error


```
PipelineEngine                          : 2018-05-25 10:42:01,851 DEBUG     (MainThread) 00: Find Flux Monitors<FindFluxMonitorsNode> Runtime: 29.4769
PipelineEngine                          : 2018-05-25 10:42:01,862 DEBUG     (MainThread) 01: Flux Monitors<FluxMonitorsNode> Runtime: 0.0100
apptools.sweet_pickle.versioned_unpickler: 2018-05-25 10:42:01,866 DEBUG     (MainThread) VersionedUnpickler [<apptools.sweet_pickle.versioned_unpickler.VersionedUnpickler object at 0x1118ab888>] using Updater [<apptools.sweet_pickle.updater.Updater object at 0x12d3a7570>]
ignore exception
root                                    : 2018-05-25 10:42:12,590 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2018-05-25 10:42:12,590 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2018-05-25 10:42:12,591 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
root                                    : 2018-05-25 10:42:12,591 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 614, in dispatch
    handler( *args )
root                                    : 2018-05-25 10:42:12,591 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/editor.py", line 366, in _update_editor
    self.update_editor()
root                                    : 2018-05-25 10:42:12,591 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/instance_editor.py", line 319, in update_editor
    self.resynch_editor()
root                                    : 2018-05-25 10:42:12,591 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/instance_editor.py", line 380, in resynch_editor
    self.factory.id )
root                                    : 2018-05-25 10:42:12,591 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
root                                    : 2018-05-25 10:42:12,591 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/ui.py", line 222, in ui
    self.rebuild( self, parent )
root                                    : 2018-05-25 10:42:12,592 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/toolkit.py", line 141, in ui_subpanel
    ui_panel.ui_subpanel( ui, parent )
root                                    : 2018-05-25 10:42:12,592 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 76, in ui_subpanel
    _ui_panel_for(ui, parent, True)
root                                    : 2018-05-25 10:42:12,592 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 82, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
root                                    : 2018-05-25 10:42:12,592 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/launchers/helpers.py", line 138, in __init__
    self.control = panel(ui)
root                                    : 2018-05-25 10:42:12,592 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 255, in panel
    panel = _GroupPanel(content[0], ui).control
root                                    : 2018-05-25 10:42:12,592 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 590, in __init__
    layout = self._add_groups(content, inner)
root                                    : 2018-05-25 10:42:12,592 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 669, in _add_groups
    panel = _GroupPanel(subgroup, self.ui).control
root                                    : 2018-05-25 10:42:12,593 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 590, in __init__
    layout = self._add_groups(content, inner)
root                                    : 2018-05-25 10:42:12,593 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 669, in _add_groups
    panel = _GroupPanel(subgroup, self.ui).control
root                                    : 2018-05-25 10:42:12,593 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 592, in __init__
    layout = self._add_items(content, inner)
root                                    : 2018-05-25 10:42:12,593 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 852, in _add_items
    ui, object, name, item.tooltip, None
root                                    : 2018-05-25 10:42:12,593 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/editor_factory.py", line 155, in custom_editor
    description = description )
root                                    : 2018-05-25 10:42:12,593 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/editor.py", line 133, in __init__
    self.old_value = getattr( self.object, self.name )
root                                    : 2018-05-25 10:42:12,593 CRITICAL  (MainThread) AttributeError: 'FluxOptions' object has no attribute 'layout'
root                                    : 2018-05-25 10:42:12,594 CRITICAL  (MainThread) ============ End Exception ==========

```

**Comment by wcmcintosh** [comment]
Trying testing of position error function in flux pipeline.  Entered 1.0 as position error and pipeline ran without error, but I'm not sure where to find output relative to position error.

**Comment by jirhiker** [comment]
currently you have to manually compare results between different values of "position error"

**Comment by wcmcintosh** [comment]
Flux pipeline runs without error, but changing position uncertainty from 0.0 through 10.0 did not change J -error.  Monte Carlo must be seeded, because J-error is repeatable to six sig figs.

**Comment by wcmcintosh** [comment]
You are right, not seeded. 
[J-test.xlsx](https://github.com/NMGRL/pychron/files/2041995/J-test.xlsx)
Did some test files. Predicted J-error is varying with trials, as expected (previously was looking at mean J, not predicted J).  However, position error of 0.04 and 0.4 not having noticeable effect.
Can you modify the routine to keep J variation with position separate from other errors and examine SD as pos error varies?  This effect should be significantly larger (0.1%  or more) than current predicted J errors (0.01% ish).
