### ISSUE TITLE
Non-showstopper error during run from Excel Analysis Table

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1496]
active branch=None

active analyses=65761-01A,65761-01B,65761-01C,65761-01D,65761-01E,65761-02A,65761-02B,65761-02C,65761-02D,65761-02E,65762-01A,65762-01B,65762-01C,65762-01D,65762-01E,65762-02A,65762-02B,65762-02C,65762-02D,65762-02E,65763-01A,65763-01B,65763-01C,65763-01D,65763-01E,65763-02A,65763-02B,65763-02C,65763-02D,65763-02E,65761-03,65761-04,65761-05,65761-06,65761-07,65761-08,65761-09,65761-10,65761-11,65761-12,65761-13,65761-14,65761-15,65762-03A,65762-03B,65762-04A,65762-04B,65762-05A,65762-05B,65762-06A,65762-06B,65762-07A,65762-07B,65762-08A,65762-08B,65762-09A,65762-09B,65762-10A,65762-10B,65762-11A,65762-11B,65762-12A,65762-12B,65762-13A,65762-13B,65762-14A,65762-14B,65762-15A,65762-15B,65763-03,65763-04,65763-05,65763-06,65763-07,65763-08,65763-09,65763-10,65763-11,65763-12,65763-13,65763-14,65763-15,65767-01A,65767-01B,65767-02,65767-03,65767-04A,65767-04B,65767-05A,65767-05B,65767-06A,65767-06B,65767-07A,65767-07B,65767-08A,65767-08B,65767-09A,65767-09B,65767-10,65767-11,65767-12,65767-13,65767-14,65767-15,65767-16,65767-17,65773-01A,65773-01B,65773-01C,65773-01D,65773-01E,65773-01F,65773-01G,65773-01H,65773-01I,65773-01J,65773-01K,65773-01L,65773-01M

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 320, in run_from
    self._run_from_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 489, in _run_from_pipeline
    self._run('run from', 'run_from_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 474, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 651, in run_from_pipeline
    ret = self.run_pipeline(run_from=node, state=self.state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 747, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/persist.py", line 256, in run
    writer.build(state.groups, options=self.options)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 78, in build
    self._make_human_unknowns(unknowns)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 380, in _make_human_unknowns
    self._make_sheet(unks, 'Unknowns')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 463, in _make_sheet
    cols = self._get_columns(name, groups)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 122, in _get_columns
    detectors = self._get_detectors(grps)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 115, in _get_detectors
    detectors = {i.detector for g in grps
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 117, in <setcomp>
    for i in a.isotopes.values()}
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 382, in __getattr__
    return getattr(self.analysis_group, item)
AttributeError: 'InterpretedAgeGroup' object has no attribute 'isotopes'

```

**Comment by jirhiker** [comment]
I do not understand how these errors keep happening. What are you trying to do? What analyses, what groups, what subgroups, what options are you using?

**Comment by wcmcintosh** [comment]
Making a table from IR998, grouped by ID, subgrouped by Aliquot, plateau else mean
error occurs  if "run from" excel node regardless of whether configuration is changed unchanged
reproducible error

**Comment by wcmcintosh** [comment]
You are correct. I don't see the error for recently collected data.

**Comment by wcmcintosh** [comment]
With the old data, the table pipeline runs fine if started from the beginning.
Close issue?
