### ISSUE TITLE
Bug in Excel node

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1509]
active branch=None

active analyses=65761-01A,65761-01B,65761-01C,65761-01D,65761-01E,65761-02A,65761-02B,65761-02C,65761-02D,65761-02E,65761-03,65761-04,65761-05,65761-06,65761-07,65761-08,65761-09,65761-10,65761-11,65761-12,65761-13,65761-14,65761-15

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 314, in resume
    self._resume_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 489, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 471, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 655, in resume_pipeline
    return self.run_pipeline(state=self.state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 722, in run_pipeline
    pipeline.resume(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 97, in resume
    prev_node.resume(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/group_age.py", line 45, in resume
    ias = make_interpreted_age_subgroups(ans)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/subgrouping.py", line 103, in make_interpreted_age_subgroups
    for attr in SUBGROUPING_ATTRS:
NameError: name 'SUBGROUPING_ATTRS' is not defined

```

**Comment by wcmcintosh** [comment]
A different bug, running Hanneman 1074
```
islaasta True
root                                    : 2018-05-26 12:53:21,812 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2018-05-26 12:53:21,813 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2018-05-26 12:53:21,813 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
root                                    : 2018-05-26 12:53:21,813 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
root                                    : 2018-05-26 12:53:21,813 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
root                                    : 2018-05-26 12:53:21,813 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 314, in resume
    self._resume_pipeline()
root                                    : 2018-05-26 12:53:21,813 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 489, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
root                                    : 2018-05-26 12:53:21,813 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 471, in _run
    if not getattr(self.engine, func)():
root                                    : 2018-05-26 12:53:21,814 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 655, in resume_pipeline
    return self.run_pipeline(state=self.state)
root                                    : 2018-05-26 12:53:21,814 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 747, in run_pipeline
    node.run(state)
root                                    : 2018-05-26 12:53:21,814 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/persist.py", line 256, in run
    writer.build(state.groups, options=self.options)
root                                    : 2018-05-26 12:53:21,814 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 77, in build
    self._make_human_unknowns(unknowns)
root                                    : 2018-05-26 12:53:21,814 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 387, in _make_human_unknowns
    self._make_sheet(unks, 'Unknowns')
root                                    : 2018-05-26 12:53:21,814 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 526, in _make_sheet
    ag.preferred_age_kind = 'weighted_mean'
root                                    : 2018-05-26 12:53:21,814 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_handlers.py", line 173, in error
    value )
root                                    : 2018-05-26 12:53:21,814 CRITICAL  (MainThread) traits.trait_errors.TraitError: The 'preferred_age_kind' trait of an InterpretedAgeGroup instance must be 'Weighted Mean' or 'Integrated' or 'Arithmetic Mean' or 'Plateau' or 'Plateau else Weighted Mean' or 'Isochron', but a value of 'weighted_mean' <class 'str'> was specified.
root                                    : 2018-05-26 12:53:21,814 CRITICAL  (MainThread) ============ End Exception ==========

```

**Comment by wcmcintosh** [comment]
Bug fixed. Ready to close.
