### ISSUE TITLE
Error in final node of Subgroup Ideogram

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1514]
active branch=None

active analyses=65761-01A,65761-01B,65761-01C,65761-01D,65761-01E,65761-02A,65761-02B,65761-02C,65761-02D,65761-02E,65761-03,65761-04,65761-05,65761-06,65761-07,65761-08,65761-09,65761-10,65761-11,65761-12,65761-13,65761-14,65761-15

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 64, in _model_changed
    self.model_changed(True)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 61, in model_changed
    self.refresh(clear=clear)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 45, in dec
    return func(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/figure_container.py", line 46, in refresh
    comp.add(p.make_graph())
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 45, in dec
    return func(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/panels/figure_panel.py", line 123, in make_graph
    fig.plot(plots, legend)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/ideogram.py", line 163, in plot
    args = getattr(self, '_plot_{}'.format(po.plot_name))(po, plotobj, pid)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/arar_figure.py", line 413, in _plot_radiogenic_yield
    return self._plot_aux('%<sup>40</sup>Ar*', k, po, pid)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/ideogram.py", line 221, in _plot_aux
    ys, es = self._get_aux_plot_data(vk)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/arar_figure.py", line 440, in _get_aux_plot_data
    vs = list(self._unpack_attr(k))
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/arar_figure.py", line 285, in gen
    v = ai.get_value(attr)
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 775, in get_value
    if hasattr(self, attr):
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 759, in rad40_percent
    return self.preferred_rad40_percent
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 882, in _get_preferred_rad40_percent
    return self._get_preferred_('rad40_percent')
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 892, in _get_preferred_
    pa = getattr(self, 'integrated_{}'.format(attr))
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/has_traits.py", line 896, in decorator
    self.__dict__[ name ] = result = function( self )
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 322, in _get_integrated_rad40_percent
    return ufloat(*self._calculate_integrated('rad40_percent'))
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 392, in _calculate_integrated
    prs = ans[0].production_ratios
TypeError: 'generator' object is not subscriptable

```

**Comment by wcmcintosh** [comment]
Fixed. Ready to close.
