### ISSUE TITLE
Error changing error method option IA window

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1517]
active branch=None

active analyses=65761-06,65761-07

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/has_traits.py", line 966, in wrapper0
    return function(arg)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/has_traits.py", line 3372, in notify
    self.trait_property_changed( name, old )
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/has_traits.py", line 896, in decorator
    self.__dict__[ name ] = result = function( self )
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 334, in _get_integrated_moles_k39
    return ufloat(*self._calculate_integrated('k39'))
TypeError: ufloat() argument after * must be an iterable, not AffineScalarFunc

```

**Comment by wcmcintosh** [comment]
SE=0.002
MSE = 0.032




[3.pdf](https://github.com/NMGRL/pychron/files/2046398/3.pdf)

**Comment by wcmcintosh** [comment]
IA config window working well - no errors

**Comment by wcmcintosh** [comment]
Ready to close
