### ISSUE TITLE
table subgrouping not liking plateau else mean

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1521]
```
Pipeline Data Processing                : 2018-05-29 11:50:50,408 DEBUG     (MainThread) resume pipeline started
pychronmeta                             : 2018-05-29 11:50:50,409 DEBUG     (MainThread) force create new session 4877828256
root                                    : 2018-05-29 11:50:50,449 CRITICAL  (MainThread) ============ Exception ==============
ignore exception
root                                    : 2018-05-29 11:50:50,449 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2018-05-29 11:50:50,449 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
root                                    : 2018-05-29 11:50:50,449 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
root                                    : 2018-05-29 11:50:50,450 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
root                                    : 2018-05-29 11:50:50,450 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 314, in resume
    self._resume_pipeline()
root                                    : 2018-05-29 11:50:50,450 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 498, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
root                                    : 2018-05-29 11:50:50,450 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 480, in _run
    if not getattr(self.engine, func)():
root                                    : 2018-05-29 11:50:50,450 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 656, in resume_pipeline
    return self.run_pipeline(state=self.state)
root                                    : 2018-05-29 11:50:50,450 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 723, in run_pipeline
    pipeline.resume(state)
root                                    : 2018-05-29 11:50:50,450 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 98, in resume
    prev_node.resume(state)
root                                    : 2018-05-29 11:50:50,451 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/group_age.py", line 45, in resume
    ias = make_interpreted_age_subgroups(ans)
root                                    : 2018-05-29 11:50:50,451 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/subgrouping.py", line 111, in make_interpreted_age_subgroups
    ag.set_preferred_kind(attr, k, ek)
root                                    : 2018-05-29 11:50:50,451 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 766, in set_preferred_kind
    pv.kind = k
root                                    : 2018-05-29 11:50:50,451 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_handlers.py", line 173, in error
    value )
root                                    : 2018-05-29 11:50:50,451 CRITICAL  (MainThread) traits.trait_errors.TraitError: The 'kind' trait of a PreferredValue instance must be 'Weighted Mean' or 'Integrated' or 'Arithmetic Mean', but a value of 'Plateau else Weighted Mean' <class 'str'> was specified.
root                                    : 2018-05-29 11:50:50,451 CRITICAL  (MainThread) ============ End Exception ==========

```

**Comment by wcmcintosh** [comment]
Fixed. Ready to close.
