### ISSUE TITLE
mean value issues

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1523]
exception saving spectrum plateau age to IA
```
Inspection                              : 2018-05-29 15:05:21,612 DEBUG     (MainThread) analyses called by get_interpreted_ages. parent call=<pychron.pipeline.plot.editors.spectrum_editor.SpectrumEditor object at 0x1c3402f468> ias = [func(list(ans)) for gid, ans in groupby(sorted(self.analyses, key=key), key=key)]
root                                    : 2018-05-29 15:05:21,637 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2018-05-29 15:05:21,637 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2018-05-29 15:05:21,637 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
root                                    : 2018-05-29 15:05:21,637 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
root                                    : 2018-05-29 15:05:21,637 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
root                                    : 2018-05-29 15:05:21,637 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 320, in set_interpreted_age
    ias = self.active_editor.get_interpreted_ages()
root                                    : 2018-05-29 15:05:21,637 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/editors/interpreted_age_editor.py", line 59, in get_interpreted_ages
    ias = [func(list(ans)) for gid, ans in groupby(sorted(self.analyses, key=key), key=key)]
root                                    : 2018-05-29 15:05:21,637 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/editors/interpreted_age_editor.py", line 59, in <listcomp>
    ias = [func(list(ans)) for gid, ans in groupby(sorted(self.analyses, key=key), key=key)]
root                                    : 2018-05-29 15:05:21,638 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/editors/interpreted_age_editor.py", line 55, in func
    p.set_preferred_age(pk, ek)
root                                    : 2018-05-29 15:05:21,638 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 626, in set_preferred_age
    pv.kind = pk
root                                    : 2018-05-29 15:05:21,638 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_handlers.py", line 173, in error
    value )
root                                    : 2018-05-29 15:05:21,638 CRITICAL  (MainThread) traits.trait_errors.TraitError: The 'kind' trait of an AgePreferredValue instance must be 'Weighted Mean' or 'Integrated' or 'Arithmetic Mean' or 'Plateau' or 'Plateau else Weighted Mean' or 'Isochron', but a value of '' <class 'str'> was specified.
root                                    : 2018-05-29 15:05:21,638 CRITICAL  (MainThread) ============ End Exception ==========
```

**Comment by wcmcintosh** [comment]
39Ar in fA - thanks. Integrated 39Ar working fine, but weighted and arithmetic mean giving nan ± 0 and 0 ± 0 respectively.
For all means, if arithmetic mean is selected, error type selection does not change mean. Does arithmetic mean default to only SD?  I'll close #xxx

**Comment by wcmcintosh** [comment]
Means seem to all be operating perfectly.
