### ISSUE TITLE
Error fitting iso evolution Felix data 66049-01A

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1546]
active branch=None

active analyses=66049-01A

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 311, in run
    self._run_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 501, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 480, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 751, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/fit.py", line 342, in run
    fs = progress_loader(unks, self._assemble_result, threshold=1, step=10)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 101, in progress_loader
    items = list(gen())
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 86, in gen
    for ri in r:
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/fit.py", line 440, in _assemble_result
    rsquared=rsquared,
UnboundLocalError: local variable 'rsquared' referenced before assignment

```

**Comment by wcmcintosh** [comment]
Tried Iso Ev on  Jan data 65671, reentrant error


```
Pipeline Data Processing                : 2018-06-02 16:39:13,856 DEBUG     (MainThread) run pipeline started
pychronmeta                             : 2018-06-02 16:39:13,857 DEBUG     (MainThread) force create new session 4894122496
PipelineEngine                          : 2018-06-02 16:39:13,857 DEBUG     (MainThread) pipeline run started
SampleBrowserModel                      : 2018-06-02 16:39:13,857 DEBUG     (MainThread) reattach
SampleBrowserModel                      : 2018-06-02 16:39:14,283 DEBUG     (MainThread) load associated analysis groups for ['IR998 (Streck, M)']
libpng warning: iCCP: known incorrect sRGB profile
2018-06-02 16:39:18.920 python[14774:2414353] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
SampleBrowserModel                      : 2018-06-02 16:39:18,921 DEBUG     (MainThread) dump browser
SampleBrowserModel                      : 2018-06-02 16:39:18,924 DEBUG     (MainThread) $$$$$$$$$$$$$$$$$$$$$ Dumping browser selection
DVC                                     : 2018-06-02 16:39:18,929 DEBUG     (MainThread) sync repository IR998. exists=True
Inspection                              : 2018-06-02 16:39:18,931 DEBUG     (MainThread) pull called by sync_repo. parent call=<pychron.dvc.dvc.DVC object at 0x123b66048> repo.pull(use_progress=use_progress)
GitRepoManager                          : 2018-06-02 16:39:18,931 DEBUG     (MainThread) pulling master from origin
GitRepoManager                          : 2018-06-02 16:39:18,933 DEBUG     (MainThread) pulling from url: https://github.com/NMGRLData/IR998.git
git.cmd                                 : 2018-06-02 16:39:18,933 DEBUG     (MainThread) Popen(['git', 'fetch', 'origin'], cwd=/Users/mcintosh/Pychron_dev/data/.dvc/repositories/IR998, universal_newlines=False, shell=None)
GitRepoManager                          : 2018-06-02 16:39:19,432 DEBUG     (MainThread) fetch complete
git.cmd                                 : 2018-06-02 16:39:19,433 DEBUG     (MainThread) Popen(['git', 'merge', 'FETCH_HEAD'], cwd=/Users/mcintosh/Pychron_dev/data/.dvc/repositories/IR998, universal_newlines=False, shell=None)
GitRepoManager                          : 2018-06-02 16:39:19,491 DEBUG     (MainThread) pull complete
DVC                                     : 2018-06-02 16:39:20,222 DEBUG     (MainThread) Make analysis time, total: 1.2928988933563232, n: 1, average: 1.2928988933563232
PipelineEngine                          : 2018-06-02 16:39:20,225 DEBUG     (MainThread) 00: Unknowns<UnknownNode> Runtime: 0.0032
2018-06-02 16:39:23.413 python[14774:2414353] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
not auto configure
PipelineEngine                          : 2018-06-02 16:39:23,421 DEBUG     (MainThread) 01: Fit IsoEvo<FitIsotopeEvolutionNode> Runtime: 0.0076
PipelineEngine                          : 2018-06-02 16:39:23,426 DEBUG     (MainThread) 02: Review<ReviewNode> Runtime: 0.0040
PipelineEngine                          : 2018-06-02 16:39:23,426 DEBUG     (MainThread) pipeline vetoed by Review<ReviewNode>
Pipeline Data Processing                : 2018-06-02 16:39:23,436 DEBUG     (MainThread) false run pipeline run_pipeline
Pipeline Data Processing                : 2018-06-02 16:39:23,437 DEBUG     (MainThread) run pipeline finished
```

**Comment by wcmcintosh** [comment]
Have not seen this error for a while now.  All fixed I think.  Ready to close.
