### ISSUE TITLE
Error in flux monitor node, flux pipeline

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1552]
active branch=None

active analyses=25328-01,25328-02,25328-03,25328-04,25328-05,25328-06,25329-01,25329-02,25329-03,25329-04,25329-05,25329-06,25330-01,25330-02,25330-03,25330-04,25330-05,25330-06,25331-01,25331-02,25331-03,25331-04,25331-05,25331-06,25332-01,25332-02,25332-03,25332-04,25332-05,25332-06,25333-01,25333-02,25333-03,25333-04,25333-05,25333-06,25333-07,25333-08,25333-09,25333-10,25333-11,25333-12,25334-01,25334-02,25334-03,25334-04,25334-05,25334-06,25335-01,25335-02,25335-03,25335-04,25335-05,25335-06

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 314, in run
    self._run_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 504, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 483, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 757, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/fit.py", line 486, in run
    editor.predict_values()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/editors/flux_results_editor.py", line 370, in predict_values
    self._graph_hole_vs_j(x, y, r, reg, refresh)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/editors/flux_results_editor.py", line 453, in _graph_hole_vs_j
    l, u = reg.calculate_error_envelope(fxs, rmodel=fys)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/base_regressor.py", line 240, in calculate_error_envelope
    es = self.predict_error(rx, error_calc=error_calc)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 178, in predict_error
    e = self.predict_error_matrix(x, error_calc)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 244, in predict_error_matrix
    return [func(xi) for xi in x]
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 244, in <listcomp>
    return [func(xi) for xi in x]
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 233, in func
    varY_hat = calc_hat(xi)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 218, in calc_hat
    Xk = self._get_X(xi).T
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/regression/ols_regressor.py", line 387, in _get_X
    x1, x2 = xs.T
TypeError: iteration over a 0-d array

```

**Comment by wcmcintosh** [comment]
Not data specific, same error for NM-281A, recently ran fine

**Comment by wcmcintosh** [comment]
Flux fitting working fine.  Ready to close.
