### ISSUE TITLE
Error in Excel node of table making

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1556]
active branch=None

active analyses=65185-01,65185-03,65185-06,65185-07,65185-08,65185-09,65185-10,65185-11,65185-12,65185-13,65185-14,65185-15,65185-16,65186-20,65186-21,65186-22,65186-23,65186-25,65186-26,65186-27,65186-29,65186-36,65187-11,65187-16,65187-20,65187-21,65187-22,65187-25,65187-28,65187-29,65187-32,65187-33,65187-34,65187-35,65187-37,65187-38,65187-39,65187-40,65188-10,65188-11,65188-12,65188-14,65188-15,65188-16,65188-17,65188-18,65188-19,65188-21,65188-22,65188-23,65188-25,65188-28,65188-29,65188-30,65188-31,65188-33,65188-34,65188-35,65188-36,65188-37,65188-38,65188-39,65250-02,65250-03,65250-04,65250-06,65250-07,65250-08,65250-09,65250-10,65250-11,65250-12,65250-15,65250-16,65250-17,65250-18,65250-19,65250-20,65250-21,65250-22,65250-23,65250-24,65250-25,65251-01,65251-05,65251-07,65251-08,65251-09,65251-10,65251-11,65251-12,65251-13,65251-14,65251-16,65251-17,65251-18,65251-19,65251-20,65251-21,65251-22,65251-23,65251-24,65251-25,65253-01,65253-03,65253-04,65253-05,65253-08,65253-09,65253-11,65254-01,65254-02,65254-03,65254-19,65254-20,65254-21,65254-22,65254-23,65254-24,65254-25,65254-26,65254-28,65254-29,65254-30,65255-01,65255-02,65255-03,65255-04,65255-06,65255-07,65255-08,65255-09,65255-11,65255-13,65255-15,65255-17,65255-18,65255-19,65255-20,65255-21,65255-23,65255-25,65255-26,65255-27,65255-28,65255-29,65255-30,65255-31,65257-10,65257-11,65257-12,65257-13,65257-14,65257-16,65257-17,65257-18,65257-19,65257-21,65257-22,65257-23,65257-24,65257-27,65257-28,65257-29,65257-30,65257-32,65257-34

description="Hanneman 65185-65275"

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 317, in resume
    self._resume_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 501, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 483, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 659, in resume_pipeline
    return self.run_pipeline(state=self.state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 757, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/persist.py", line 256, in run
    writer.build(state.groups, options=self.options)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 76, in build
    unknowns = self._make_human_unknowns(unknowns)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 418, in _make_human_unknowns
    return self._make_sheet(unks, 'Unknowns')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 594, in _make_sheet
    self._make_summary(worksheet, cols, nitems[0])
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 931, in _make_summary
    sh.write_number(self._current_row, k2o_idx, nominal_value(group.total_k2o), nfmt)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/has_traits.py", line 896, in decorator
    self.__dict__[ name ] = result = function( self )
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 457, in _get_total_k2o
    total = sum([a.k2o for a in self.analyses])
TypeError: unsupported operand type(s) for +: 'int' and 'str'

```

**Comment by wcmcintosh** [comment]
No longer seeing this message. Ready to close.
