### ISSUE TITLE
This error occured while saving the air run data.

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1558]
active branch=release/v17.7

active analyses=bu-FD-F-861

```
Traceback (most recent call last):
  File "/Users/obama/.pychron.1/updates/pychron/core/helpers/exception_helper.py", line 283, in run_with_except_hook
    run_old(*args, **kw)
  File "/anaconda2/envs/pychron/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/obama/.pychron.1/updates/pychron/experiment/experiment_executor.py", line 504, in _execute
    self._execute_queue(i, exp)
  File "/Users/obama/.pychron.1/updates/pychron/experiment/experiment_executor.py", line 647, in _execute_queue
    self._join_run(spec, run)
  File "/Users/obama/.pychron.1/updates/pychron/experiment/experiment_executor.py", line 744, in _join_run
    self._do_run(run)
  File "/Users/obama/.pychron.1/updates/pychron/experiment/experiment_executor.py", line 822, in _do_run
    run.save()
  File "/Users/obama/.pychron.1/updates/pychron/experiment/automated_run/automated_run.py", line 1063, in save
    self._persister_save_action('post_measurement_save')
  File "/Users/obama/.pychron.1/updates/pychron/experiment/automated_run/automated_run.py", line 1613, in _persister_save_action
    getattr(self.dvc_persister, func)(*args, **kw)
  File "/Users/obama/.pychron.1/updates/pychron/dvc/dvc_persister.py", line 200, in post_measurement_save
    self._save_analysis(timestamp)
  File "/Users/obama/.pychron.1/updates/pychron/dvc/dvc_persister.py", line 503, in _save_analysis
    p = self._make_path()
  File "/Users/obama/.pychron.1/updates/pychron/dvc/dvc_persister.py", line 580, in _make_path
    return analysis_path(runid, repository_identifier, modifier, extension, mode='w')
  File "/Users/obama/.pychron.1/updates/pychron/dvc/__init__.py", line 98, in analysis_path
    root, tail = subdirize(root, runid, l=l, mode=mode)
  File "/Users/obama/.pychron.1/updates/pychron/core/helpers/filetools.py", line 38, in subdirize
    os.mkdir(path)
OSError: [Errno 2] No such file or directory: '/Users/obama/PychronDev/data/.dvc/repositories/NoRepo/a-02'

```

**Comment by wcmcintosh** [comment]
Ready to close?
