### ISSUE TITLE
Error after selecting point in flux graph

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1576]
active branch=None

active analyses=24751-01,24751-02,24751-03,24751-04,24751-05,24751-06,24751-07,24752-01,24752-02,24752-03,24752-04,24752-05,24752-06,24753-01,24753-02,24753-03,24753-05,24753-06,24754-01,24754-02,24754-03,24754-04,24754-05,24754-06,24755-01,24755-02,24755-03,24755-04,24755-05,24755-06,24756-01,24756-02,24756-03,24756-05,24756-06,24757-01,24757-02,24757-03,24757-04,24757-05,24757-06,24758-01,24758-02,24758-03,24758-04,24758-05,24758-06

description="Error occured immediately after clicking on point, staus changed correctly
NM-281A data
"

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/editors/flux_results_editor.py", line 579, in _update_graph_metadata
    sel = self._filter_metadata_changes(obj, self.analyses, self._recalculate_means)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/arar_figure.py", line 62, in _filter_metadata_changes
    self._set_selected(ans, sel)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/arar_figure.py", line 56, in _set_selected
    a.set_temp_status(a.otemp_status if a.otemp_status else 'omit')
AttributeError: 'list' object has no attribute 'set_temp_status'

```

**Comment by wcmcintosh** [comment]
Tagging from flux graph working well.  Ready to close.
