### ISSUE TITLE
Error after changing tag from analysis list, flux pipeline

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1577]
active branch=None

active analyses=24751-01,24751-02,24751-03,24751-04,24751-05,24751-06,24751-07,24752-01,24752-02,24752-03,24752-04,24752-05,24752-06,24753-01,24753-02,24753-03,24753-05,24753-06,24754-01,24754-02,24754-03,24754-04,24754-05,24754-06,24755-01,24755-02,24755-03,24755-04,24755-05,24755-06,24756-01,24756-02,24756-03,24756-05,24756-06,24757-01,24757-02,24757-03,24757-04,24757-05,24757-06,24758-01,24758-02,24758-03,24758-04,24758-05,24758-06

description="Error occured before status changed in figure"

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 267, in set_tag
    fans = [ai for ai in ans if ai.tag.lower() != 'invalid']
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 267, in <listcomp>
    fans = [ai for ai in ans if ai.tag.lower() != 'invalid']
AttributeError: 'list' object has no attribute 'tag'

```

**Comment by wcmcintosh** [comment]
Tagging from flux graph working well.  Ready to close.
