### ISSUE TITLE
Spectrum pipeline error - infinite loop

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1590]
active branch=None

active analyses=63461-04A,63461-04B,63461-04C,63461-04D

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/enable/qt4/base_window.py", line 202, in paintEvent
    self.handler.paintEvent(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/enable/qt4/base_window.py", line 54, in paintEvent
    self._enable_window._paint(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/enable/abstract_window.py", line 468, in _paint
    self.component.draw(gc, view_bounds=(0, 0, size[0], size[1]))
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/enable/component.py", line 427, in draw
    self._draw(gc, view_bounds, mode)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/enable/component.py", line 776, in _draw
    self._dispatch_draw("overlay", gc, view_bounds, mode)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/enable/container.py", line 272, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/enable/container.py", line 272, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/enable/container.py", line 272, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/enable/component.py", line 799, in _dispatch_draw
    handler(gc, view_bounds, mode)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/enable/component.py", line 877, in _draw_overlay
    overlay.overlay(self, gc, view_bounds, mode)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/overlays/spectrum.py", line 389, in overlay
    points = self._get_line()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/overlays/spectrum.py", line 328, in _get_line
    estart = es[sidx] * self.nsigma
IndexError: index 3 is out of bounds for axis 0 with size 3

```

**Comment by wcmcintosh** [comment]
I expect this is a one off.  I just reported it because it is the first time in a very long time that I have had to restart after an error.

**Comment by jirhiker** [comment]
`index 3 is out of bounds for axis 0 with size 3`

you get this type of error in the following case
```
x = ['a','b','c']
print x[3] # raises index error
```
`x` has a size of 3, but pychron uses zero-based indexing  so the last valid index is 2

```
x=['a','b','c']
print x[2] # this ok. will print 'c'
```

why such are error occurred however is not clear. e.g why is `sidx==3` when `es` has a length of only 3
