### ISSUE TITLE
Key error - what is it

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1593]
I got this error plotting spectra prior to seeing the funky J values.

Prevented plotting of spectrum, requiring restart.  I didn't think much of it, just restarted. 

Error has now reoccurred.  Related to reading J values from irradiation?

```
2018-06-22 16:34:02.460 python[7869:17687766] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
SampleBrowserModel                      : 2018-06-22 16:34:02,461 DEBUG     (MainThread) dump browser
SampleBrowserModel                      : 2018-06-22 16:34:02,464 DEBUG     (MainThread) $$$$$$$$$$$$$$$$$$$$$ Dumping browser selection
DVC                                     : 2018-06-22 16:34:02,469 DEBUG     (MainThread) sync repository Toba. exists=True
Inspection                              : 2018-06-22 16:34:02,471 DEBUG     (MainThread) pull called by sync_repo. parent call=<pychron.dvc.dvc.DVC object at 0x1a357a1c50> repo.pull(use_progress=use_progress)
GitRepoManager                          : 2018-06-22 16:34:02,472 DEBUG     (MainThread) pulling master from origin
GitRepoManager                          : 2018-06-22 16:34:02,473 DEBUG     (MainThread) pulling from url: https://github.com/NMGRLData/Toba.git
git.cmd                                 : 2018-06-22 16:34:02,473 DEBUG     (MainThread) Popen(['git', 'fetch', 'origin'], cwd=/Users/mcintosh/Pychron_dev/data/.dvc/repositories/Toba, universal_newlines=False, shell=None)
GitRepoManager                          : 2018-06-22 16:34:03,484 DEBUG     (MainThread) fetch complete
git.cmd                                 : 2018-06-22 16:34:03,485 DEBUG     (MainThread) Popen(['git', 'merge', 'FETCH_HEAD'], cwd=/Users/mcintosh/Pychron_dev/data/.dvc/repositories/Toba, universal_newlines=False, shell=None)
GitRepoManager                          : 2018-06-22 16:34:03,541 DEBUG     (MainThread) pull complete
ISO                                     : 2018-06-22 16:34:03,991 WARNING   (MainThread)  - Failed loading peakcenter. error='int' object is not iterable
DVC                                     : 2018-06-22 16:34:03,996 DEBUG     (MainThread) make analysis exception
DVC                                     : 2018-06-22 16:34:03,996 DEBUG     (MainThread) Traceback (most recent call last):
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 798, in func
    reload=reload, *args)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 1390, in _make_record
    pname, prod = productions[a.irradiation][a.irradiation_level]
KeyError: 'F'

ISO                                     : 2018-06-22 16:34:04,013 WARNING   (MainThread)  - Failed loading peakcenter. error='int' object is not iterable
DVC                                     : 2018-06-22 16:34:04,017 DEBUG     (MainThread) make analysis exception
DVC                                     : 2018-06-22 16:34:04,017 DEBUG     (MainThread) Traceback (most recent call last):
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 798, in func
    reload=reload, *args)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 1390, in _make_record
    pname, prod = productions[a.irradiation][a.irradiation_level]
KeyError: 'F'

ISO                                     : 2018-06-22 16:34:04,032 WARNING   (MainThread)  - Failed loading peakcenter. error='int' object is not iterable
DVC                                     : 2018-06-22 16:34:04,035 DEBUG     (MainThread) make analysis exception
DVC                                     : 2018-06-22 16:34:04,035 DEBUG     (MainThread) Traceback (most recent call last):
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 798, in func
    reload=reload, *args)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 1390, in _make_record
    pname, prod = productions[a.irradiation][a.irradiation_level]
KeyError: 'F'

ISO                                     : 2018-06-22 16:34:04,195 WARNING   (MainThread)  - Failed loading peakcenter. error='int' object is not iterable
DVC                                     : 2018-06-22 16:34:04,198 DEBUG     (MainThread) make analysis exception
DVC                                     : 2018-06-22 16:34:04,198 DEBUG     (MainThread) Traceback (most recent call last):
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 798, in func
    reload=reload, *args)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 1390, in _make_record
    pname, prod = productions[a.irradiation][a.irradiation_level]
KeyError: 'F'

DVC                                     : 2018-06-22 16:34:04,199 DEBUG     (MainThread) Make analysis time, total: 1.7299609184265137, n: 4, average: 0.4324902296066284
PipelineEngine                          : 2018-06-22 16:34:04,199 DEBUG     (MainThread) Pre run failed Unknowns<UnknownNode>
Pipeline Data Processing                : 2018-06-22 16:34:04,199 DEBUG     (MainThread) true run pipeline run_pipeline
Pipeline Data Processing                : 2018-06-22 16:34:04,199 DEBUG     (MainThread) run pipeline finished


```

**Comment by wcmcintosh** [comment]
Reproducible and data dependent, 63470-04B to D

**Comment by wcmcintosh** [comment]
Not reproduced after restart.  63470-04B to D spectrum plots OK.

**Comment by wcmcintosh** [comment]
I can plot one or two spectra, then get a similar key error for the respective irradiation tray.

**Comment by wcmcintosh** [comment]
Key error problem may well be related to the same sorting/unsorted issue that may be causing J selection error #1596.

**Comment by wcmcintosh** [comment]
Still getting key error when loading many analyses, then selecting subgroup for spectrum pipeline. No error if single run ID loaded.

**Comment by wcmcintosh** [comment]
I have not seen this error for some time.  Fixed?  Ready to close?
