### ISSUE TITLE
tagging error

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1602]
active branch=None

active analyses=65871-33A

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 163, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/editor.py", line 269, in perform
    self.ui.do_undoable( self._perform, action )
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/ui.py", line 716, in do_undoable
    action( *args, **kw )
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/editor.py", line 291, in _perform
    method( info, selection )
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/sample_view.py", line 379, in tag_skip
    self._set_tags(info.object, 'skip')
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/sample_view.py", line 382, in _set_tags
    items = obj.set_tags(tag)
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/sample_browser_model.py", line 198, in set_tags
    self.dvc.tag_items(tagname, items)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 1270, in tag_items
    self.debug('setting {} tag= {}'.format(it.record_id, tag))
AttributeError: 'NoneType' object has no attribute 'record_id'

```

**Comment by wcmcintosh** [comment]
Data dependent.  Three Morgan analyses 65871-33A, 65873-24A, and 65873-25A are flawed in such a way that they cause errors when attempted to be recalled of tagged in any way.  Cannot be tagged as invalid to keep them out of trouble.
