### ISSUE TITLE
Error in blanks pipeline, fit blanlks node

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1610]
active branch=None

active analyses=bu-FC-J-4389,bu-FC-J-4390,bu-FC-J-4391,bu-FC-J-4392,bu-FC-J-4393,bu-FC-J-4394,bu-FC-J-4395,bu-FC-J-4396,bu-FC-J-4397,bu-FC-J-4398,bu-FC-J-4399,bu-FC-J-4400,bu-FC-J-4401,bu-FC-J-4402,bu-FC-J-4403,bu-FC-J-4404,bu-FC-J-4405,bu-FC-J-4406,bu-FC-J-4407,bu-FC-J-4408,bu-FC-J-4409,bu-FC-J-4410,bu-FC-J-4411,bu-FC-J-4412,bu-FC-J-4413,bu-FC-J-4414,bu-FC-J-4415,bu-FC-J-4416,bu-FC-J-4417,bu-FC-J-4418,bu-FC-J-4419,bu-FC-J-4420,bu-FC-J-4421,bu-FC-J-4422,bu-FC-J-4423,bu-FC-J-4424,bu-FC-J-4425,bu-FC-J-4426,bu-FC-J-4427,bu-FC-J-4428,bu-FC-J-4429,bu-FC-J-4430,bu-FC-J-4431,bu-FC-J-4432,bu-FC-J-4433,bu-FC-J-4434,bu-FC-J-4435,bu-FC-J-4436,bu-FC-J-4437,bu-FC-J-4438,bu-FC-J-4439,bu-FC-J-4440,bu-FC-J-4441,bu-FC-J-4442

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 315, in run
    self._run_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 505, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 484, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 757, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/fit.py", line 113, in run
    self.editor.force_update(force=True)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/editors/figure_editor.py", line 74, in force_update
    model.refresh(force=force)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/models/figure_model.py", line 46, in refresh
    p.make_graph()
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 45, in dec
    return func(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/panels/figure_panel.py", line 123, in make_graph
    fig.plot(plots, legend)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/references_series.py", line 256, in plot
    _, mx = self._get_min_max()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/references_series.py", line 315, in _get_min_max
    mi = min(self.sorted_references[0].timestamp, self.sorted_analyses[0].timestamp)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/plot/plotter/references_series.py", line 333, in _get_sorted_references
    reverse=self._reverse_sorted_analyses)
TypeError: unorderable types: NoneType() < NoneType()

```

**Comment by wcmcintosh** [comment]
Seemingly data indépendant. Same error for 276D or 276E data.
