### ISSUE TITLE
Error in find reference node of blanks pipeline

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1611]
active branch=None

active analyses=24365-02,24365-03,24365-04,24365-05,24365-06,bu-FC-J-4438,24366-01,24366-02,24366-03,24366-04,24366-05,24366-06,24367-01,24367-02,24367-03,24367-04,24367-05,24367-06,24368-01,24368-02,24368-03,24368-04,24368-05,24368-06,24369-01,24369-02,24369-03,24369-04,24369-05,24369-06,24370-01,24370-02,24370-03,24370-04,24370-05,24370-06,24371-01,24371-02,24371-03,24371-04,24371-05,24371-06,24372-01,24372-02,24372-03,24372-04,24372-05,24372-06

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 315, in run
    self._run_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 505, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 484, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 757, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/find.py", line 277, in run
    if self._run_group(state, gid, list(ans)):
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/find.py", line 335, in _run_group
    model.setup()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/graphical_filter.py", line 256, in setup
    ans = sorted(ans, key=lambda x: x.timestampf)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/graphical_filter.py", line 256, in <lambda>
    ans = sorted(ans, key=lambda x: x.timestampf)
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/isotope_group.py", line 423, in __getattr__
    raise AttributeError(attr)
AttributeError: timestampf

```

**Comment by wcmcintosh** [comment]
error caused by blank in samples list.
