### ISSUE TITLE
error selecting "use J in individual analyses" selected from subgroup node.

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1614]
active branch=None

active analyses=63630-08A

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/ui/qt/tabular_editor.py", line 483, in data
    return TabularModel.data(self, mi, role)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/qt4/tabular_model.py", line 73, in data
    return adapter.get_text(obj, name, row, column)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/tabular_adapter.py", line 322, in get_text
    return self._result_for( 'get_text', object, trait, row, column )
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/tabular_adapter.py", line 530, in _result_for
    return handler()
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traitsui/tabular_adapter.py", line 581, in <lambda>
    return lambda: getattr( self, name )
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/editors/group_age_editor.py", line 48, in _get_age_error_kind_text
    pv = self.item.get_preferred_obj('age')
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 863, in get_preferred_obj
    _ = self.preferred_age
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 876, in _get_preferred_age
    pa = self.weighted_age
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/has_traits.py", line 896, in decorator
    self.__dict__[ name ] = result = function( self )
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 258, in _get_weighted_age
    return self._apply_j_err(wa)
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 265, in _apply_j_err
    wa = wa + ufloat(0, self.j_err)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/has_traits.py", line 896, in decorator
    self.__dict__[ name ] = result = function( self )
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 167, in _get_j_err
    j = self.j
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/has_traits.py", line 896, in decorator
    self.__dict__[ name ] = result = function( self )
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 176, in _get_j
    j = self.analyses[0].j
IndexError: list index out of range

```

**Comment by wcmcintosh** [comment]
No longer seeing any errors.  Ready to close.
