### ISSUE TITLE
error running analysis table

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1618]
active branch=None

active analyses=65854-01B,65854-01C,65854-01D,65854-02B,65854-02C,65854-02D,65854-02E,65855-05A,65855-05B,65855-05C,65855-05D,65855-05E,65856-01A,65856-01B,65856-01C,65856-01D,65856-01E,65856-02A,65856-02B,65856-02C,65856-02D,65856-02E,65857-01A,65857-01B,65857-01C,65857-01D,65857-02A,65857-02B,65857-02C,65857-02D,65858-01A,65858-01B,65858-01C,65858-01D,65858-02A,65858-02B,65858-02C,65858-02D,65859-01A,65859-01B,65859-01C,65859-01D,65859-02A,65859-02B,65859-02C,65859-02D,65860-01A,65860-01B,65860-01C,65860-01D,65860-02A,65860-02B,65860-02C,65860-02D,65861-01A,65861-01B,65861-01C,65861-01D,65861-02A,65861-02B,65861-02C,65861-02D,65866-01A,65866-01B,65866-01C,65866-01D,65866-02A,65866-02B,65866-02C,65866-02D,65867-01A,65867-01B,65867-01C,65867-01D,65867-02A,65867-02B,65867-02C,65867-02D,65868-01A,65868-01B,65868-01C,65868-01D,65868-02A,65868-02B,65868-02C,65868-02D,65869-01A,65869-01B,65869-01C,65869-01D,65869-02A,65869-02B,65869-02C,65869-02D,65870-01A,65870-01B,65870-01C,65870-01D,65870-02A,65870-02B,65870-02C,65871-01A,65871-01B,65871-01C,65871-01D,65871-02A,65871-02B,65871-02C,65871-02D,65872-01A,65872-01B,65872-01C,65872-01D,65872-02A,65872-02B,65872-02C,65872-02D,65873-01A,65873-01B,65873-01C,65873-01D,65873-02A,65873-02B,65873-02C,65873-02D,65890-01A,65890-01B,65890-01C,65890-02A,65890-02B,65890-02C,65854-03A,65854-03B,65854-04A,65854-04B,65854-05A,65854-05B,65854-06A,65854-06B,65855-07A,65855-07B,65855-08A,65855-08B,65855-09A,65855-09B,65855-10A,65855-10B,65855-11A,65855-11B,65855-12A,65855-12B,65856-03A,65856-03B,65856-04A,65856-04B,65856-05A,65856-05B,65856-06A,65856-06B,65856-07A,65856-07B,65857-03A,65857-03B,65857-04A,65857-04B,65857-05A,65857-05B,65857-06A,65857-06B,65857-07A,65857-07B,65857-08A,65857-08B,65857-09A,65857-09B,65857-10A,65857-10B,65858-03A,65858-03B,65858-04A,65858-04B,65858-05A,65858-05B,65858-06A,65858-06B,65858-07A,65858-07B,65858-08A,65858-09A,65858-09B,65858-10A,65858-10B,65859-03A,65859-03B,65859-04A,65859-04B,65859-05A,65859-05B,65859-06A,65859-06B,65859-07A,65859-07B,65860-03A,65860-03B,65860-04A,65860-04B,65860-05A,65860-05B,65861-06A,65861-06B,65861-04A,65861-04B,65861-05A,65861-05B,65861-06C,65861-06D,65866-03A,65866-03B,65866-04A,65866-04B,65866-05A,65866-05B,65866-06A,65866-06B,65867-03A,65867-03B,65867-04A,65867-04B,65867-05A,65867-05B,65867-06A,65867-06B,65867-07A,65867-07B,65867-08A,65867-08B,65867-09A,65867-09B,65867-10A,65867-10B,65868-03A,65868-03B,65868-04A,65868-04B,65868-05A,65868-05B,65868-06A,65868-06B,65869-03A,65869-03B,65869-04A,65869-04B,65869-05A,65869-05B,65869-06A,65869-06B,65869-07A,65869-07B,65869-08A,65869-08B,65869-09A,65869-09B,65869-10A,65869-10B,65870-03A,65870-03B,65870-04A,65870-04B,65870-05A,65870-05B,65870-06A,65870-06B,65871-01E,65871-01F,65871-02E,65871-02F,65871-03A,65871-03B,65871-04A,65871-04B,65872-01E,65872-01F,65872-02E,65872-02F,65872-03A,65872-03B,65872-04A,65872-04B,65873-02E,65873-02F,65873-03A,65873-03B,65873-04A,65873-04B,65873-05A,65873-05B,65873-06A,65873-06B,65873-07A,65873-07B,65873-08A,65873-08B,65873-09A,65873-09B,65890-03A,65890-03B,65890-04A,65890-04B,65890-05A,65890-05B,65890-06A,65890-06B,65890-07A,65890-07B,65890-08A,65890-08B,65890-09A,65890-09B,65890-10A,65890-10B,65854-07A,65854-07B,65854-08A,65854-08B,65854-09A,65854-09B,65854-10A,65854-10B,65854-11A,65854-11B,65854-12A,65854-12B,65854-13A,65854-13B,65854-14A,65854-14B,65854-15A,65854-15B,65854-16A,65854-16B,65854-17A,65854-17B,65855-13A,65855-13B,65855-14A,65855-14B,65855-15A,65855-15B,65855-16A,65855-17B,65855-18A,65855-18B,65855-19A,65855-19B,65855-20A,65855-21A,65855-21B,65855-22A,65855-22B,65855-23A,65855-23B,65856-08A,65856-08B,65856-09A,65856-09B,65856-10A,65856-10B,65856-11A,65856-11B,65856-12A,65856-12B,65856-13A,65856-13B,65856-14A,65856-14B,65856-15A,65856-15B,65856-16A,65856-16B,65856-17A,65856-17B,65856-18A,65856-18B,65857-11A,65857-11B,65857-12A,65857-13A,65857-13B,65857-14A,65857-14B,65857-15A,65857-15B,65857-16A,65857-16B,65857-17A,65857-18A,65857-18B,65857-19A,65857-19B,65857-20A,65857-20B,65857-21A,65857-21B,65858-11A,65858-11B,65858-12A,65858-12B,65858-13A,65858-13B,65858-14A,65858-14B,65858-15A,65858-15B,65858-16A,65858-16B,65858-17A,65858-17B,65858-18A,65858-18B,65858-19A,65858-19B,65858-20A,65858-20B,65858-21A,65858-21B,65859-08A,65859-08B,65859-09A,65859-09B,65859-10A,65859-10B,65859-11A,65859-11B,65859-12A,65859-12B,65859-13A,65859-13B,65859-14A,65859-14B,65859-15A,65859-15B,65859-16A,65859-16B,65859-17A,65859-17B,65859-18A,65859-18B,65860-06A,65860-06B,65860-07A,65860-07B,65860-08A,65860-08B,65860-09A,65860-09B,65860-10A,65860-10B,65860-11A,65860-11B,65860-12A,65860-12B,65860-13A,65860-13B,65860-14A,65860-14B,65860-15A,65860-15B,65860-16A,65860-16B,65861-07A,65861-07B,65861-08A,65861-08B,65861-09A,65861-09B,65861-10A,65861-10B,65861-11A,65861-11B,65861-12A,65861-12B,65861-13A,65861-13B,65861-14B,65861-15A,65861-15B,65861-16A,65861-16B,65861-17A,65861-17B,65866-07A,65866-08A,65866-08B,65866-09A,65866-09B,65866-10A,65866-10B,65866-11A,65866-11B,65866-12A,65866-12B,65866-13A,65866-13B,65866-14A,65866-14B,65866-15A,65866-15B,65866-16A,65866-16B,65866-17A,65866-17B,65867-11A,65867-11B,65867-12A,65867-12B,65867-13A,65867-13B,65867-14A,65867-15A,65867-15B,65867-16A,65867-16B,65867-17A,65867-17B,65867-18A,65867-18B,65867-19A,65867-19B,65867-20A,65867-20B,65867-21A,65867-21B,65868-07A,65868-07B,65868-08A,65868-08B,65868-09A,65868-09B,65868-10B,65868-11A,65868-11B,65868-12A,65868-12B,65867-14B,65868-12D,65868-13A,65868-13B,65868-14A,65868-14B,65868-15A,65868-15B,65868-16A,65868-16B,65868-17A,65868-17B,65869-11A,65869-11B,65869-12A,65869-12B,65869-13A,65869-13B,65869-14A,65869-15A,65869-15B,65869-16A,65869-16B,65869-17A,65869-17B,65869-18A,65869-18B,65869-19A,65869-19B,65869-20A,65869-20B,65869-21A,65869-21B,65870-28A,65870-29A,65870-29B,65870-30A,65870-30B,65870-31A,65870-31B,65870-32A,65870-32B,65870-33A,65870-33B,65870-34A,65870-34B,65870-35A,65870-35B,65870-36A,65870-36B,65870-37A,65870-37B,65870-07A,65870-07B,65871-27A,65871-27B,65871-28A,65871-28B,65871-29A,65871-29B,65871-30A,65871-30B,65871-31A,65871-31B,65871-32A,65871-32B,65871-33A,65871-33B,65871-34A,65871-34B,65872-05A,65872-05B,65872-06A,65872-06B,65872-07A,65872-07B,65872-08B,65872-09B,65872-10A,65872-11A,65872-11B,65872-12A,65872-12B,65872-13A,65872-13B,65872-14A,65872-14B,65873-10A,65873-10B,65873-11A,65873-11B,65873-12A,65873-12B,65873-13A,65873-13B,65873-14A,65873-14B,65873-15A,65873-15B,65873-16A,65873-16B,65890-11A,65890-11B,65890-12A,65890-12B,65890-13A,65890-13B,65890-14A,65890-14B,65890-15A,65890-15B,65890-16A,65854-18A,65854-18B,65854-19A,65854-19B,65854-20A,65854-20B,65854-21A,65854-21B,65854-22A,65854-22B,65854-23A,65854-23B,65854-24A,65854-24B,65854-25A,65854-25B,65854-26A,65854-26B,65854-27A,65854-27B,65854-28A,65854-28B,65855-24A,65855-24B,65855-25A,65855-25B,65855-26A,65855-26B,65855-27A,65855-27B,65855-28A,65855-28B,65855-29A,65855-29B,65855-30A,65855-30B,65855-31A,65855-31B,65855-32A,65855-32B,65855-33A,65855-33B,65855-34A,65855-34B,65856-19A,65856-19B,65856-20A,65856-20B,65856-21A,65856-21B,65856-22A,65856-22B,65856-23A,65856-23B,65856-24A,65856-24B,65856-25A,65856-25B,65856-26A,65856-26B,65856-27A,65856-27B,65856-28A,65856-29A,65856-29B,65857-22A,65857-22B,65857-23A,65857-23B,65857-24A,65857-24B,65857-25A,65857-25B,65857-26A,65857-26B,65857-27A,65857-27B,65857-28A,65857-28B,65857-29A,65857-29B,65857-30A,65857-30B,65857-31A,65857-31B,65857-32A,65857-32B,65858-22A,65858-22B,65858-23A,65858-23B,65858-24A,65858-24B,65858-25A,65858-25B,65858-26A,65858-26B,65858-27A,65858-27B,65858-28A,65858-28B,65858-29A,65858-29B,65858-30A,65858-30B,65858-31A,65858-31B,65858-32A,65858-32B,65859-19A,65859-19B,65859-20A,65859-20B,65859-21A,65859-21B,65859-22A,65859-22B,65859-23A,65859-23B,65859-24A,65859-24B,65859-25A,65859-25B,65859-26A,65859-26B,65859-27A,65859-27B,65859-28A,65859-28B,65859-29A,65859-29B,65860-17A,65860-17B,65860-18A,65860-18B,65860-19A,65860-19B,65860-20A,65860-20B,65860-21A,65860-21B,65860-22A,65860-22B,65860-23A,65860-23B,65860-24A,65860-24B,65860-25A,65860-25B,65860-26A,65860-26B,65860-27A,65860-27B,65861-18A,65861-18B,65861-19A,65861-19B,65861-20A,65861-20B,65861-21A,65861-21B,65861-22A,65861-22B,65861-23A,65861-23B,65861-24A,65861-24B,65861-25A,65861-25B,65861-26A,65861-26B,65861-27A,65861-27B,65861-28A,65861-28B,65866-18A,65866-18B,65866-19A,65866-19B,65866-20A,65866-20B,65866-21A,65866-21B,65866-22A,65866-22B,65866-23A,65866-23B,65866-24A,65866-24B,65866-25A,65866-25B,65866-26A,65866-26B,65866-27A,65866-27B,65866-28A,65866-28B,65867-22A,65867-22B,65867-23A,65867-23B,65867-24A,65867-24B,65867-25A,65867-25B,65867-26A,65867-26B,65867-27A,65867-27B,65867-28A,65867-28B,65867-29A,65867-29B,65867-30A,65867-30B,65867-31A,65867-31B,65867-32A,65867-32B,65867-33A,65867-33B,65868-18A,65868-18B,65868-19A,65868-19B,65868-20A,65868-20B,65868-21A,65868-21B,65868-22A,65868-22B,65868-23A,65868-23B,65868-24A,65868-24B,65868-25A,65868-25B,65868-26A,65868-26B,65868-27A,65868-27B,65868-28A,65868-28B,65868-29A,65868-29B,65868-30A,65868-30B,65868-31A,65868-31B,65868-32A,65868-32B,65868-33A,65868-33B,65868-34A,65868-34B,65868-35A,65868-35B,65868-36A,65868-36B,65868-37A,65868-37B,65868-38A,65868-38B,65868-39A,65868-39B,65870-16A,65870-16B,65870-17A,65870-17B,65870-18A,65870-18B,65870-19A,65870-19B,65870-20A,65870-20B,65870-21A,65870-21B,65870-22A,65870-22B,65870-23A,65870-23B,65870-24A,65870-24B,65870-25A,65870-25B,65870-26A,65870-26B,65871-16A,65871-16B,65871-17A,65871-17B,65871-18A,65871-18B,65871-19A,65871-19B,65871-20A,65871-20B,65871-21A,65871-21B,65871-22A,65871-22B,65871-23A,65871-23B,65871-24A,65871-24B,65871-25A,65871-25B,65871-26A,65871-26B,65872-15A,65872-16A,65872-17A,65872-18A,65872-18B,65872-19A,65872-19B,65872-20A,65872-20B,65872-15B,65872-16B,65872-17B,65872-21A,65872-21B,65872-22A,65872-22B,65872-23A,65872-23B,65872-24A,65872-24B,65872-25A,65872-25B,65873-17A,65873-17B,65873-18A,65873-18B,65873-19A,65873-19B,65873-20A,65873-20B,65873-21A,65873-21B,65873-22A,65873-22B,65873-23A,65873-23B,65873-24A,65873-25A,65873-25B,65873-26B,65873-26C,65873-27A,65873-27B,65873-28A,65873-28B,65873-30A,65873-30B,65873-31A,65873-31B,65890-17A,65890-17B,65890-18A,65890-18B,65890-19A,65890-19B,65890-20A,65890-20B,65890-21A,65890-21B,65890-22A,65890-22B,65890-23A,65890-23B,65890-24A,65890-24B,65890-25A,65890-25B,65890-26A,65890-26B,65890-27A,65890-27B,65890-28A,65890-28B,65890-29A,65890-29B,65890-30A,65890-30B,65890-31A,65890-31B

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 318, in resume
    self._resume_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 502, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 484, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 659, in resume_pipeline
    return self.run_pipeline(state=self.state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 757, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/persist.py", line 260, in run
    writer.build(state.run_groups, options=self.options)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 77, in build
    unknowns = self._make_human_unknowns(unknowns)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 434, in _make_human_unknowns
    return self._make_sheet(unks, 'Unknowns')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 553, in _make_sheet
    self._make_meta(worksheet, group)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 789, in _make_meta
    sh.write_rich_string(row, 2, group.sample, fmt)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/traits/has_traits.py", line 896, in decorator
    self.__dict__[ name ] = result = function( self )
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis_group.py", line 240, in _get_sample
    sam = self.analyses[0].sample
IndexError: list index out of range

```

**Comment by wcmcintosh** [comment]
Working fine for Streck data

**Comment by wcmcintosh** [comment]
No longer a problem.  Ready to close.
