### ISSUE TITLE
subgroup ideogram error

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1628]
active branch=None

active analyses=66465-01A,66465-01B,66465-01C,66465-02A,66465-02B,66465-02C,66465-03A,66465-03B,66465-04A,66465-05A,66465-06A,66465-07A,66465-08A,66465-09A,66465-10A,66465-11A,66465-12A,66465-13A,66465-14A,66465-15A,66465-16A,66465-17A,66465-18A,66465-19A,66465-20A,66465-21A,66465-22A,66465-23A,66465-24A,66465-25A,66465-26A,66465-27A,66465-28A,66465-29A,66465-30A

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 315, in run
    self._run_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 508, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 487, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 765, in run_pipeline
    if not node.pre_run(state, configure=configure):
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/base.py", line 83, in pre_run
    self._pre_run_hook(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/grouping.py", line 142, in _pre_run_hook
    self._run(unks)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/grouping.py", line 62, in _run
    unks = getattr(state, self.analysis_kind)
AttributeError: 'TraitListObject' object has no attribute 'unknowns'

```

**Comment by wcmcintosh** [comment]
Fixed. Ready to close.
