### ISSUE TITLE
error during last node of table pipeline

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1635]
66526 to 66533

```
root                                    : 2018-08-22 16:32:57,329 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2018-08-22 16:32:57,329 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2018-08-22 16:32:57,329 CRITICAL  (MainThread) File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
root                                    : 2018-08-22 16:32:57,329 CRITICAL  (MainThread) File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
root                                    : 2018-08-22 16:32:57,329 CRITICAL  (MainThread) File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
root                                    : 2018-08-22 16:32:57,329 CRITICAL  (MainThread) File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 318, in resume
    self._resume_pipeline()
root                                    : 2018-08-22 16:32:57,330 CRITICAL  (MainThread) File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 505, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
root                                    : 2018-08-22 16:32:57,330 CRITICAL  (MainThread) File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 487, in _run
    if not getattr(self.engine, func)():
root                                    : 2018-08-22 16:32:57,330 CRITICAL  (MainThread) File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 673, in resume_pipeline
    return self.run_pipeline(state=self.state)
root                                    : 2018-08-22 16:32:57,330 CRITICAL  (MainThread) File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 771, in run_pipeline
    node.run(state)
root                                    : 2018-08-22 16:32:57,330 CRITICAL  (MainThread) File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/nodes/persist.py", line 261, in run
    writer.build(state.run_groups, options=self.options)
root                                    : 2018-08-22 16:32:57,330 CRITICAL  (MainThread) File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 101, in build
    self._make_summary_sheet(unknowns)
root                                    : 2018-08-22 16:32:57,330 CRITICAL  (MainThread) File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 480, in _make_summary_sheet
    txt = self._get_txt(ug, ci)
root                                    : 2018-08-22 16:32:57,330 CRITICAL  (MainThread) File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 1036, in _get_txt
    v = func(item, attr)
root                                    : 2018-08-22 16:32:57,331 CRITICAL  (MainThread) File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/util.py", line 82, in value
    x = getattr(x, k)
root                                    : 2018-08-22 16:32:57,331 CRITICAL  (MainThread) File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traits/has_traits.py", line 896, in decorator
    self.__dict__[ name ] = result = function( self )
root                                    : 2018-08-22 16:32:57,331 CRITICAL  (MainThread) File "/Users/argonlab2/.pychron.1/updates/pychron/processing/analyses/analysis_group.py", line 251, in _get_arith_age
    return self._apply_j_err(aa)
root                                    : 2018-08-22 16:32:57,331 CRITICAL  (MainThread) File "/Users/argonlab2/.pychron.1/updates/pychron/processing/analyses/analysis_group.py", line 283, in _apply_j_err
    wa = ufloat(v, ne * v)
root                                    : 2018-08-22 16:32:57,331 CRITICAL  (MainThread) File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/uncertainties/core.py", line 3194, in ufloat
    return Variable(nominal_value, std_dev, tag=tag)
root                                    : 2018-08-22 16:32:57,331 CRITICAL  (MainThread) File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/uncertainties/core.py", line 2692, in __init__
    self.std_dev = std_dev  # Assignment through a Python property
root                                    : 2018-08-22 16:32:57,331 CRITICAL  (MainThread) File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/uncertainties/core.py", line 2713, in std_dev
    raise NegativeStdDev("The standard deviation cannot be negative")
root                                    : 2018-08-22 16:32:57,331 CRITICAL  (MainThread) uncertainties.core.NegativeStdDev: The standard deviation cannot be negative
root                                    : 2018-08-22 16:32:57,331 CRITICAL  (MainThread) ============ End Exception ==========


```

**Comment by wcmcintosh** [comment]
l longest getting error.  Ready tp close.
