### ISSUE TITLE
This error is occurring after a run save and prior to running the next crystal.

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1701]
active branch=release/py3/v18.2

active analyses=bu-FC-J-10183

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/jan/.pychron.1/updates/pychron/core/helpers/exception_helper.py", line 271, in run_with_except_hook
    run_old(*args, **kw)
  File "/Users/jan/anaconda/envs/pychron3/pychron.app/Contents/lib/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jan/.pychron.1/updates/pychron/experiment/experiment_executor.py", line 504, in _execute
    self._execute_queue(i, exp)
  File "/Users/jan/.pychron.1/updates/pychron/experiment/experiment_executor.py", line 641, in _execute_queue
    self._join_run(spec, run)
  File "/Users/jan/.pychron.1/updates/pychron/experiment/experiment_executor.py", line 736, in _join_run
    self._do_run(run)
  File "/Users/jan/.pychron.1/updates/pychron/experiment/experiment_executor.py", line 808, in _do_run
    run.save()
  File "/Users/jan/.pychron.1/updates/pychron/experiment/automated_run/automated_run.py", line 1013, in save
    self._persister_save_action('post_measurement_save')
  File "/Users/jan/.pychron.1/updates/pychron/experiment/automated_run/automated_run.py", line 1516, in _persister_save_action
    getattr(self.dvc_persister, func)(*args, **kw)
  File "/Users/jan/.pychron.1/updates/pychron/dvc/dvc_persister.py", line 288, in post_measurement_save
    self._save_analysis_db(timestamp)
  File "/Users/jan/.pychron.1/updates/pychron/dvc/dvc_persister.py", line 365, in _save_analysis_db
    an.measured_positions.append(dbpos)
AttributeError: 'NoneType' object has no attribute 'measured_positions'

```

**Comment by jirhiker** [comment]
error was related to a AutomateRun comment being too long (>80characters).

Added a maxlen to "comment" and increased length to 200
