### ISSUE TITLE
Grouped Analyses Interpreted Age group error

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1754]
active branch=release/py3/v18.2

active analyses=61647-03B,61647-03C,61647-03D,61647-03E,61648-03A,61648-03B,61648-03C,61648-03D,61648-03E,61646-04A,61646-04B,61646-04C,61646-04D,61646-04E,61646-05B,61646-06B,61646-07B,61646-08B,61648-04B,61648-05B,61648-06B,61648-07B,61647-08B,61647-09B,61647-10B,61647-11B,61658-01,61661-01,61663-01,61664-01,61665-01,61658-02,61658-03,61658-04,61658-05,61658-06,61658-07,61658-08,61658-09,61661-02,61661-03,61661-04,61661-05,61661-06,61661-07,61661-08,61661-09,61663-02,61663-03,61663-04,61663-05,61663-06,61663-07,61663-08,61663-09,61664-02,61664-03,61664-04,61664-05,61664-06,61664-07,61664-08,61665-02,61665-03,61665-04,61665-05,61665-06,61665-07,61665-08,61665-09,61671-01,61671-02,61671-03,61671-04,61671-09,61671-10,61671-11,61671-12,61671-13,61667-01,61667-02,61667-03,61667-04,61667-05,61667-06,61667-07,61667-08,61667-09,61668-01,61668-03,61668-04,61668-05,61668-06,61668-07,61668-08,61668-09,61668-10,61666-01,61666-02,61666-03,61666-04,61666-05,61666-06,61666-07,61666-08,61666-09,61670-01,61670-02,61670-05,61670-09,61670-10,61670-11,61670-12,61670-13,61670-14,61670-15,61666-19,61668-20,61667-19,61671-14,61665-10,61664-10,61663-10,61661-10,61658-10,61650-01,61650-02,61650-03,61650-04,61650-06,61650-07,61650-08,61650-09,61651-01,61651-02,61651-03,61651-04,61651-05,61651-06,61651-07,61651-10,61652-01,61652-02,61652-03,61652-04,61652-05,61652-06,61652-07,61652-08,61652-09,61652-10,61653-01,61653-02,61653-03,61653-04,61653-05,61653-06,61653-07,61653-08,61653-09,61653-10,61654-01,61654-02,61654-03,61654-04,61654-05,61654-06,61654-07,61654-08,61654-09,61654-10,61655-01,61655-02,61655-03,61655-04,61655-05,61655-06,61655-07,61655-08,61655-09,61655-10,61668-21,61668-22,61668-23,61668-24,61668-25,61668-26,61668-27,61668-28,61668-29,61668-30,61672-01,61672-02,61672-03,61672-06,61672-07,61672-08,61672-09,61656-01,61656-02,61656-03,61656-04,61656-05,61656-06,61656-08,61656-09,61656-10,61656-11,61656-12,61656-13,61656-14,61656-15,61659-01,61659-02,61659-03,61659-04,61659-05,61659-06,61659-07,61659-08,61659-09,61659-10,61659-11,61659-12,61659-13,61659-14,61659-15,61660-01,61660-02,61660-03,61660-04,61660-05,61660-06,61660-07,61660-08,61660-09,61660-10,61660-11,61660-12,61660-13,61660-14,61660-15,61662-26,61662-27,61662-28,61662-29,61662-30,61662-31,61662-32,61662-33,61662-34,61662-35,61662-36,61662-37,61662-38,61662-39,61662-40,61662-41,61662-42,61662-43,61662-44,61662-45,61662-46,61654-11,61654-12,61654-13,61654-14,61654-15,61654-16,61654-17,61654-18,61654-19,61654-20,61654-21,61654-22,61654-23,61654-24,61654-25,61654-26,61654-27,61654-28,61654-29,61654-30,61654-31,61654-32,61654-33,61654-34,61654-35,61652-11,61652-12,61652-13,61652-14,61652-15,61652-16,61652-17,61652-18,61652-19,61652-20,61652-21,61652-22,61652-23,61652-24,61652-25,61652-26,61652-27,61658-11,61658-12,61658-13,61653-11,61653-12,61653-13,61672-10A,61672-10B,61672-10C,61653-14,61653-15,61653-16,61653-17,61653-18,61653-19,61653-20,61653-21,61653-22,61653-23,61653-24,61646-17,61646-18,61646-19,61646-20,61646-21,61646-22,61646-23,61646-24,61646-25,61646-26,61646-27,61646-28,61646-29,61646-30,61658-14,61658-15,61658-16,61658-17,61658-18,61658-19,61658-20,61658-21,61658-22,61658-23,61658-24,61658-25,61658-26,61658-27,61659-16,61659-17,61659-18,61659-19,61659-20,61659-21,61659-22,61659-23,61659-24,61659-25,61659-26,61659-27,61659-28,61659-29,61660-16,61660-17,61660-18,61660-19,61660-20,61660-21,61660-22,61660-23,61660-24,61660-25,61660-26,61660-27,61660-28,61660-29,61660-30,61660-31,61671-15,61671-16,61671-17,61671-18,61671-19,61671-20,61671-22,61671-23,61671-24,61671-25,61671-26,61671-27,61671-28,61671-29,61671-30,61671-31,61671-32,61671-33,61671-34,61671-35,61671-36,61671-37,61671-38,61671-39,61672-11,61672-12,61672-13,61672-14,61672-15,61672-16,61672-17,61672-18,61672-19,61672-20,61672-21,61672-22,61672-23,61672-24,61672-25,61672-26,61672-27,61672-28,61672-29,61672-30,61672-31,61672-32,61672-33

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 325, in run
    self._run_pipeline()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 509, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 488, in _run
    if not getattr(self.engine, func)():
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 725, in run_pipeline
    node.run(state)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/nodes/group_age.py", line 35, in run
    editor.make_groups()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/editors/group_age_editor.py", line 188, in make_groups
    gs.append(make_interpreted_age_group(ans, gid))
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/subgrouping.py", line 94, in make_interpreted_age_group
    ag = InterpretedAgeGroup(analyses=ans, group_id=gid)
  File "/Users/argonlab2/.pychron.1/updates/pychron/processing/analyses/analysis_group.py", line 743, in __init__
    super(InterpretedAgeGroup, self).__init__(*args, **kw)
  File "/Users/argonlab2/.pychron.1/updates/pychron/processing/analyses/analysis_group.py", line 122, in __init__
    super(AnalysisGroup, self).__init__(make_arar_constants=False, *args, **kw)
  File "/Users/argonlab2/.pychron.1/updates/pychron/processing/analyses/analysis.py", line 221, in __init__
    super(IdeogramPlotable, self).__init__(*args, **kw)
  File "/Users/argonlab2/.pychron.1/updates/pychron/processing/analyses/preferred.py", line 100, in __init__
    super(Preferred, self).__init__(*args, **kw)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traits/trait_types.py", line 2339, in validate
    self.error( object, name, value )
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traits/trait_handlers.py", line 173, in error
    value )
traits.trait_errors.TraitError: The 'analyses' trait of an InterpretedAgeGroup instance must be a list of items which are any value, but a value of <generator object <genexpr> at 0x14aeacea0> <class 'generator'> was specified.

```

**Comment by nmgrluser** [comment]
Testing Complete- works great!
