### ISSUE TITLE
cannot remove points from flux calculation

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1763]
active branch=develop

active analyses=26482-01,26482-02,26482-03,26482-04,26482-05,26482-06,26483-01,26483-02,26483-03,26483-04,26483-05,26483-06,26484-01,26484-02,26484-03,26484-04,26484-05,26484-06,26485-01,26485-02,26485-03,26485-04,26485-05,26485-06,26486-01,26486-02,26486-03,26486-04,26486-05,26486-06,26487-01,26487-02,26487-03,26487-04,26487-05,26487-06,26488-01,26488-02,26488-03,26488-04,26488-05,26488-06,26489-01,26489-02,26489-03,26489-04,26489-05,26489-06

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/editors/flux_results_editor.py", line 287, in _update_graph_metadata
    self._filter_metadata_changes(obj, self.analyses, self._recalculate_means)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/arar_figure.py", line 58, in _filter_metadata_changes
    func(sel)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/editors/flux_results_editor.py", line 310, in _recalculate_means
    self.predict_values(refresh=True)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/editors/flux_visualization_editor.py", line 216, in predict_values
    self._graph_hole_vs_j(x, y, r, reg, refresh)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/editors/flux_visualization_editor.py", line 594, in _graph_hole_vs_j
    s1.error_bars.invalidate()
AttributeError: 'ErrorBarOverlay' object has no attribute 'invalidate'

```

**Comment by jirhiker** [comment]
see #1762
