### ISSUE TITLE
Running flux

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1787]
active branch=develop

active analyses=25833-01,25833-02,25833-03,25833-04,25833-05,25833-06,25834-01,25834-02,25834-03,25834-04,25834-05,25834-06,25835-01,25835-02,25835-03,25835-04,25835-05,25835-06,25836-01,25836-02,25836-03,25836-04,25836-05,25836-06,25837-01,25837-02,25837-03,25837-04,25837-05,25837-06,25838-01,25838-02,25838-03,25838-04,25838-05,25838-06,25839-01,25839-02,25839-03,25839-04,25839-05,25839-06,25840-01,25840-02,25840-03,25840-04,25840-05,25840-06

description="Running NM294B flux monitors"

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/.pychron.1/updates/pychron/core/ui/qt/tabular_editor.py", line 489, in data
    return TabularModel.data(self, mi, role)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traitsui/qt4/tabular_model.py", line 73, in data
    return adapter.get_text(obj, name, row, column)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traitsui/tabular_adapter.py", line 322, in get_text
    return self._result_for( 'get_text', object, trait, row, column )
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traitsui/tabular_adapter.py", line 530, in _result_for
    return handler()
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traitsui/tabular_adapter.py", line 581, in <lambda>
    return lambda: getattr( self, name )
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traitsui/tabular_adapter.py", line 411, in _get_text
    self.object, self.name, self.row, self.column )
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traitsui/tabular_adapter.py", line 328, in get_content
    return self._result_for( 'get_content', object, trait, row, column )
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traitsui/tabular_adapter.py", line 530, in _result_for
    return handler()
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traitsui/tabular_adapter.py", line 581, in <lambda>
    return lambda: getattr( self, name )
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traitsui/tabular_adapter.py", line 429, in _get_content
    return getattr( self.item, self.column_id )
  File "/Users/argonlab2/.pychron.1/updates/pychron/dvc/dvc_orm.py", line 183, in project
    return self.irradiation_position.sample.project.name
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 584, in get
    value = self.callable_(state, passive)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/sqlalchemy/orm/strategies.py", line 530, in _load_for_state
    (orm_util.state_str(state), self.key)
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <IrradiationPositionTbl at 0x19163e470> is not bound to a Session; lazy load operation of attribute 'sample' cannot proceed

```

**Comment by jirhiker** [comment]
User is doing something specific to produce this issue that I cannot replicate.

Cannot resolve without additional information
