### ISSUE TITLE
While I was trying to generate a table of step-heated aliquots of 65639 (this time as Grouped Analyses, previous was SubGrouped Analyses), I got this message

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1791]
active branch=develop

active analyses=65639-01A,65639-01B,65639-01C,65639-01D,65639-01E,65639-01F,65639-01G,65639-02A,65639-02B,65639-02C,65639-02D,65639-02E,65639-02F,65639-03A,65639-03B,65639-03C,65639-03D,65639-03E,65639-03F,65639-03G,65639-04A,65639-04B,65639-04C,65639-04D,65639-04E,65639-04F,65639-04G

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 346, in resume
    self._resume_pipeline()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 527, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 509, in _run
    if not getattr(self.engine, func)():
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 627, in resume_pipeline
    return self.run_pipeline(state=self.state)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 727, in run_pipeline
    node.run(state)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/nodes/persist.py", line 283, in run
    writer.build(state.run_groups, options=self.options)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 79, in build
    unknowns = self._make_human_unknowns(unknowns)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 464, in _make_human_unknowns
    return self._make_sheet(unks, 'Unknowns')
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 624, in _make_sheet
    self._make_summary(worksheet, cols, a)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 1006, in _make_summary
    sh.write_number(self._current_row, idx, trapped_value, nfmt)
UnboundLocalError: local variable 'trapped_value' referenced before assignment

```

**Comment by jirhiker** [comment]
see #1789
