### ISSUE TITLE
Trying to generate an Excel table from NM290B

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1792]
active branch=develop

active analyses=65604-01A,65604-01B,65604-01C,65604-01D,65604-01E,65604-01F,65604-01G,65604-01H,65604-01I,65604-01J,65604-01K,65604-01L,65611-01A,65611-01B,65611-01C,65611-01D,65611-01E,65611-01F,65611-01G,65611-01H,65611-01I,65611-01J,65611-01K,65611-01L,65611-01M,65611-01N,65608-01A,65608-01B,65608-01C,65608-01D,65608-01E,65608-01F,65608-01G,65607-01A,65607-01B,65607-01C,65607-01D,65607-01E,65607-01F,65607-01G,65607-01H,65607-01I,65607-01J,65605-01A,65605-01B,65605-01C,65605-01D,65605-01E,65605-01F,65605-01G,65605-01H,65605-01I,65605-01J,65605-02A,65605-02B,65605-02C,65605-02D,65605-02E,65605-02F,65605-02G,65605-02H,65605-02I,65605-02J,65610-01A,65610-01B,65610-01C,65610-01D,65610-01E,65610-01F,65610-01G,65610-01H,65610-01I,65610-01J,65610-01K,65608-02A,65608-02B,65608-02C,65608-02D,65608-02E,65608-02F,65608-02G,65608-02H,65608-02I,65608-02J,65609-01A,65609-01B,65609-01C,65609-01D,65609-01E,65609-01F,65609-01G,65609-01H,65609-01I,65609-01J

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 346, in resume
    self._resume_pipeline()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 527, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 509, in _run
    if not getattr(self.engine, func)():
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 627, in resume_pipeline
    return self.run_pipeline(state=self.state)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 727, in run_pipeline
    node.run(state)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/nodes/persist.py", line 283, in run
    writer.build(state.run_groups, options=self.options)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 79, in build
    unknowns = self._make_human_unknowns(unknowns)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 464, in _make_human_unknowns
    return self._make_sheet(unks, 'Unknowns')
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 627, in _make_sheet
    self._make_summary(worksheet, cols, group)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tables/xlsx_table_writer.py", line 1006, in _make_summary
    sh.write_number(self._current_row, idx, trapped_value, nfmt)
UnboundLocalError: local variable 'trapped_value' referenced before assignment

```

**Comment by jirhiker** [comment]
see #1789
