### ISSUE TITLE
Error in using CSV ideogram.  Extra "samples" were present in list after file selected, with runid "A", will send data via slack

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#1802]
active branch=None

active analyses=

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 346, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 347, in run
    self._run_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 534, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 513, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 723, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/data.py", line 194, in run
    unks = self._load_analyses()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/data.py", line 208, in _load_analyses
    return self._get_items_from_file(par)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/data.py", line 234, in _get_items_from_file
    for d in parser.values()]
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/data.py", line 234, in <listcomp>
    for d in parser.values()]
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/data.py", line 216, in get_case_insensitive
    for k in (key, key.lower(), key.upper(), k.capitalize()):
UnboundLocalError: local variable 'k' referenced before assignment

```

**Comment by wcmcintosh** [comment]
Problem fixed.
