### ISSUE TITLE
When transfering data from Mass Spec to Pychron I get this error message.

### ISSUE THREAD

**Issue by mattheizler** [NMGRL/pychron#1816]
active branch=develop

active analyses=66757-01A,66757-01B,66757-01C,66757-01D,66757-01E,66757-01F,66757-01G,66757-01H,66757-01I,66757-01J,66757-01K,66757-01L,66757-01M

description="I selected sample 22A under the pipeline "Mass Spec Reduced" "

Traceback
```
Traceback (most recent call last):
  File "/Users/matthewheizler/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 345, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/matthewheizler/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/matthewheizler/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 347, in run
    self._run_pipeline()
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 534, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 513, in _run
    if not getattr(self.engine, func)():
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/engine.py", line 723, in run_pipeline
    node.run(state)
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/nodes/mass_spec_reduced.py", line 86, in run
    if self.recaller.connect():
AttributeError: 'NoneType' object has no attribute 'connect'

```

**Comment by jirhiker** [comment]
you are not configured to use Mass Spec. You need to enable Mass Spec plugin and setup you mass spec database connection
