### ISSUE TITLE
Not plotting from CSV ideogram

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1818]
active branch=develop

active analyses=25809-01,25809-02,25809-03,25809-04,25809-05,25809-06,25809-07

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.4/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/figure_container.py", line 65, in _model_changed
    self.model_changed(True)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/figure_container.py", line 62, in model_changed
    self.refresh(clear=clear)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/figure_container.py", line 47, in refresh
    comp.add(p.make_graph())
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/panels/figure_panel.py", line 120, in make_graph
    fig.plot(plots, legend)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/ideogram.py", line 159, in plot
    args = getattr(self, '_plot_{}'.format(po.plot_name))(po, plotobj, pid)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/ideogram.py", line 295, in _plot_analysis_number
    return self.__plot_analysis_number(*args, **kw)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/ideogram.py", line 381, in __plot_analysis_number
    gid=self.group_id or aux_id, xs=xs, **kw)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/ideogram.py", line 780, in _add_aux_plot
    plotkw.pop('type')
KeyError: 'type'

```

**Comment by jirhiker** [comment]
see #1818
