### ISSUE TITLE
Using bracketing interpolate for blank fitting and error of SD I get this error message

### ISSUE THREAD

**Issue by mattheizler** [NMGRL/pychron#1833]
active branch=develop

active analyses=bu-FC-J-11496,bu-FC-J-11497,bu-FC-J-11498,bu-FC-J-11499,bu-FC-J-11500,bu-FC-J-11501,bu-FC-J-11502,bu-FC-J-11503,bu-FC-J-11504,bu-FC-J-11505,bu-FC-J-11506,bu-FC-J-11507,bu-FC-J-11508,bu-FC-J-11509,bu-FC-J-11510,bu-FC-J-11511,bu-FC-J-11512,bu-FC-J-11513

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/matthewheizler/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/ui/qt4/action/action_item.py", line 345, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/matthewheizler/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/matthewheizler/miniconda3/envs/pychron3/lib/python3.5/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 348, in run
    self._run_pipeline()
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 535, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 514, in _run
    if not getattr(self.engine, func)():
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/engine.py", line 723, in run_pipeline
    node.run(state)
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/nodes/fit.py", line 118, in run
    self.editor.force_update(force=True)
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/plot/editors/figure_editor.py", line 85, in force_update
    model.refresh(force=force)
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/plot/models/figure_model.py", line 43, in refresh
    p.make_graph()
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/plot/panels/figure_panel.py", line 120, in make_graph
    fig.plot(plots, legend)
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/plot/plotter/references_series.py", line 87, in plot
    self._new_fit_series(i, p)
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/plot/plotter/references_series.py", line 138, in _new_fit_series
    args = self._plot_references(pid, po)
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/plot/plotter/references_series.py", line 256, in _plot_references
    ymi, yma = self._calc_limits(r_ys, r_es)
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/plot/plotter/references_series.py", line 121, in _calc_limits
    return calc_limits(ys, ye, self.options.nsigma)
  File "/Users/matthewheizler/.pychron.0/pychron/pychron/pipeline/plot/plotter/references_series.py", line 36, in calc_limits
    ymi = (ys - (ye * n)).min()
  File "/Users/matthewheizler/miniconda3/envs/pychron3/lib/python3.5/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity

```

**Comment by jirhiker** [comment]
doesn't appear that any references were selected
