### ISSUE TITLE
Grouping Issues with CSV ideogram

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1844]
active branch=develop

active analyses=bu-FC-J-11617,bu-FC-J-11618,bu-FC-J-11619,bu-FC-J-11620,bu-FC-J-11621,bu-FC-J-11622,bu-FC-J-11623,bu-FC-J-11624,bu-FC-J-11625,bu-FC-J-11626,bu-FC-J-11627,bu-FC-J-11628,bu-FC-J-11629,bu-FC-J-11630,bu-FC-J-11631,bu-FC-J-11632,bu-FC-J-11633,bu-FC-J-11634,bu-FC-J-11635,bu-FC-J-11636,bu-FC-J-11637,bu-FC-J-11638,bu-FC-J-11639,bu-FC-J-11640,bu-FC-J-11641,bu-FC-J-11642,bu-FC-J-11643,bu-FC-J-11644,bu-FC-J-11645,bu-FC-J-11646,bu-FC-J-11647,bu-FC-J-11648,bu-FC-J-11649,bu-FC-J-11650,bu-FC-J-11651,bu-FC-J-11652,bu-FC-J-11653,bu-FC-J-11654,bu-FC-J-11655,bu-FC-J-11656,bu-FC-J-11657,bu-FC-J-11658,bu-FC-J-11659,bu-FC-J-11660,bu-FC-J-11661,bu-FC-J-11662,bu-FC-J-11663,bu-FC-J-11664,bu-FC-J-11665,bu-FC-J-11666,bu-FC-J-11667,bu-FC-J-11668,bu-FC-J-11669,bu-FC-J-11670,bu-FC-J-11671,bu-FC-J-11672,bu-FC-J-11673,bu-FC-J-11674,bu-FC-J-11675

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/ui/qt4/action/action_item.py", line 371, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/action/listening_action.py", line 74, in perform
    method()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 348, in run
    self._run_pipeline()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 535, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 524, in _run
    self._open_editor(editor)
  File "/Users/argonlab2/.pychron.1/updates/pychron/envisage/tasks/editor_task.py", line 163, in _open_editor
    self.editor_area.add_editor(editor)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/ui/qt4/tasks/advanced_editor_area_pane.py", line 98, in add_editor
    editor_widget = EditorWidget(editor, self.control)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/ui/qt4/tasks/advanced_editor_area_pane.py", line 531, in __init__
    self.editor.create(self)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/tasks/traits_editor.py", line 38, in create
    self.ui = self.edit_traits(kind='subpanel', parent=parent)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/has_traits.py", line 2024, in edit_traits
    args,
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/view.py", line 448, in ui
    ui.ui(parent, kind)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/ui.py", line 234, in ui
    self.rebuild(self, parent)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/toolkit.py", line 150, in ui_subpanel
    ui_panel.ui_subpanel(ui, parent)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 76, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 82, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
  File "/Users/argonlab2/.pychron.1/updates/launchers/helpers.py", line 136, in __init__
    self.control = panel(ui)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 263, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 556, in __init__
    self._add_splitter_items(content, splitter)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 636, in _add_splitter_items
    panel = self._add_items([item])
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 863, in _add_items
    ui, object, name, item.tooltip, None
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/editor_factory.py", line 156, in custom_editor
    description=description)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/editor.py", line 146, in __init__
    self.old_value = getattr(self.object, self.name)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/has_traits.py", line 980, in decorator
    self.__dict__[name] = result = function(self)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/graph_editor.py", line 105, in _get_component
    comp = self._component_factory()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/figure_editor.py", line 98, in _component_factory
    self._get_component_hook(model)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/ideogram_editor.py", line 99, in _get_component_hook
    t = RValuesTable(ags)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/base_matrix_table.py", line 43, in __init__
    self.recalculate()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/base_matrix_table.py", line 49, in recalculate
    results = [self.result_klass(ag, self.analysis_groups) for ag in self.analysis_groups[:-1]]
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/base_matrix_table.py", line 49, in <listcomp>
    results = [self.result_klass(ag, self.analysis_groups) for ag in self.analysis_groups[:-1]]
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/results/base_matrix_result.py", line 26, in __init__
    self.values = self._calculate_values(ag, ags)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/rvalues_table.py", line 34, in _calculate_values
    pv = other.weighted_mean_f / fstd
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/uncertainties/core.py", line 697, in f_with_affine_output
    f_nominal_value = f(*args_values, **kwargs)
ZeroDivisionError: float division by zero

```

**Comment by jirhiker** [comment]
turn off "Show R-values"
