### ISSUE TITLE
missing detector data for cocktail

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1856]
active branch=develop

active analyses=a-02-F-2264,a-02-F-2265,a-02-F-2266,a-02-F-2267,a-02-F-2268,a-02-F-2269,a-02-F-2270,a-02-F-2271,a-02-F-2272,a-02-F-2273,a-02-F-2274,a-02-F-2275,a-02-F-2276,a-02-F-2277,a-02-F-2278,a-02-F-2279,a-02-F-2280,a-02-F-2281,a-02-F-2282,a-02-F-2283,a-02-F-2284,a-02-F-2285,a-02-F-2286,a-02-F-2287

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/ui/qt4/action/action_item.py", line 371, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/action/listening_action.py", line 74, in perform
    method()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 348, in run
    self._run_pipeline()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 535, in _run_pipeline
    self._run('run pipeline', 'run_pipeline')
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 514, in _run
    if not getattr(self.engine, func)():
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 726, in run_pipeline
    node.run(state)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/nodes/fit.py", line 118, in run
    self.editor.force_update(force=True)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/figure_editor.py", line 85, in force_update
    model.refresh(force=force)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/models/figure_model.py", line 43, in refresh
    p.make_graph()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/panels/figure_panel.py", line 120, in make_graph
    fig.plot(plots, legend)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/references_series.py", line 94, in plot
    self._new_fit_series(i, p)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/references_series.py", line 145, in _new_fit_series
    args = self._plot_references(pid, po)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/references_series.py", line 259, in _plot_references
    data = self.reference_data(po)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/references_series.py", line 180, in reference_data
    ans, xs, ys = self._get_reference_data(po)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/icfactor.py", line 78, in _get_reference_data
    rys = nys / dys
ValueError: operands could not be broadcast together with shapes (24,) (0,) 

```

**Comment by jirhiker** [comment]
Looks like you have airs selected not cocktails
