### ISSUE TITLE
SubGroup Ideogram Multiple Sample Error

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1875]
active branch=develop

active analyses=66665-01A,66665-01B,66665-02A,66665-02B,66665-03A,66665-03B,66665-04,66665-05,66665-06,66665-07,66665-08,66665-09,66665-10,66665-11,66665-12,66665-13,66665-14,66665-15,66665-16,66665-17,66665-18,66665-19,66665-20,66665-21,66955-01A,66955-01B,66955-02A,66955-02B,66955-03,66955-04,66955-05,66955-06,66955-07,66955-08,66955-09,66955-10,66955-11,66955-12,66955-13,66955-14,66955-15,66955-16,66955-17,66955-18,66955-19,66955-20,67141-01A,67141-01B,67141-02A,67141-02B,67142-01A,67142-01B,67142-02A,67142-02B,67141-03,67141-04,67141-05,67141-06,67141-07,67141-08,67141-09,67141-10,67141-11,67141-12,67141-13,67141-14,67141-15,67141-16,67141-17,67141-18,67141-19,67141-20,67142-03,67142-04,67142-05,67142-06,67142-07,67142-08,67142-09,67142-10,67142-11,67142-12,67142-13,67142-14,67142-15,67142-16,67142-17,67142-18,67142-19,67142-20

description="Attempted to select 4 different samples, and group their A and B steps into a Total Integrated Age. Error pops up when I attempt to display the ideogram itself. "

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/ui/qt4/action/action_item.py", line 371, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/action/listening_action.py", line 74, in perform
    method()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 351, in resume
    self._resume_pipeline()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 532, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 524, in _run
    self._open_editor(editor)
  File "/Users/argonlab2/.pychron.1/updates/pychron/envisage/tasks/editor_task.py", line 163, in _open_editor
    self.editor_area.add_editor(editor)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/ui/qt4/tasks/advanced_editor_area_pane.py", line 98, in add_editor
    editor_widget = EditorWidget(editor, self.control)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/ui/qt4/tasks/advanced_editor_area_pane.py", line 531, in __init__
    self.editor.create(self)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/tasks/traits_editor.py", line 38, in create
    self.ui = self.edit_traits(kind='subpanel', parent=parent)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/has_traits.py", line 2024, in edit_traits
    args,
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/view.py", line 448, in ui
    ui.ui(parent, kind)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/ui.py", line 234, in ui
    self.rebuild(self, parent)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/toolkit.py", line 150, in ui_subpanel
    ui_panel.ui_subpanel(ui, parent)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 76, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 82, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
  File "/Users/argonlab2/.pychron.1/updates/launchers/helpers.py", line 136, in __init__
    self.control = panel(ui)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 263, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 556, in __init__
    self._add_splitter_items(content, splitter)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 636, in _add_splitter_items
    panel = self._add_items([item])
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/qt4/ui_panel.py", line 863, in _add_items
    ui, object, name, item.tooltip, None
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/editor_factory.py", line 156, in custom_editor
    description=description)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traitsui/editor.py", line 146, in __init__
    self.old_value = getattr(self.object, self.name)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/has_traits.py", line 980, in decorator
    self.__dict__[name] = result = function(self)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/graph_editor.py", line 105, in _get_component
    comp = self._component_factory()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/figure_editor.py", line 98, in _component_factory
    self._get_component_hook(model)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/ideogram_editor.py", line 99, in _get_component_hook
    t = RValuesTable(ags)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/base_matrix_table.py", line 43, in __init__
    self.recalculate()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/base_matrix_table.py", line 49, in recalculate
    results = [self.result_klass(ag, self.analysis_groups) for ag in self.analysis_groups[:-1]]
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/base_matrix_table.py", line 49, in <listcomp>
    results = [self.result_klass(ag, self.analysis_groups) for ag in self.analysis_groups[:-1]]
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/results/base_matrix_result.py", line 26, in __init__
    self.values = self._calculate_values(ag, ags)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/rvalues_table.py", line 29, in _calculate_values
    fstd = ag.weighted_mean_f
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/has_traits.py", line 980, in decorator
    self.__dict__[name] = result = function(self)
  File "/Users/argonlab2/.pychron.1/updates/pychron/processing/analyses/analysis_group.py", line 370, in _get_weighted_mean_f
    v, e = self._calculate_weighted_mean('uF', self.age_error_kind)
  File "/Users/argonlab2/.pychron.1/updates/pychron/processing/analyses/analysis_group.py", line 581, in _calculate_weighted_mean
    return self._calculate_mean(attr, use_weights=True, error_kind=error_kind)
  File "/Users/argonlab2/.pychron.1/updates/pychron/processing/analyses/analysis_group.py", line 472, in _calculate_mean
    av, werr = calculate_weighted_mean(vs, es)
  File "/Users/argonlab2/.pychron.1/updates/pychron/core/stats/core.py", line 60, in calculate_weighted_mean
    wmean, sum_weights = average(x, weights=weights, returned=True)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 419, in average
    scl = wgt.sum(axis=axis, dtype=result_dtype)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/numpy/core/_methods.py", line 36, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial)
TypeError: cannot perform reduce with flexible type

```

**Comment by jirhiker** [comment]
looks like you have the R-values table turned on. That is not currently compatible with Subgrouping
