### ISSUE TITLE
Tag bug?

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1879]
active branch=develop

active analyses=65328-01A,65328-01B,65328-01C,65328-01D,65328-01E,65328-01F,65328-01G,65328-02A,65328-02B,65328-02C,65328-02D,65328-02E,65328-03A,65328-03B,65328-03C,65328-03D,65328-03E,65328-04,65328-05A,65328-05B,65328-05C,65328-05D,65328-05E,65328-06A,65328-06B,65328-06C,65328-06D,65328-07,65328-08,65328-09,65328-10,65328-11A,65328-11B,65328-12A,65328-12B,65328-13A,65328-13B,65328-14A,65328-14B,65328-15A,65328-15B,65328-16A,65328-16B,65328-17A,65328-17B,65328-18A,65328-18B,65328-19A,65328-19B,65328-20A,65328-20B,65328-21A,65328-21B,65328-22A,65328-22B,65328-23A,65328-23B,65328-24A,65328-24B,65328-25A,65328-25B,66013-02B,66013-04B,66013-05,66013-08,66013-09,66013-10,66013-11,66013-12,66013-14,66013-15,66013-16,66013-17,66013-18,66013-19,66013-20,66013-21,66013-25,66013-27,66013-29

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/ui/qt4/action/action_item.py", line 371, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/action/listening_action.py", line 74, in perform
    method()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 358, in set_interpreted_age
    set_interpreted_age(self.dvc, ias)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/interpreted_age_factory.py", line 160, in set_interpreted_age
    if dvc.add_interpreted_ages(rid, iass):
  File "/Users/argonlab2/.pychron.1/updates/pychron/dvc/dvc.py", line 1209, in add_interpreted_ages
    self.repository_commit(rid, '<IA> added interpreted ages {}'.format(','.join(ialabels)))
  File "/Users/argonlab2/.pychron.1/updates/pychron/dvc/dvc.py", line 985, in repository_commit
    repo.commit(msg)
  File "/Users/argonlab2/.pychron.1/updates/pychron/git_archive/repo_manager.py", line 887, in commit
    index.commit(msg)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/git/index/base.py", line 947, in commit
    tree = self.write_tree()
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/git/index/base.py", line 538, in write_tree
    binsha, tree_items = write_tree_from_cache(entries, mdb, slice(0, len(entries)))
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/git/index/fun.py", line 268, in write_tree_from_cache
    sha, tree_entry_list = write_tree_from_cache(entries, odb, slice(ci - 1, xi), rbound + 1)  # @UnusedVariable
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/git/index/fun.py", line 268, in write_tree_from_cache
    sha, tree_entry_list = write_tree_from_cache(entries, odb, slice(ci - 1, xi), rbound + 1)  # @UnusedVariable
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/git/index/fun.py", line 246, in write_tree_from_cache
    raise UnmergedEntriesError(entry)
git.exc.UnmergedEntriesError: 100644 5e97efb7f8fc054fef49a11c122f0e7e73a337bd 1	660/tags/16-01A.tags.json

```

**Comment by jirhiker** [comment]
looks like you are trying to set an interpreted age
