### ISSUE TITLE
Clicking red flagged runID UUID in iso evo fit isoevo; 36 bs

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1887]
active branch=develop

active analyses=67424-01A,67424-01B,67424-01C,67424-01D,67424-01E,67424-01F,67424-01G,67424-01H,67424-01I,67424-01J,67424-01K,67424-01L,67424-01M,67424-01N,67425-01A,67425-01B,67425-01C,67425-01D,67425-01E,67425-01F,67425-01G,67425-01H,67425-01I,67425-01J,67425-01K,67425-01L,67425-01M,67425-01N

description="got bug when clicking red flagegd 36 bs  in isoevo results panel"

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/enable/qt4/base_window.py", line 213, in paintEvent
    self.handler.paintEvent(event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/enable/qt4/base_window.py", line 65, in paintEvent
    self._enable_window._paint(event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/enable/abstract_window.py", line 471, in _paint
    self.component.draw(gc, view_bounds=(0, 0, size[0], size[1]))
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/enable/component.py", line 427, in draw
    self._draw(gc, view_bounds, mode)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/enable/component.py", line 779, in _draw
    self._dispatch_draw(layer, gc, view_bounds, mode)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/enable/container.py", line 273, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/enable/container.py", line 273, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/enable/component.py", line 799, in _dispatch_draw
    handler(gc, view_bounds, mode)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/enable/component.py", line 877, in _draw_overlay
    overlay.overlay(self, gc, view_bounds, mode)
  File "/Users/argonlab2/.pychron.1/updates/pychron/graph/tools/info_inspector.py", line 125, in overlay
    lines = self.tool.assemble_lines()
  File "/Users/argonlab2/.pychron.1/updates/pychron/graph/tools/regression_inspector.py", line 89, in assemble_lines
    lines = make_statistics(reg, x=x)
  File "/Users/argonlab2/.pychron.1/updates/pychron/graph/tools/regression_inspector.py", line 56, in make_statistics
    mi, ma = reg.min, reg.max
  File "/Users/argonlab2/.pychron.1/updates/pychron/core/regression/base_regressor.py", line 89, in min
    return self.clean_ys.min()
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity

```

**Comment by jirhiker** [comment]
no data for that run
