### ISSUE TITLE
set invalid within ideogram pipline using ideogram plot

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#1892]
active branch=develop

active analyses=67400-01,67400-02,67400-03B,67400-03D,67400-04,67400-06,67400-07,67400-08,67400-09,67400-10,67400-11,67400-12,67400-13,67400-14,67400-15,67400-16,67400-17,67400-18,67400-19,67400-21,67400-22,67400-23,67400-24,67400-25,67400-26,67400-27,67400-28,67400-29,67400-30,67400-31,67400-32,67400-33,67400-34,67400-35,67400-36,67400-37,67400-38,67400-39,67400-40,67400-41,67400-42,67400-43,67400-45,67400-46,67400-47,67400-48,67400-49,67400-50,67400-51,67400-52,67400-53,67400-54,67400-56,67400-57,67400-58,67400-59,67400-60,67400-61,67400-62,67400-63,67400-64,67400-65,67400-66,67400-67,66252-01,66252-02,66252-03,66252-04,66252-05,66252-06,66252-07,66252-08,66252-09,66252-10,66252-11,66252-12,66252-13,66252-14,66252-15,66252-17,66252-18,66252-19,66252-20,66252-21,66252-22,66252-23,66252-25,66252-26,66252-27,66252-29,66252-30,66252-32,66252-33,66252-34,66252-35,66252-36,66252-39,66252-40,66252-41,66252-42,66252-43,66252-44,66252-45,66252-46,66252-47,66252-48,66252-49,66252-50,66252-51,66252-54,66252-56,66252-57,66252-58,66252-61,66252-63,66252-64,66252-65,66252-66,66252-67,66252-68,66252-69,66252-70,66252-71,66252-72,66252-73,66252-74,66252-75,66252-77,66252-79,66252-80,66252-81,66252-82,66252-83,66252-86,66252-88,66252-89,66252-90,66252-92,66252-93,66252-94,66252-95,66252-96,66252-97,66252-98,66252-100,66252-101,66252-103,66252-104,66252-105,66252-106,66252-107,66252-109,66252-113,66252-114,66252-115,66252-116,66252-117,66252-120,66252-121,66252-124,66252-125,66252-126,66252-128,66252-129,66252-131,66252-132,66252-135,66252-137,66252-138,66252-139,66252-141,66252-142,66252-145,66252-146,66252-147,66252-148,66252-152,66252-153,66252-154,66252-155,66252-156,66252-157,66252-158,66252-159,66252-161,66252-162,66252-163,66252-164,66252-166,66252-167,66252-168,66252-170,66252-172,66253-02,66253-03,66253-04,66253-05,66253-06,66253-07,66253-08,66253-09,66253-10,66253-11,66253-14,66253-15,66253-16,66253-17,66253-19,66253-20,66253-21,66253-22,66253-24,66253-28,66253-31,66253-32,66253-33,66253-34,66253-36,66253-39,66253-41,66253-42,66253-43,66253-44,66253-46,66253-48,66253-49,66253-51,66253-52,66253-54,66253-58,66253-59,66253-60,66253-61,66253-62,66253-63,66253-65,66253-66,66253-67,66253-70,66253-72,66253-73,66253-75,66253-77,66253-78,66253-79,66253-80,66253-81,66253-82,66253-83,66253-84,66253-85,66253-86,66253-88,66253-89,66253-90,66253-91,66253-95,66253-97,66253-99,66253-100,66253-101,66253-103,66253-104,66253-105,66253-106,66253-107,66253-108,66253-109,66254-74,66254-75,66254-95,66254-109,66254-110,66254-112,66254-113,66254-114,66254-117,66254-118,66254-123,66254-124,66254-125,66254-126,66254-131,66254-132,66254-133,66254-134,66254-135,66254-137,66254-139,66254-140,66254-141,66254-142,66254-145,66254-146,66254-147,66254-152,66254-154,66254-160,66254-161,66254-162,66254-163,66254-169,66254-173,66254-174,66254-179,66254-191,66254-192,66254-200,66254-202

description="Getting bug when right click selected DS grain and "set invalid". Seems pretty important for when culling data! Cheers."

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/has_traits.py", line 1054, in wrapper0
    return function(arg)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/has_traits.py", line 3617, in notify
    self.trait_property_changed(name, old)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/has_traits.py", line 980, in decorator
    self.__dict__[name] = result = function(self)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/graph_editor.py", line 105, in _get_component
    comp = self._component_factory()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/editors/figure_editor.py", line 96, in _component_factory
    self.figure_container.model_changed()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/figure_container.py", line 62, in model_changed
    self.refresh(clear=clear)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/figure_container.py", line 47, in refresh
    comp.add(p.make_graph())
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/panels/figure_panel.py", line 168, in make_graph
    self.figures[-1].post_make()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/arar_figure.py", line 144, in post_make
    self._fix_log_axes()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/arar_figure.py", line 173, in _fix_log_axes
    m = 10 ** math.floor(math.log10(min(ys)))
ValueError: math domain error

```

**Comment by jirhiker** [comment]
see #1891
