### ISSUE TITLE
windows installation error

### ISSUE THREAD

**Issue by goudorn** [NMGRL/pychron#1895]
Hello, 
i'm trying to instal pychron on a windows 10 machine (1909)
install.py give me an error

i installed :
Git 
Anaconda3
Microsoft Build Tools 2015 Update 3

i run in powershell : 
Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/NMGRL/pychron/develop/app_utils/install.py' -OutFile  install.py

cd /path/to/install.py
python install.py

i set my info in the installer and this occurs

========== Install App ==========
Traceback (most recent call last):
  File "install.py", line 335, in <module>
    main()
  File "install.py", line 326, in main
    install_app(cfg)
  File "install.py", line 312, in install_app
    subprocess.call(['chmod', '+x', l])
  File "C:\Users\aiem\anaconda3\envs\pychron3\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\aiem\anaconda3\envs\pychron3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\aiem\anaconda3\envs\pychron3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

i didn't find a way to do it, even manually following 
https://pychron.readthedocs.io/en/latest/user_guide/setup/quick_start.html
how can i solve this ?
thank you

**Comment by jirhiker** [comment]
it looks like you said yes to "Make a Mac OS application" during the config process.
