### ISSUE TITLE
Error when fitting blanks for WSD L# 66960

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#2007]
active branch=dev/dr

active analyses=66960-06,66960-07,66960-08,66960-09,66960-10,66960-11,66960-12,66960-13,66960-14,66960-15,66960-16,66960-17,66960-18,66960-19,66960-20,66960-21,66960-22

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/ui/qt4/action/action_item.py", line 371, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/action/listening_action.py", line 74, in perform
    method()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 367, in resume
    self._resume_pipeline()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 569, in _resume_pipeline
    self._run('resume pipeline', 'resume_pipeline')
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 551, in _run
    if not getattr(self.engine, func)():
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 642, in resume_pipeline
    return self.run_pipeline(state=self.state)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 742, in run_pipeline
    node.run(state)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/nodes/persist.py", line 149, in run
    progress_iterator(state.unknowns, wrapper, threshold=1)
  File "/Users/argonlab2/.pychron.1/updates/pychron/core/progress.py", line 146, in progress_iterator
    gen(progress)
  File "/Users/argonlab2/.pychron.1/updates/pychron/core/progress.py", line 138, in gen
    func(x, prog, i, n)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/nodes/persist.py", line 147, in wrapper
    self._save_fit(x, prog, i, n, state.saveable_keys)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/nodes/persist.py", line 162, in _save_fit
    self.dvc.save_fits(x, keys)
  File "/Users/argonlab2/.pychron.1/updates/pychron/dvc/dvc.py", line 664, in save_fits
    ai.dump_fits(keys, reviewed=True)
  File "/Users/argonlab2/.pychron.1/updates/pychron/dvc/dvc_analysis.py", line 410, in dump_fits
    isos, path = self._get_json('intercepts')
  File "/Users/argonlab2/.pychron.1/updates/pychron/dvc/dvc_analysis.py", line 633, in _get_json
    jd = dvc_load(path)
  File "/Users/argonlab2/.pychron.1/updates/pychron/dvc/__init__.py", line 97, in dvc_load
    if os.path.isfile(path):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

```

**Comment by nmgrluser** [comment]
Correction - Error messages when hitting resume to save iso evo (not blanks).
