### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#2079]
active branch=dev/dr

active analyses=69534-01A,69534-01B,69534-01C

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/Users/argonlab2/.pychron.1/updates/pychron/envisage/tasks/base_task.py", line 300, in _on_close
    close = self._prompt_for_save()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 822, in _prompt_for_save
    changed = repository_has_staged(ps)
  File "/Users/argonlab2/.pychron.1/updates/pychron/dvc/func.py", line 43, in repository_has_staged
    if repo.git.log("{}/{}..HEAD".format(remote, branch), "--oneline"):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git log origin/master..HEAD --oneline
  stderr: 'fatal: ambiguous argument 'origin/master..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]''

```

**Comment by jirhiker** [comment]
same issue with wokeness. 

origin/master doesn't exist but origin/main does
