### ISSUE TITLE
problem saving spectrum

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#2099]
active branch=dev/dr

active analyses=69535-01A,69535-01B,69535-01C,69535-01D,69535-01E,69535-01F,69535-01G,69535-01H,69535-01I,69535-01J,69535-01K

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/ui/qt4/action/action_item.py", line 371, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/action/listening_action.py", line 74, in perform
    method()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 416, in save_figure_pdf
    save_pdf(ed.component, path=path, options=sfm.pdf_options, view=True)
  File "/Users/argonlab2/.pychron.1/updates/pychron/core/pdf/save_pdf_dialog.py", line 151, in save_pdf
    gc.save()
  File "/Users/argonlab2/.pychron.1/updates/pychron/core/pdf/pdf_graphics_context.py", line 225, in save
    self.gc.save()
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/reportlab/pdfgen/canvas.py", line 1242, in save
    self._doc.SaveToFile(self._filename, self)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/reportlab/pdfbase/pdfdoc.py", line 214, in SaveToFile
    f = open(filename, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/argonlab2/Documents/Zimmerer/Biedell/BGMN-03 Spectrum.pdf'

```

**Comment by jirhiker** [comment]
likely because of the space in the file name
