### ISSUE TITLE
Tagging analyses

### ISSUE THREAD

**Issue by cburrill** [NMGRL/pychron#2115]
Unable to tag a heating step (omit, invalid, etc) on office PC or home MAC (with latest version of PyCrunch). 

After plotting a spectra and seeing a step that I would like to remove, I select the step in the analyses window and go to the 'Tag' button on the top menu bar. The step correctly appears in the tag box, then I select to 'omit' or make 'invalid' then the error pops up and I have to restart pychron in order to continue working.
I've also tried to tag steps in the browser window and an error pops up when I try that way as well.

**From error message**
Traceback (most recent call last):
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1142, "UPDATE command denied to user 'cburrill'@'129.138.12.185' for table 'AnalysisChangeTbl'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pyface/ui/qt4/action/action_item.py", line 401, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pyface/tasks/action/task_action_controller.py", line 40, in perform
    return action.perform(event)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pyface/action/listening_action.py", line 78, in perform
    method()
  File "/Users/cburrill/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 311, in set_tag
    self.dvc.tag_items(tag, items, note)
  File "/Users/cburrill/.pychron.0/pychron/pychron/dvc/dvc.py", line 1862, in tag_items
    self.set_analysis_tag(it, tag)
  File "/Users/cburrill/.pychron.0/pychron/pychron/dvc/dvc_database.py", line 346, in set_analysis_tag
    sess.add(change)
  File "/Users/cburrill/.pychron.0/pychron/pychron/database/core/database_adapter.py", line 95, in __exit__
    self._parent.close_session()
  File "/Users/cburrill/.pychron.0/pychron/pychron/database/core/database_adapter.py", line 232, in close_session
    self.session.flush()
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3298, in flush
    self._flush(objects)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3438, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3398, in _flush
    flush_context.execute()
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 234, in save_obj
    _emit_update_statements(
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 998, in _emit_update_statements
    c = connection._execute_20(
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/cburrill/opt/miniconda3/envs/pychron3/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1142, "UPDATE command denied to user 'cburrill'@'129.138.12.185' for table 'AnalysisChangeTbl'")
[SQL: UPDATE `AnalysisChangeTbl` SET tag=%(tag)s, user=%(user)s WHERE `AnalysisChangeTbl`.`idanalysischangeTbl` = %(AnalysisChangeTbl_idanalysischangeTbl)s]
[parameters: {'tag': 'omit', 'user': 'root', 'AnalysisChangeTbl_idanalysischangeTbl': 210703}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by jirhiker** [comment]
Fixed. cburrill did not have sufficient privileges enabled to allow updating the database.  UPDATE privilege added to cburrill
