### ISSUE TITLE
Error upon saving cocktail IC

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#2130]
active branch=dev/dr

active analyses=c-03-F-1209,c-03-F-1210,c-03-F-1211,c-03-F-1212,c-03-F-1213,c-03-F-1214,c-03-F-1215,c-03-F-1216,c-03-F-1217,c-03-F-1218,c-03-F-1219,c-03-F-1220,c-03-F-1221,c-03-F-1222,c-03-F-1223

description="Note: the process is saved in the recall window, suggesting the error is related to saving to GIT"

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/ui/qt4/action/action_item.py", line 371, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/action/listening_action.py", line 74, in perform
    method()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 422, in resume
    self._resume_pipeline()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 641, in _resume_pipeline
    self._run("resume pipeline", "resume_pipeline")
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/tasks/task.py", line 623, in _run
    if not getattr(self.engine, func)():
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 738, in resume_pipeline
    return self.run_pipeline(state=self.state)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/engine.py", line 844, in run_pipeline
    node.run(state)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/nodes/push.py", line 35, in run
    changed = repository_has_staged(ps)
  File "/Users/argonlab2/.pychron.1/updates/pychron/dvc/func.py", line 43, in repository_has_staged
    if repo.git.log("{}/{}..HEAD".format(remote, branch), "--oneline"):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git log origin/master..HEAD --oneline
  stderr: 'fatal: ambiguous argument 'origin/master..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]''

```

**Comment by jirhiker** [comment]
this is related to the woke change a github. `master` is not longer used as the default branch name but `master` is still hardcoded in places in pychron.  Latest version of pychron handles this `master-main` issue much better
