### ISSUE TITLE
Unable to plot

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#2134]
active branch=dev/dr

active analyses=69292-38A,69292-38B

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/trait_notifiers.py", line 394, in __call__
    self.handler(*args)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/figure_container.py", line 74, in _model_changed
    self.model_changed(True)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/figure_container.py", line 71, in model_changed
    self.refresh(clear=clear)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/figure_container.py", line 47, in refresh
    comp.add(p.make_graph())
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/panels/figure_panel.py", line 174, in make_graph
    self.figures[-1].post_make()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/arar_figure.py", line 198, in post_make
    self._fix_log_axes()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/arar_figure.py", line 228, in _fix_log_axes
    m = 10 ** math.floor(math.log10(min(ys)))
ValueError: min() arg is an empty sequence

```

**Comment by jirhiker** [comment]
FYI this was caused by trying to make a log plot of all negative numbers.

The following was added as a guard
```python
ys = ys[ys > 0]
try:
    m = 10 ** math.floor(math.log10(min(ys)))
    p.value_mapper.range.low = m
except ValueError:
    continue
```
