### ISSUE TITLE
Error upon tagging invalid

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#2136]
active branch=dev/dr

active analyses=69292-01A,69292-01B,69292-02A,69292-02B,69292-03A,69292-03B,69292-04,69292-05,69292-06,69292-07,69292-08,69292-09,69292-10,69292-11,69292-12,69292-13,69292-14,69292-15,69292-16,69292-17,69292-18,69292-19,69292-20,69292-21A,69292-21B,69292-22A,69292-22B,69292-23A,69292-23B,69292-24A,69292-24B,69292-25A,69292-25B,69292-26A,69292-26B,69292-27A,69292-27B,69292-28A,69292-28B,69292-30A,69292-30B,69292-31A,69292-31B,69292-32A,69292-32B,69292-33A,69292-33B,69292-34A,69292-34B,69292-35A,69292-35B,69292-36A,69292-36B,69292-37A,69292-37B,69292-38A,69292-38B,69292-39A,69292-39B,69292-40A,69292-40B

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/ui/qt4/action/action_item.py", line 202, in _qt4_on_triggered
    action.perform(action_event)
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/pyface/action/action.py", line 135, in perform
    self.on_perform()
  File "/Users/argonlab2/.pychron.1/updates/pychron/graph/tools/analysis_inspector.py", line 73, in _set_invalid
    ai.trigger_invalid(ans)
TypeError: 'str' object is not callable

```

**Comment by jirhiker** [comment]
`trigger_invalid` is a `str` because `ai` is not an `Analysis`.  it must be an `AnalysisGroup` which means that the "analysis" that was trying to be tagged was actually a group.  This makes sense from the list of active analyses; there is a mix of SCLF and SH data.
