### ISSUE TITLE
Unable to plot spectrum for TR-2 (69286-27 steps A and B)

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#2139]
active branch=dev/dr

active analyses=69286-27A,69286-27B

description=""

Traceback
```
Traceback (most recent call last):
  File "/Users/argonlab2/miniconda2/envs/pychron3/lib/python3.7/site-packages/traits/trait_notifiers.py", line 394, in __call__
    self.handler(*args)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/figure_container.py", line 74, in _model_changed
    self.model_changed(True)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/figure_container.py", line 71, in model_changed
    self.refresh(clear=clear)
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/figure_container.py", line 47, in refresh
    comp.add(p.make_graph())
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/panels/figure_panel.py", line 174, in make_graph
    self.figures[-1].post_make()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/arar_figure.py", line 198, in post_make
    self._fix_log_axes()
  File "/Users/argonlab2/.pychron.1/updates/pychron/pipeline/plot/plotter/arar_figure.py", line 228, in _fix_log_axes
    m = 10 ** math.floor(math.log10(min(ys)))
ValueError: min() arg is an empty sequence

```

**Comment by jirhiker** [comment]
see #2134
