### ISSUE TITLE
IC cocktails error - index.lock

### ISSUE THREAD

**Issue by jirhiker** [NMGRL/pychron#2158]
Below is the bug report. Seems like it is not pushing to github and doesn't seem to be saving in pychron.

Traceback (most recent call last):
  File "/Users/argonlab/.edm/envs/edm/lib/python3.6/site-packages/gitdb/util.py", line 323, in open
    fd = os.open(self._lockfilepath(), lockmode, int("600", 8))
FileExistsError: [Errno 17] File exists: '/Users/argonlab/Pychron/data/.dvc/repositories/SanidineDispersion/.git/index.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/argonlab/.edm/envs/edm/lib/python3.6/site-packages/pyface/ui/qt4/action/action_item.py", line 401, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/argonlab/.edm/envs/edm/lib/python3.6/site-packages/pyface/tasks/action/task_action_controller.py", line 40, in perform
    return action.perform(event)
  File "/Users/argonlab/.edm/envs/edm/lib/python3.6/site-packages/pyface/action/listening_action.py", line 78, in perform
    method()
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 432, in resume
    self._resume_pipeline()
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 651, in _resume_pipeline
    self._run("resume pipeline", "resume_pipeline")
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 633, in _run
    if not getattr(self.engine, func)():
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/engine.py", line 738, in resume_pipeline
    return self.run_pipeline(state=self.state)
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/engine.py", line 844, in run_pipeline
    node.run(state)
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/nodes/persist.py", line 224, in run
    self._persist(state, msg)
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/nodes/persist.py", line 96, in _persist
    state.unknowns, mi, "<{}>.{} {}".format(self.commit_tag, mi, msg)
  File "/Users/argonlab/.pychron.0/pychron/pychron/dvc/dvc.py", line 752, in update_analyses
    if self.repository_add_paths(expid, ps):
  File "/Users/argonlab/.pychron.0/pychron/pychron/dvc/dvc.py", line 1277, in repository_add_paths
    return repo.add_paths(paths)
  File "/Users/argonlab/.pychron.0/pychron/pychron/git_archive/repo_manager.py", line 202, in add_paths
    self.index.add(ps)
  File "/Users/argonlab/.edm/envs/edm/lib/python3.6/site-packages/git/index/base.py", line 794, in add
    self.write(ignore_extension_data=not write_extension_data)
  File "/Users/argonlab/.edm/envs/edm/lib/python3.6/site-packages/git/index/base.py", line 200, in write
    stream = lfd.open(write=True, stream=True)
  File "/Users/argonlab/.edm/envs/edm/lib/python3.6/site-packages/gitdb/util.py", line 330, in open
    raise IOError("Lock at %r could not be obtained" % self._lockfilepath())
OSError: Lock at '/Users/argonlab/Pychron/data/.dvc/repositories/SanidineDispersion/.git/index.lock' could not be obtained

**Comment by jirhiker** [comment]
manually deleting the index.lock file resolved the issue
