### ISSUE TITLE
Iso Evo not work for Diode trays

### ISSUE THREAD

**Issue by nelsiverson** [NMGRL/pychron#2230]
Traceback (most recent call last):
  File "/Users/argonlab/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_notifiers.py", line 524, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/Users/argonlab/.edm/envs/edm/lib/python3.6/site-packages/traits/trait_notifiers.py", line 486, in dispatch
    handler(*args)
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 847, in _handle_run_needed
    self.run()
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 460, in run
    self._run_pipeline()
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 683, in _run_pipeline
    self._run("run pipeline", "run_pipeline")
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/tasks/task.py", line 662, in _run
    if not getattr(self.engine, func)():
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/engine.py", line 872, in run_pipeline
    node.run(state)
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/nodes/fit.py", line 328, in run
    fs = progress_loader(unks, self._assemble_result, threshold=1, step=10)
  File "/Users/argonlab/.pychron.0/pychron/pychron/core/progress.py", line 116, in progress_loader
    items = list(gen())
  File "/Users/argonlab/.pychron.0/pychron/pychron/core/progress.py", line 98, in gen
    for ri in r:
  File "/Users/argonlab/.pychron.0/pychron/pychron/pipeline/nodes/fit.py", line 364, in _assemble_result
    smart_filter_goodness = e < f.smart_filter_values(i)
TypeError: '<' not supported between instances of 'float' and 'complex'

**Comment by nelsiverson** [comment]
Ba-03-F-1012 was corrupt somehow and removing it resolved the issue.
