### ISSUE TITLE
Spectrum - minor enhancements

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#501]
Would it be possible to add control over significant figures in the integrated age?
Also, would it be possible to slightly change the label format such that 15 displays as 15 rather than 15.0, just to clean up appearances abit?

**Comment by wcmcintosh** [comment]
Testing results: I tested the spectrum step alignment changes and they look great, especially in PDF format.  On screen, there are still some one-pixel offsets visible, especially in filled box mode, but these vanish when the PDF is saved.  One further request would be to keep the vertical leaders solid, even when the center line is dashed.  The current format of the leaders follows the centerline format.  Labeling appears to be correctly dropping zeros right of the decimal.

Integrated age significant figures working well,  although error = 0.007 does not round to 0.01 when n=2.  I can see the values of not rounding down to 0.0 if n=1, but perhaps the rounding cutoff should be <0.005 rather than <0.01.  e.g 0.006 rounds to 0.01, but 0.004 stays where it is, even for n digits < 3.

Two possible additional enhancements:
   1) significant digit control of MSWD would be great.
   2) Vertical arrangement of step over power might be better than the current horizontal arrangement.

I am seeing one error message (below) reported after each replot, but it doesn't seem to be stopping the show.
```
Traceback (most recent call last):
  File "/Users/mcintosh/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/mcintosh/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/plotters/spectrum/spectrum.py", line 289, in _update_graph_metadata
    self.plateau_overlay.selections = sel
AttributeError: 'NoneType' object has no attribute 'selections'
```
