### ISSUE TITLE
error on data load

### ISSUE THREAD

**Issue by jirhiker** [NMGRL/pychron#551]
when I load a large set of J-data, I get the following error

```
Traceback (most recent call last):
  File "/Users/mcintosh/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 514, in _dclicked_changed
    self.configure(new)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 170, in configure
    node.configure()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/data.py", line 41, in configure
    analyses = self.dvc.make_analyses(records)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 294, in make_analyses
    ret = progress_loader(records, wrapper, threshold=1)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 85, in progress_loader
    return list(gen(progress))
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 65, in gen
    r = func(x, prog, i, n)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 291, in <lambda>
    wrapper = lambda *args: self._make_record(calculate_f_only=calculate_f_only, *args)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 507, in _make_record
    a = DVCAnalysis(record.record_id, expid)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc_analysis.py", line 124, in __init__
    super(DVCAnalysis, self).__init__(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis.py", line 208, in __init__
    super(Analysis, self).__init__(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/arar_age.py", line 180, in __init__
    self.arar_constants = ArArConstants()
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/arar_constants.py", line 117, in __init__
    bind_preference(self, 'atm_4036_e', 'pychron.arar.constants.Ar40_Ar36_atm_error')
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/ui/preference_binding.py", line 72, in bind_preference
    return PreferenceBinding(**traits)
  File "/Users/mcintosh/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/apptools/preferences/preference_binding.py", line 42, in __init__
    self._set_trait(notify=False)
  File "/Users/mcintosh/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/apptools/preferences/preference_binding.py", line 139, in _set_trait
    trait_value = self._get_value(self.trait_name, value)
  File "/Users/mcintosh/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/apptools/preferences/preference_binding.py", line 116, in _get_value
    return handler.validate(self, trait_name, value)
TypeError: 'NoneType' object is not callable
traits                                  : 2015-06-24 00:38:05,055 ERROR     (MainThread) Exception occurred in traits notification handler for object: <pychron.pipeline.engine.PipelineEngine object at 0x126645b90>, trait: dclicked, old value: <undefined>, new value: Unknowns<UnknownNode>
Traceback (most recent call last):
  File "/Users/mcintosh/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 514, in _dclicked_changed
    self.configure(new)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 170, in configure
    node.configure()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/data.py", line 41, in configure
    analyses = self.dvc.make_analyses(records)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 294, in make_analyses
    ret = progress_loader(records, wrapper, threshold=1)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 85, in progress_loader
    return list(gen(progress))
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 65, in gen
    r = func(x, prog, i, n)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 291, in <lambda>
    wrapper = lambda *args: self._make_record(calculate_f_only=calculate_f_only, *args)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 507, in _make_record
    a = DVCAnalysis(record.record_id, expid)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc_analysis.py", line 124, in __init__
    super(DVCAnalysis, self).__init__(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/analyses/analysis.py", line 208, in __init__
    super(Analysis, self).__init__(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/arar_age.py", line 180, in __init__
    self.arar_constants = ArArConstants()
  File "/Users/mcintosh/Programming/git/pychron/pychron/processing/arar_constants.py", line 117, in __init__
    bind_preference(self, 'atm_4036_e', 'pychron.arar.constants.Ar40_Ar36_atm_error')
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/ui/preference_binding.py", line 72, in bind_preference
    return PreferenceBinding(**traits)
  File "/Users/mcintosh/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/apptools/preferences/preference_binding.py", line 42, in __init__
    self._set_trait(notify=False)
  File "/Users/mcintosh/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/apptools/preferences/preference_binding.py", line 139, in _set_trait
    trait_value = self._get_value(self.trait_name, value)
  File "/Users/mcintosh/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/apptools/preferences/preference_binding.py", line 116, in _get_value
    return handler.validate(self, trait_name, value)
TypeError: 'NoneType' object is not callable

```

**Comment by jirhiker** [comment]
solution is to add a ararconstants.ini file to preferences. This will populate the global preference file with default constants values.
