### ISSUE TITLE
pychron startup error

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#587]
twisted.logger module missing?

```
Traceback (most recent call last):
  File "/Users/mcintosh/Programming/git/pychron/launchers/pychron_dev.py", line 21, in <module>
    entry_point('pyexperiment', 'PyExperiment', '_dev', debug=True)
  File "/Users/mcintosh/Programming/git/pychron/launchers/helpers.py", line 834, in entry_point
    from pychron.envisage.pychron_run import launch
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/pychron_run.py", line 27, in <module>
    from pychron.logger.tasks.logger_plugin import LoggerPlugin
  File "/Users/mcintosh/Programming/git/pychron/pychron/logger/tasks/logger_plugin.py", line 23, in <module>
    from pychron.logger.tasks.actions import LogViewerAction, CurrentLogViewerAction
  File "/Users/mcintosh/Programming/git/pychron/pychron/logger/tasks/actions.py", line 27, in <module>
    from pychron.logger.logviewer import LogViewer, LogModel, TwistedLogModel
  File "/Users/mcintosh/Programming/git/pychron/pychron/logger/logviewer.py", line 26, in <module>
    from twisted.logger import eventsFromJSONLogFile
ImportError: No module named twisted.logger

Process finished with exit code 1


```

**Comment by jirhiker** [comment]
remove twisted dependency
