### ISSUE TITLE
Can't cancel exception

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#636]
```
Traceback (most recent call last):
  File "/Users/Zimmerer/anaconda/lib/python2.7/site-packages/enable/qt4/base_window.py", line 184, in paintEvent
    self.handler.paintEvent(event)
  File "/Users/Zimmerer/anaconda/lib/python2.7/site-packages/enable/qt4/base_window.py", line 50, in paintEvent
    self._enable_window._paint(event)
  File "/Users/Zimmerer/anaconda/lib/python2.7/site-packages/enable/abstract_window.py", line 420, in _paint
    self.component.draw(gc, view_bounds=(0, 0, size[0], size[1]))
  File "/Users/Zimmerer/anaconda/lib/python2.7/site-packages/enable/component.py", line 421, in draw
    self._draw(gc, view_bounds, mode)
  File "/Users/Zimmerer/anaconda/lib/python2.7/site-packages/enable/component.py", line 763, in _draw
    self._dispatch_draw(layer, bb, view_bounds, mode)
  File "/Users/Zimmerer/anaconda/lib/python2.7/site-packages/enable/container.py", line 327, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/Zimmerer/anaconda/lib/python2.7/site-packages/enable/container.py", line 327, in _dispatch_draw
    component._dispatch_draw(layer, gc, new_bounds, mode)
  File "/Users/Zimmerer/anaconda/lib/python2.7/site-packages/enable/container.py", line 312, in _dispatch_draw
    my_handler(gc, view_bounds, mode)
  File "/Users/Zimmerer/anaconda/lib/python2.7/site-packages/enable/container.py", line 352, in _draw_container_underlay
    self._draw_underlay(gc, view_bounds, mode)
  File "/Users/Zimmerer/anaconda/lib/python2.7/site-packages/enable/component.py", line 881, in _draw_underlay
    underlay.overlay(self, gc, view_bounds, mode)
  File "/Users/Zimmerer/anaconda/lib/python2.7/site-packages/chaco/axis.py", line 222, in overlay
    self._draw_component(gc, view_bounds, mode, component)
  File "/Users/Zimmerer/anaconda/lib/python2.7/site-packages/chaco/axis.py", line 247, in _draw_component
    self._compute_tick_positions(gc, component)
  File "/Users/Zimmerer/anaconda/lib/python2.7/site-packages/chaco/axis.py", line 463, in _compute_tick_positions
    raise RuntimeError, "DataRange low is greater than high; unable to compute axis ticks."
RuntimeError: DataRange low is greater than high; unable to compute axis ticks.

```

**Comment by jirhiker** [comment]
see #635
