### ISSUE TITLE
Blank filtering - set iteration error

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#653]
For filtering of blanks in Fit Blanks node, double clicking to set  "Iter" generates the following error

```
Traceback (most recent call last):
  File "/Users/mcintosh/anaconda/lib/python2.7/site-packages/traitsui/qt4/table_editor.py", line 810, in createEditor
    editor = factory_method(ui, target, name, '', parent)
  File "/Users/mcintosh/anaconda/lib/python2.7/site-packages/traitsui/editor_factory.py", line 140, in simple_editor
    description = description )
  File "/Users/mcintosh/anaconda/lib/python2.7/site-packages/traitsui/editor.py", line 133, in __init__
    self.old_value = getattr( self.object, self.name )
AttributeError: 'SeriesFitAuxPlot' object has no attribute 'filter_outlier_iterations'

```

**Comment by wcmcintosh** [comment]
I did reset to factory defaults as instructed
