### ISSUE TITLE
Message came up just prior to peak center

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#679]
Just prior to the peak center this message window popped up.
The peak center appeared to run ok.

```
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/enable/qt4/base_window.py", line 244, in sizeHint
    return self.handler.sizeHint(qt_size_hint)
  File "//anaconda/lib/python2.7/site-packages/enable/qt4/base_window.py", line 141, in sizeHint
    q_size = self._enable_window.control.size()
AttributeError: 'NoneType' object has no attribute 'size'

```

**Comment by jirhiker** [comment]
Consequence of catching all exceptions. This is a non critical exception raised by the underlying GUI toolkit.
