### ISSUE TITLE
semi auto calibration

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#721]
```
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/argonlab3/Programming/git/pychron/pychron/stage/calibration/tray_calibration_manager.py", line 181, in _calibrate_fired
    x, y, self.canvas)
  File "/Users/argonlab3/Programming/git/pychron/pychron/stage/calibration/auto_calibrator.py", line 66, in handle
    if self._check_auto_calibration():
  File "/Users/argonlab3/Programming/git/pychron/pychron/stage/calibration/auto_calibrator.py", line 248, in _check_auto_calibration
    l = smap.get_calibration_hole('west')
  File "/Users/argonlab3/Programming/git/pychron/pychron/stage/maps/base_stage_map.py", line 164, in get_calibration_hole
    key = self.calibration_holes[idx]
IndexError: list index out of range

```

**Comment by nmgrluser** [comment]
need to fix no auto rotation
