### ISSUE TITLE
Can't open experiment or create new experiment

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#729]
When I try to open experiment or create a new experiment I get this error.

```
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/pyface/ui/qt4/action/action_item.py", line 163, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "//anaconda/lib/python2.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argus2ms/Programming/git/pychron/pychron/experiment/tasks/experiment_actions.py", line 264, in perform
    open_experiment(event)
  File "/Users/argus2ms/Programming/git/pychron/pychron/experiment/tasks/experiment_actions.py", line 180, in open_experiment
    task = app.get_task(EXP_ID, False)
  File "/Users/argus2ms/Programming/git/pychron/pychron/envisage/tasks/base_tasks_application.py", line 106, in get_task
    win = self.create_window(TaskWindowLayout(tid))
  File "//anaconda/lib/python2.7/site-packages/envisage/ui/tasks/tasks_application.py", line 205, in create_window
    window.add_task(task)
  File "//anaconda/lib/python2.7/site-packages/pyface/tasks/task_window.py", line 190, in add_task
    dock_pane.create(self.control)
  File "//anaconda/lib/python2.7/site-packages/pyface/ui/qt4/tasks/dock_pane.py", line 64, in create
    contents = self.create_contents(control)
  File "//anaconda/lib/python2.7/site-packages/pyface/tasks/traits_dock_pane.py", line 53, in create_contents
    self.ui = self.edit_traits(kind='subpanel', parent=parent)
  File "//anaconda/lib/python2.7/site-packages/traits/has_traits.py", line 2089, in edit_traits
    handler, id, scrollable, args )
  File "//anaconda/lib/python2.7/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "//anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/toolkit.py", line 140, in ui_subpanel
    ui_panel.ui_subpanel( ui, parent )
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 79, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 85, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 143, in __init__
    self.control = panel(ui)
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 231, in panel
    panel = _GroupPanel(content[0], ui).control
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 570, in __init__
    layout = self._add_groups(content, inner)
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 649, in _add_groups
    panel = _GroupPanel(subgroup, self.ui).control
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 541, in __init__
    _fill_panel(sub, content, self.ui, self._add_page_item)
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 270, in _fill_panel
    gp = _GroupPanel(item, ui, suppress_label=True)
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 570, in __init__
    layout = self._add_groups(content, inner)
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 649, in _add_groups
    panel = _GroupPanel(subgroup, self.ui).control
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 572, in __init__
    layout = self._add_items(content, inner)
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 840, in _add_items
    editor.prepare(inner)
  File "//anaconda/lib/python2.7/site-packages/traitsui/editor.py", line 158, in prepare
    self.update_editor()
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/instance_editor.py", line 319, in update_editor
    self.resynch_editor()
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/instance_editor.py", line 380, in resynch_editor
    self.factory.id )
  File "//anaconda/lib/python2.7/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "//anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/toolkit.py", line 140, in ui_subpanel
    ui_panel.ui_subpanel( ui, parent )
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 79, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "//anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 92, in _ui_panel_for
    ui.prepare_ui()
  File "//anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 456, in prepare_ui
    self._do_evaluate_when(at_init=True)
  File "//anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 838, in _do_evaluate_when
    self._evaluate_condition(self._visible, 'visible', at_init)
  File "//anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 883, in _evaluate_condition
    context = self._get_context( self.context )
  File "//anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 804, in _get_context
    context2 = value.trait_get()
  File "//anaconda/lib/python2.7/site-packages/traits/has_traits.py", line 1715, in trait_get
    value = getattr( self, name, Missing )
  File "//anaconda/lib/python2.7/site-packages/traits/has_traits.py", line 1126, in decorator
    self.__dict__[ name ] = result = function( self )
  File "/Users/argus2ms/Programming/git/pychron/pychron/experiment/automated_run/factory.py", line 997, in _get_experiment_identifiers
    ids = dvc.get_experiment_identifiers()
  File "/Users/argus2ms/Programming/git/pychron/pychron/dvc/dvc_database.py", line 926, in get_experiment_identifiers
    return self._get_table_names(ExperimentTbl)
  File "/Users/argus2ms/Programming/git/pychron/pychron/dvc/dvc_database.py", line 983, in _get_table_names
    return [ni.name for ni in names]
TypeError: 'NoneType' object is not iterable

```

**Comment by jirhiker** [comment]
release 2.4 does not work with DVC plugin. Disabled DVC in initialization file
