### ISSUE TITLE
Error trying to add repository

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#751]
```
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/argus2ms/Programming/git/pychron/pychron/experiment/automated_run/factory.py", line 1269, in _add_repository_identifier_fired
    if a.do():
  File "/Users/argus2ms/Programming/git/pychron/pychron/entry/entry_views/entry.py", line 41, in do
    return self._add_loop()
  File "/Users/argus2ms/Programming/git/pychron/pychron/entry/entry_views/entry.py", line 57, in _add_loop
    if self._add_item():
  File "/Users/argus2ms/Programming/git/pychron/pychron/entry/entry_views/repository_entry.py", line 26, in _add_item
    return self.dvc.add_repository(self.value)
TypeError: add_repository() takes exactly 3 arguments (2 given)

```

**Comment by jirhiker** [comment]
temporarily fixed problem by adding dummy principal investigator to 

self.dvc.add_repository(self.value,'xxxx')
