### ISSUE TITLE
erro when file save selected after pipeline flux - database save icon not on bar

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#761]
```
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/pyface/ui/qt4/action/action_item.py", line 163, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "//anaconda/lib/python2.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/argus2ms/Programming/git/pychron/pychron/envisage/tasks/actions.py", line 402, in perform
    task.save()
  File "/Users/argus2ms/Programming/git/pychron/pychron/envisage/tasks/editor_task.py", line 104, in save
    if self.active_editor.path:
AttributeError: 'FluxResultsEditor' object has no attribute 'path'

```

**Comment by nmgrluser** [comment]
works fine when I use resume

All OK, my mistake
