### ISSUE TITLE
still not able to recall data

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#800]
set preferences for Git hub
tested connection to DVC data base
still getting error on data recall

```
                               : 2016-05-06 17:04:41,289 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2016-05-06 17:04:41,289 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2016-05-06 17:04:41,289 CRITICAL  (MainThread) File "/Users/mcintosh/anaconda/lib/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
root                                    : 2016-05-06 17:04:41,289 CRITICAL  (MainThread) File "/Users/mcintosh/anaconda/lib/python2.7/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
root                                    : 2016-05-06 17:04:41,289 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/browser_task.py", line 370, in _handle_dclicked
    self._recall_item(new.item)
root                                    : 2016-05-06 17:04:41,289 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/browser_task.py", line 313, in _recall_item
    self.recall(item, open_copy=open_copy)
root                                    : 2016-05-06 17:04:41,290 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/browser_task.py", line 186, in recall
    ans = self.dvc.make_analyses(records)
root                                    : 2016-05-06 17:04:41,290 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 506, in make_analyses
    ret = progress_loader(records, func, threshold=1, step=25)
root                                    : 2016-05-06 17:04:41,290 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 97, in progress_loader
    items = list(gen())
root                                    : 2016-05-06 17:04:41,290 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 79, in gen
    r = func(x, prog, i, n)
root                                    : 2016-05-06 17:04:41,290 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 504, in func
    calculate_f_only=calculate_f_only, *args)
root                                    : 2016-05-06 17:04:41,290 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 946, in _make_record
    a = DVCAnalysis(rid, expid)
root                                    : 2016-05-06 17:04:41,290 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc_analysis.py", line 184, in __init__
    self.rundate = datetime.datetime.strptime(jd['timestamp'], '%Y-%m-%dT%H:%M:%S')
root                                    : 2016-05-06 17:04:41,290 CRITICAL  (MainThread) KeyError: 'timestamp'
root                                    : 2016-05-06 17:04:41,290 CRITICAL  (MainThread) ============ End Exception ==========
Analysis Browser                        : 2016-05-06 17:04:41,291 DEBUG     (MainThread) recalling records <pychron.database.records.isotope_record.DVCIsotopeRecordView instance at 0x11be53440>


```

**Comment by jirhiker** [comment]
which analysis
