### ISSUE TITLE
Error when trying to plot ideogram of lipman sanidine data

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#807]
note: Lipman is appearing twice ion project window

```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/ui/qt4/action/action_item.py", line 163, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/.pychron/updates/pychron/pipeline/tasks/actions.py", line 118, in perform
    getattr(task, self.action)()
  File "/Users/mcintosh/.pychron/updates/pychron/pipeline/tasks/task.py", line 320, in set_ideogram_template
    self._set_action_template('Ideogram')
  File "/Users/mcintosh/.pychron/updates/pychron/pipeline/tasks/task.py", line 385, in _set_action_template
    self.run()
  File "/Users/mcintosh/.pychron/updates/pychron/pipeline/tasks/task.py", line 250, in run
    self._run_pipeline()
  File "/Users/mcintosh/.pychron/updates/pychron/pipeline/tasks/task.py", line 441, in _run_pipeline
    self._run('run pipeline', 'run_pipeline', close_all=True)
  File "/Users/mcintosh/.pychron/updates/pychron/pipeline/tasks/task.py", line 420, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/.pychron/updates/pychron/pipeline/engine.py", line 488, in run_pipeline
    if not node.pre_run(state):
  File "/Users/mcintosh/.pychron/updates/pychron/pipeline/nodes/base.py", line 84, in pre_run
    if self.configure(refresh=False, pre_run=True):
  File "/Users/mcintosh/.pychron/updates/pychron/pipeline/nodes/data.py", line 100, in configure
    analyses = self.dvc.make_analyses(records)
  File "/Users/mcintosh/.pychron/updates/pychron/dvc/dvc.py", line 510, in make_analyses
    ret = progress_loader(records, func, threshold=1, step=25)
  File "/Users/mcintosh/.pychron/updates/pychron/core/progress.py", line 97, in progress_loader
    items = list(gen())
  File "/Users/mcintosh/.pychron/updates/pychron/core/progress.py", line 79, in gen
    r = func(x, prog, i, n)
  File "/Users/mcintosh/.pychron/updates/pychron/dvc/dvc.py", line 508, in func
    calculate_f_only=calculate_f_only, *args)
  File "/Users/mcintosh/.pychron/updates/pychron/dvc/dvc.py", line 983, in _make_record
    pname, prod = meta_repo.get_production(a.irradiation, a.irradiation_level)
  File "/Users/mcintosh/.pychron/updates/pychron/dvc/meta_repo.py", line 304, in wrapper
    ret = func(obj, name, *args, **kw)
  File "/Users/mcintosh/.pychron/updates/pychron/dvc/meta_repo.py", line 596, in get_production
    pname = obj[level]
KeyError: u'H'


```

**Comment by wcmcintosh** [comment]
thats because there are two lipman projects
one with principal investigator BMcintosh and one with Mcintosh
