### ISSUE TITLE
stopped running

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#814]
```
Traceback (most recent call last):
  File "/Users/obama/Programming/git/pychron/pychron/core/helpers/exception_helper.py", line 257, in run_with_except_hook
    run_old(*args, **kw)
  File "/Users/obama/anaconda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/obama/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 451, in _execute
    self._execute_queue(i, exp)
  File "/Users/obama/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 572, in _execute_queue
    self._join_run(spec, run)
  File "/Users/obama/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 667, in _join_run
    self._do_run(run)
  File "/Users/obama/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 735, in _do_run
    run.save()
  File "/Users/obama/Programming/git/pychron/pychron/experiment/automated_run/automated_run.py", line 1037, in save
    self._persister_save_action('post_measurement_save')
  File "/Users/obama/Programming/git/pychron/pychron/experiment/automated_run/automated_run.py", line 1496, in _persister_save_action
    getattr(self.dvc_persister, func)(*args, **kw)
  File "/Users/obama/Programming/git/pychron/pychron/dvc/dvc_persister.py", line 182, in post_measurement_save
    self._save_analysis_db(timestamp)
  File "/Users/obama/Programming/git/pychron/pychron/dvc/dvc_persister.py", line 246, in _save_analysis_db
    db.add_repository_association(rs.repository_identifier, an)
  File "/Users/obama/Programming/git/pychron/pychron/dvc/dvc_database.py", line 312, in add_repository_association
    e.repository = repo.name
AttributeError: 'NoneType' object has no attribute 'name'

```

**Comment by jirhiker** [comment]
Bad repository name, no repository name or bug in setting repository name for runspec.
