### ISSUE TITLE
Could not start Pychron after updating

### ISSUE THREAD

**Issue by mjz1983** [NMGRL/pychron#815]
Could not start Pychron after automated update (see message below) activated during start up.

```

Traceback (most recent call last):
  File "/Users/Zimmerer/.pychron/updates/pychron/envisage/pychron_run.py", line 228, in launch
    app.run()
  File "/Users/Zimmerer/miniconda2/envs/pychron/lib/python2.7/site-packages/envisage/ui/tasks/tasks_application.py", line 131, in run
    started = self.start()
  File "/Users/Zimmerer/.pychron/updates/pychron/envisage/tasks/base_tasks_application.py", line 80, in start
    return super(BaseTasksApplication, self).start()
  File "/Users/Zimmerer/miniconda2/envs/pychron/lib/python2.7/site-packages/envisage/application.py", line 296, in start
    self.plugin_manager.start()
  File "/Users/Zimmerer/miniconda2/envs/pychron/lib/python2.7/site-packages/envisage/plugin_manager.py", line 138, in start
    map(lambda plugin: self.start_plugin(plugin), self._plugins)
  File "/Users/Zimmerer/miniconda2/envs/pychron/lib/python2.7/site-packages/envisage/plugin_manager.py", line 138, in <lambda>
    map(lambda plugin: self.start_plugin(plugin), self._plugins)
  File "/Users/Zimmerer/miniconda2/envs/pychron/lib/python2.7/site-packages/envisage/plugin_manager.py", line 148, in start_plugin
    plugin.activator.start_plugin(plugin)
  File "/Users/Zimmerer/miniconda2/envs/pychron/lib/python2.7/site-packages/envisage/plugin_activator.py", line 31, in start_plugin
    plugin.start()
  File "/Users/Zimmerer/.pychron/updates/pychron/updater/tasks/update_plugin.py", line 77, in start
    globalv.active_branch = updater.get_active_branch()
AttributeError: 'Updater' object has no attribute 'get_active_branch'

```

**Comment by jirhiker** [comment]
use three backticks (```) to enclose error messages. **Not three single quotes '''**
e.g

```
  File "/Users/Zimmerer/.pychron/updates/pychron/updater/tasks/update_plugin.py", line 77, in start
    globalv.active_branch = updater.get_active_branch()
AttributeError: 'Updater' object has no attribute 'get_active_branch'
```

**NOT**

'''
  File "/Users/Zimmerer/.pychron/updates/pychron/updater/tasks/update_plugin.py", line 77, in start
    globalv.active_branch = updater.get_active_branch()
AttributeError: 'Updater' object has no attribute 'get_active_branch'
'''

***use Preview to check your message before commenting***
