### ISSUE TITLE
error when trying diff view

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#836]
active branch=release/v2.5

active analyses=64101-01C

```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/ui/qt4/action/action_item.py", line 343, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/.pychron/updates/pychron/pipeline/tasks/browser_task.py", line 169, in diff_analysis
    if editor.setup(left):
  File "/Users/mcintosh/.pychron/updates/pychron/pipeline/editors/diff_editor.py", line 161, in setup
    right = self._find_right(left)
  File "/Users/mcintosh/.pychron/updates/pychron/pipeline/editors/diff_editor.py", line 184, in _find_right
    left.step)
  File "/Users/mcintosh/.pychron/updates/pychron/mass_spec/mass_spec_recaller.py", line 44, in find_analysis
    rec = MassSpecAnalysis()
  File "/Users/mcintosh/.pychron/updates/pychron/processing/arar_age.py", line 111, in __init__
    self.arar_constants = ArArConstants()
  File "/Users/mcintosh/.pychron/updates/pychron/processing/arar_constants.py", line 118, in __init__
    bind_preference(self, 'atm_4036_e', 'pychron.arar.constants.Ar40_Ar36_atm_error')
  File "/Users/mcintosh/.pychron/updates/pychron/core/ui/preference_binding.py", line 106, in bind_preference
    return PreferenceBinding(**traits)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/apptools/preferences/preference_binding.py", line 42, in __init__
    self._set_trait(notify=False)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/apptools/preferences/preference_binding.py", line 139, in _set_trait
    trait_value = self._get_value(self.trait_name, value)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/apptools/preferences/preference_binding.py", line 116, in _get_value
    return handler.validate(self, trait_name, value)
TypeError: 'NoneType' object is not callable

```

**Comment by jirhiker** [comment]
something wrong with your preferences. see #835
