### ISSUE TITLE
error accessing Toba air data

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#875]
The exception triggered error submission window, but kept opening an ending series of identical windows = had to force quit to stop loop

```
ot                                    : 2016-07-13 11:30:20,246 CRITICAL  (MainThread) ============ Exception ==============
root                                    : 2016-07-13 11:30:20,246 CRITICAL  (MainThread) Traceback (most recent call last):
root                                    : 2016-07-13 11:30:20,246 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/core/ui/qt/tabular_editor.py", line 491, in data
    return adapter.get_text(obj, name, row, column)
root                                    : 2016-07-13 11:30:20,247 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 323, in get_text
    return self._result_for( 'get_text', object, trait, row, column )
root                                    : 2016-07-13 11:30:20,247 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 574, in _result_for
    return handler()
root                                    : 2016-07-13 11:30:20,247 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 582, in <lambda>
    return lambda: getattr( self, name )
root                                    : 2016-07-13 11:30:20,247 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 412, in _get_text
    self.object, self.name, self.row, self.column )
root                                    : 2016-07-13 11:30:20,247 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 329, in get_content
    return self._result_for( 'get_content', object, trait, row, column )
root                                    : 2016-07-13 11:30:20,247 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 574, in _result_for
    return handler()
root                                    : 2016-07-13 11:30:20,247 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 582, in <lambda>
    return lambda: getattr( self, name )
root                                    : 2016-07-13 11:30:20,247 CRITICAL  (MainThread) File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 430, in _get_content
    return getattr( self.item, self.column_id )
root                                    : 2016-07-13 11:30:20,247 CRITICAL  (MainThread) File "/Users/mcintosh/Programming/git/pychron/pychron/database/records/isotope_record.py", line 118, in __getattr__
    return getattr(self._dbrecord, item)
root                                    : 2016-07-13 11:30:20,247 CRITICAL  (MainThread) AttributeError: 'AnalysisTbl' object has no attribute 'tag'
root                                    : 2016-07-13 11:30:20,247 CRITICAL  (MainThread) ============ End Exception ==========
roo
```

**Comment by wcmcintosh** [comment]
same error when toga unknown sample clicked on
