### ISSUE TITLE
missing module xlsxwriter on startup

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#887]
```
Traceback (most recent call last):
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/pychron_run.py", line 108, in get_klass
    m = __import__(package, globals(), locals(), [name], -1)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/plugin.py", line 32, in <module>
    from pychron.pipeline.tasks.browser_task import BrowserTask
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/browser_task.py", line 32, in <module>
    from pychron.pipeline.tasks.panes import BrowserPane, SearcherPane, AnalysisGroupsPane
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/panes.py", line 37, in <module>
    from pychron.pipeline.engine import Pipeline
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 28, in <module>
    from pychron.pipeline.nodes import FindReferencesNode
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/__init__.py", line 31, in <module>
    from pychron.pipeline.nodes.persist import DVCPersistNode, PDFFigureNode, \
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/persist.py", line 29, in <module>
    from pychron.pipeline.tables.xlsx_table_writer import XLSXTableWriter
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tables/xlsx_table_writer.py", line 19, in <module>
    import xlsxwriter
ImportError: No module named xlsxwriter


```

**Comment by jirhiker** [comment]
added xlsxwriter to dependencies. 

you will have to add manually if running from pycharm

from terminal
use
```
conda install xlsxwriter
```
