### ISSUE TITLE
another exception when running flux, after reset  This one is a show stopper.  

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#916]
active branch=release/v2.5

active analyses=24767-01,24767-02,24767-03,24767-04,24767-05,24767-06,24768-01,24768-02,24768-03,24768-04,24768-05,24768-06,24769-01,24769-02,24769-03,24769-04,24769-05,24769-06,24770-01,24770-02,24770-03,24770-04,24770-05,24770-06,24771-01,24771-02,24771-03,24771-04,24771-05,24771-06,24772-01,24772-02,24772-03,24772-04,24772-05,24772-06,24773-01,24773-02,24773-03,24773-04,24773-05,24773-06,24774-01,24774-02,24774-03,24774-04,24774-05,24774-06

```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/ui/qt4/action/action_item.py", line 343, in _qt4_on_triggered
    self.controller.perform(action, action_event)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/tasks/action/task_action_controller.py", line 31, in perform
    return action.perform(event)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/pyface/tasks/action/listening_action.py", line 58, in perform
    method()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 250, in run
    self._run_pipeline()
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 443, in _run_pipeline
    self._run('run pipeline', 'run_pipeline', close_all=True)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/tasks/task.py", line 422, in _run
    if not getattr(self.engine, func)():
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/engine.py", line 516, in run_pipeline
    node.run(state)
  File "/Users/mcintosh/Programming/git/pychron/pychron/pipeline/nodes/find.py", line 110, in run
    monitors = self.dvc.make_analyses(ans, calculate_f_only=False)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 533, in make_analyses
    ret = progress_loader(records, func, threshold=1, step=25)
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 95, in progress_loader
    items = list(gen())
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/progress.py", line 77, in gen
    r = func(x, prog, i, n)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 529, in func
    r = make_record(calculate_f_only=calculate_f_only, *args)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc.py", line 969, in _make_record
    record.irradiation_position_position)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/meta_repo.py", line 603, in get_flux
    lambda_k = ufloat(dc.get('lambda_k_total', 0), dc.get('lambda_k_total_error', 0))
AttributeError: 'float' object has no attribute 'get'

```

**Comment by wcmcintosh** [comment]
It appears that Flux seems to work OK the fird=st time an irradiation level is run and saved.  Trying to run the same dat set through again then yields this error
