### ISSUE TITLE
Error Error selecting samples using most recent browser. Possible showstopper

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#928]
active branch=release/v2.5

active analyses=

```
Traceback (most recent call last):
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/browser_model.py", line 188, in _filter_by_button_fired
    self._filter_by_hook()
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/base_browser_model.py", line 677, in _filter_by_hook
    self._load_associated_labnumbers()
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 42, in dec
    return func(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/base_browser_model.py", line 368, in _load_associated_labnumbers
    sams.extend(self._make_labnumbers())
  File "/Users/mcintosh/Programming/git/pychron/pychron/core/codetools/inspection.py", line 42, in dec
    return func(*args, **kw)
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/base_browser_model.py", line 427, in _make_labnumbers
    ls = self._retrieve_labnumbers()
  File "/Users/mcintosh/Programming/git/pychron/pychron/envisage/browser/browser_model.py", line 288, in _retrieve_labnumbers
    low_post=self.low_post if self.use_low_post else None)
  File "/Users/mcintosh/Programming/git/pychron/pychron/dvc/dvc_database.py", line 1010, in get_labnumbers
    q = q.join(PrincipalInvestigatorTbl)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 1946, in join
    from_joinpoint=from_joinpoint)
  File "<string>", line 2, in _join
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/orm/base.py", line 201, in generate
    fn(self, *args[1:], **kw)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2089, in _join
    outerjoin, create_aliases, prop)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2157, in _join_left_to_right
    self._join_to_left(l_info, left, right, onclause, outerjoin)
  File "/Users/mcintosh/miniconda2/envs/pychron/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2285, in _join_to_left
    "Tried joining to %s, but got: %s" % (right, ae))
InvalidRequestError: Could not find a FROM clause to join from.  Tried joining to <class 'pychron.dvc.dvc_orm.PrincipalInvestigatorTbl'>, but got: Can't find any foreign key relationships between 'IrradiationPositionTbl' and 'PrincipalInvestigatorTbl'.

```

**Comment by wcmcintosh** [comment]
Browser window hung up, didn't see this or other exception window until I closed browser window
