### ISSUE TITLE
changing flux values in experiment editor

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#942]
active branch=None

active analyses=

```
Traceback (most recent call last):
  File "/Users/obama/anaconda/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/obama/Programming/git/pychron/pychron/experiment/automated_run/factory.py", line 1437, in _save_flux_button_fired
    self._save_flux()
  File "/Users/obama/Programming/git/pychron/pychron/experiment/automated_run/factory.py", line 695, in _save_flux
    self.dvc.save_flux(self.labnumber, v, e)
TypeError: 'NoneType' object is not callable

```

**Comment by jirhiker** [comment]
see #941
