### ISSUE TITLE
Problems entering flux value within the experiment editor

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#943]
active branch=None

active analyses=bc-01-J-838

```
Traceback (most recent call last):
  File "/Users/jan/anaconda/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/jan/Programming/git/pychron/pychron/experiment/automated_run/factory.py", line 1430, in _save_flux_button_fired
    self._save_flux()
  File "/Users/jan/Programming/git/pychron/pychron/experiment/automated_run/factory.py", line 694, in _save_flux
    self.dvc.save_flux(self.labnumber, v, e)
TypeError: 'NoneType' object is not callable

```

**Comment by jirhiker** [comment]
Jan is not updated to the latest version. Current version has this issue resolved
