### ISSUE TITLE
cocktail recall

### ISSUE THREAD

**Issue by wcmcintosh** [NMGRL/pychron#973]
cocktail recall shows ratios rather than age

**Comment by wcmcintosh** [comment]
Testing:

recall of cocktails give a long sequence of errors


The first two errors follow:


```
Traceback (most recent call last):
  File "/Users/argonlab2/.pychron/updates/pychron/core/ui/qt/tabular_editor.py", line 488, in data
    return adapter.get_text(obj, name, row, column)
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 323, in get_text
    return self._result_for( 'get_text', object, trait, row, column )
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 531, in _result_for
    return handler()
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 582, in <lambda>
    return lambda: getattr( self, name )
  File "/Users/argonlab2/.pychron/updates/pychron/processing/analyses/view/adapters.py", line 79, in _get_noncorrected_error_text
    return floatfmt(self.item.noncorrected_error)
AttributeError: 'ComputedValue' object has no attribute 'noncorrected_error'



Traceback (most recent call last):
  File "/Users/argonlab2/.pychron/updates/pychron/core/ui/qt/tabular_editor.py", line 488, in data
    return adapter.get_text(obj, name, row, column)
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 323, in get_text
    return self._result_for( 'get_text', object, trait, row, column )
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 531, in _result_for
    return handler()
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 582, in <lambda>
    return lambda: getattr( self, name )
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 412, in _get_text
    self.object, self.name, self.row, self.column )
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 329, in get_content
    return self._result_for( 'get_content', object, trait, row, column )
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 531, in _result_for
    return handler()
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 582, in <lambda>
    return lambda: getattr( self, name )
  File "/Users/argonlab2/miniconda2/envs/pychron/lib/python2.7/site-packages/traitsui/tabular_adapter.py", line 430, in _get_content
    return getattr( self.item, self.column_id )
AttributeError: 'ComputedValue' object has no attribute 'ref_ratio'




```
