### ISSUE TITLE
Edit Default Fits

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#996]
active branch=None

active analyses=

selecting "Default Fits" from experiment editor gives this error

```
Traceback (most recent call last):
  File "/Users/jan/anaconda/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/jan/Programming/git/pychron/pychron/experiment/automated_run/factory.py", line 1254, in _default_fits_button_fired
    from pychron.experiment.automated_run.measurement_fits_selector import MeasurementFitsSelector, \
  File "/Users/jan/Programming/git/pychron/pychron/experiment/automated_run/measurement_fits_selector.py", line 45, in <module>
    class MeasurementFitsSelector(FilterFitSelector):
NameError: name 'FilterFitSelector' is not defined

```

**Comment by wcmcintosh** [comment]
No longer an issue - closed.
