### ISSUE TITLE
Cancel current run and move onto next run stalls Pychron

### ISSUE THREAD

**Issue by nmgrluser** [NMGRL/pychron#997]
active branch=None

active analyses=

```
Traceback (most recent call last):
  File "/Users/jan/anaconda/lib/python2.7/site-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/jan/anaconda/lib/python2.7/site-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "/Users/jan/Programming/git/pychron/pychron/envisage/tasks/base_task.py", line 340, in _on_close
    close = self._prompt_for_save()
  File "/Users/jan/Programming/git/pychron/pychron/experiment/tasks/experiment_task.py", line 473, in _prompt_for_save
    self.manager.executor.cancel(confirm=False)
  File "/Users/jan/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 339, in cancel
    self._cancel(*args, **kw)
  File "/Users/jan/Programming/git/pychron/pychron/experiment/experiment_executor.py", line 887, in _cancel
    arun.cancel_run(state=state)
  File "/Users/jan/Programming/git/pychron/pychron/experiment/automated_run/automated_run.py", line 716, in cancel_run
    self.finish()
  File "/Users/jan/Programming/git/pychron/pychron/experiment/automated_run/automated_run.py", line 830, in finish
    if self.spec.state not in ('not run', 'canceled', 'success', 'truncated', 'aborted'):
AttributeError: 'NoneType' object has no attribute 'state'

```

**Comment by wcmcintosh** [comment]
Old problem. Close this issue now?
